### ISSUE TITLE
Meta Data Type

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/RiverscapesXML#10]
A URL Type of data is useful to help people link in external data sources and reference items on the internet. 

There are two possible ways forward here that I'd like to explore, both mentioned by @joewheaton on his ticket here: https://github.com/Riverscapes/RaveAddIn/issues/47

More generally we need to add a little, optional `type` to the metadata to help us contextualize it. 

I'm going to suggest that we keep the list of possible types small for now and let it grow as we need it. This type will be optional to ensure backward compatibility. If no type is provided we are assuming a simple string

## Types:

* **URL**
* **RichText**: I.e. anything with linebreaks. We can use this to put in longer descriptions if we need them.
* **Markdown**: Not really sure about this one. Maybe we leave it out for now.
* **ImageUrl**: exactly like URL but we're given the hint that there may be an image we can render on the other end. Good for logos, photos etc. ***NB: This is not to be used for georeferenced photos. That's a different ball of wax entirely.***
* **ISODate**: Any string we can parse easily as a date (2020-05-19T18:47:37+00:00)
* **UnixTimestamp**: A machine-readable, numerical representation of a date, usually in milliseconds since epoch: 1589914122297

**Comment by MattReimer** [comment]
Pretty straightforward. I've added an optional attribute to the `<Meta>` tag that should allow us to intelligently render metadata if we choose.

```xml
  <!-- The type of string in the <Meta> tag. These are optional -->
  <xs:simpleType name="MetaDataStringType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="URL" />
      <xs:enumeration value="RichText" />
      <xs:enumeration value="Markdown" />
      <xs:enumeration value="ImageURL" />
      <xs:enumeration value="ISODate" />
      <xs:enumeration value="UnixTimestamp" />
    </xs:restriction>
  </xs:simpleType>
```

We can debate about the spelling or list in the enumeration but the idea is that Metadata can have a hint associated with it about how tools that read the `project.rs.xml` file should render this.

like so:

```
	<MetaData>
		<Meta name="HUCID">
			17070204
		</Meta>
		<Meta name="Region">
			CRB
		</Meta>
		<Meta name="Watershed">
			Lower John Day
		</Meta>
		<Meta name="Model">
			rf17bCnd9
		</Meta>
		<Meta name="url" type="URL">
			http://google.ca
		</Meta>
		<Meta name="url" type="UnixTimestamp">
			1589914122297
		</Meta>
	</MetaData>
```

All nodes are still strings and for now there is no additional checking about  whether the data value matches its type.

**Comment by joewheaton** [comment]
Nice one @MattReimer. I like this for the `<MetaData>` option. Two clarification questions:
1. Is that syntax of two `<Meta>` tags having same `name="url"` argument but different types (i.e. `type="URL"` and `type="UnixTimestamp"` common or specific to just this url example?
2.  In [RaveAddIn/issues/47](https://github.com/Riverscapes/RaveAddIn/issues/47) you mentioned:

> Maybe though, we need a more advanced url type too that would allow its own metadata for things like description and name.

Is this something that should be logged over here as separate issue too?

**Comment by MattReimer** [comment]
> Nice one @MattReimer. I like this for the `<MetaData>` option. Two clarification questions:
> 
> 1. Is that syntax of two `<Meta>` tags having same `name="url"` argument but different types (i.e. `type="URL"` and `type="UnixTimestamp"` common or specific to just this url example?

name can be anything. It's the `type=` that provides the hint about what the string contents of the tag are and how they should be rendered.

> 2. In [RaveAddIn/issues/47](https://github.com/Riverscapes/RaveAddIn/issues/47) you mentioned:
> 
> > Maybe though, we need a more advanced url type too that would allow its own metadata for things like description and name.
> 
> Is this something that should be logged over here as separate issue too?

Gotcha covered: #13

**Comment by MattReimer** [comment]
Ok. @philipbaileynar  and @joewheaton here's where I'm landing on meta types:

### Types:

Here's a list of the value Meta type="" attributes:

```xml
  <xs:simpleType name="MetaDataStringType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="guid" />
      <xs:enumeration value="url" />
      <xs:enumeration value="imgurl" />
      <xs:enumeration value="richtext" />
      <xs:enumeration value="markdown" />
      <xs:enumeration value="isodate" />
      <xs:enumeration value="timestamp" />
      <xs:enumeration value="float" />
      <xs:enumeration value="int" />
    </xs:restriction>
  </xs:simpleType>
```

### Examples

Now use it in an example:

```xml
			<MetaData>
				<!-- YOu don't need to use them -->
				<Meta name="Visit">2142</Meta>
				<!-- Strings don't need them -->
				<Meta name="Discharge">S0002_28816</Meta>
				<!-- These are the core ones -->
				<Meta name="parentId" type="guid">06C4CFF5-56F0-473D-95F1-8E516ECD150D</Meta>
				<Meta name="url" type="url">http://thing.com</Meta>
				<Meta name="icon" type="imgurl">http://thing.com/image.png</Meta>
				<Meta name="createdDate" type="isodate">2017-09-08T20:01:15</Meta>
				<Meta name="createdDate" type="timestamp">1614020612</Meta>
				<Meta name="valueValue" type="float">2.34234</Meta>
				<Meta name="valueValue2" type="int">121242</Meta>
				<!-- These provide flexibility for later. Initially we will not use them -->
				<Meta name="richTextValue" type="richtext">
					<![CDATA[Please describe how you feel <b>now</b>.]]>
				</Meta>
				<Meta name="description" type="markdown">
					<![CDATA[ 
					### Description

The following should be **rendered** like markdown with [links](http://google.com) etc.
					]]>
				</Meta>
			</MetaData> 
```

We can extend this list later but any concerns about the initial list or the way it's used should be handled now because I'm going to immediately start using it for RSContext and VBET

**Comment by joewheaton** [comment]
@MattReimer or @philipbaileynar thanks for this awesome solution. Can we use this excuse as a way to figure out what our workflow is to put the documentation request update in to move the basic documentation @MattReimer provided above to appropriate place at https://riverscapes.xyz/Tools/Technical_Reference/Documentation_Standards/

I'm not thinking this should be for @MattReimer or @philipbaileynar , but instead, what is our workflow to assign in the lab or to @KellyMWhitehead or whomever to update the documentation. Our pace of development and advances is far out pacing our basic documentation. Thoughts? Feel free to move this away from this issue. I just want to flag it and get your input.

**Comment by MattReimer** [comment]
This is happening today. We're going to start using them immediately in the fall release of all `riverscapes-tools`
