### ISSUE TITLE
Confinement project woes

### ISSUE THREAD

**Issue by lauren-herbine** [Riverscapes/RiverscapesXML#101]
[Here](https://youtu.be/xF0B4iQ01m0) is a short video with a question on how to get some of my symbology to "stick." @MattReimer, I am pretty sure I have done everything you explained this morning. 

1. All local files are up-to-date
2. Confinement.xml has symbology paths for the confining polygon ("confining_poly")
3. confining_poly.qml is saved to the resources folder

Anything obvious I am missing?

@shelbysawyer tagging you in case this helps later

**Comment by MattReimer** [comment]
It's probably, almost certainly the file case problem.

Git sometimes has problems with file case issues. Hang on and I'll make the changes for you,.

**Comment by MattReimer** [comment]
This is merged I think
