### ISSUE TITLE
Confinement symbology for WebRave

### ISSUE THREAD

**Issue by lauren-herbine** [Riverscapes/RiverscapesXML#107]
- [x] Confinement Raw
- [x] Confinement Margins
- [x] Confining polygon
- [x] Confinement Ratio
- [x] Constriction Ratio
- [x] Active Channel Buffer
- [x] Flowlines
- [x] Split Points
- [x] Flowline Segments
- [x] Error Polylines
- [ ] Error Polygons

**Comment by lauren-herbine** [comment]
Related to #106 and [Riverscapes/rs-web-monorepo/issues/123](https://github.com/Riverscapes/rs-web-monorepo/issues/123)

**Comment by joewheaton** [comment]
@lauren-herbine nice job on this. I like your use of the issues.

**Comment by lauren-herbine** [comment]
opening new issue for confinement updates/edits
