### ISSUE TITLE
Channel Buffer & Flow Area Symbology

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/RiverscapesXML#119]
Build the following into the business logic:

- [ ] channelbuffer
- [ ] flowarea

Create the following layers:

- [ ] channelbuffer.lyr
- [ ] channelbuffer.qml
- [ ] flowarea.lyr
- [ ] flowarea.qml

**Comment by joewheaton** [comment]
@shelbysawyer if you close something with unfinished tasks, explain why. If part of why is because it was superseded by a newer issue or commit, reference that in closing this. Thanks!
