### ISSUE TITLE
Author `*.lyr` for ArcRAVE of layer(s) and test in ArcRAVE and commit

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RiverscapesXML#124]

**Comment by shelbysawyer** [comment]
I've almost finished the `.lyr` for ArcRAVE HAND, but I can't figure out how to get rid of the outlines. [Here is a 1 minute video](https://youtu.be/vdB9QIuE0fg) explaining my question.

**Comment by shelbysawyer** [comment]
@joewheaton Sorry, ignore that please.. I didn't realize the borders weren't actually visible in the layer itself, just the TOC.
