### ISSUE TITLE
Produce screen shot of each lyr file to provide in commit or later pull request for reviewer (include legend)

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RiverscapesXML#126]

**Comment by joewheaton** [comment]
I need to spell out what this means first... then assign.

**Comment by shelbysawyer** [comment]
`hand.lyr` full layer view:
<img width="757" alt="arc_hand1" src="https://user-images.githubusercontent.com/73311751/124185087-b5bda480-da77-11eb-9b76-530d3539392c.PNG">

`hand.lyr` zoomed-in view:
<img width="752" alt="arc_hand2" src="https://user-images.githubusercontent.com/73311751/124185084-b5250e00-da77-11eb-9ef2-b5dd4d762adc.PNG">
