### ISSUE TITLE
Possible URL Type

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/RiverscapesXML#13]
We now have a Meta Type #10 but there may be a case where a more formal URL is needed as a data type that can actually be rendered on a map

This issue was first mentioned here:
https://github.com/Riverscapes/RaveAddIn/issues/47

But I'm setting up a ticket in this repo so that I can attach commits and discuss the detailed XSD implementations of the schema change.

**Comment by joewheaton** [comment]
Ignore Q2 on #10...I didn't see this.

**Comment by MattReimer** [comment]
We should be able to accomplish this now with our Meta types fix. 

- #42 
- #10
