### ISSUE TITLE
Author `*.qml` for Outputs > Capacity layers and test in QRAVE

### ISSUE THREAD

**Issue by Cashe93** [Riverscapes/RiverscapesXML#146]
- [x] Author .qml layers for BRAT Capacity layers 
-  Existing Dam Capacity 
-  Existing Dam Size
- Historic Dam Size
- Historic Dam Capacity
- [x] Commit changes to the branched repository 
- [x] Include screenshots of layers
- [x] Include link to the warehouse project that was used to test layers

**Comment by Cashe93** [comment]
[Here](https://data.riverscapes.xyz/#/Anabranch/80ba5c6f-a492-46ec-9b38-8392c2c5ce7a) is a link to the warehouse project that was used to test these layers along with screenshots of each. 

Existing Dam Capacity
![image](https://user-images.githubusercontent.com/49880208/125179801-0edfb380-e1af-11eb-9e08-0898e80fcaad.png)

Existing Dam Size
![image](https://user-images.githubusercontent.com/49880208/125179803-26b73780-e1af-11eb-836c-258abd6f58d0.png)

Historic Dam Capacity 
![image](https://user-images.githubusercontent.com/49880208/125179810-4189ac00-e1af-11eb-852a-ed3e11718783.png)

Historic Dam Size
![image](https://user-images.githubusercontent.com/49880208/125179828-8f9eaf80-e1af-11eb-9b6a-4a50b84ac44f.png)

**Comment by Cashe93** [comment]
@joewheaton, this task was created from #145. I plan on breaking that task into smaller tasks like this one. Should each of these "sub-tasks" have a pull request?

**Comment by philipbaileynar** [comment]
No @Cashe93 you can perform all the tasks on a single branch and issue a single pull request on that branch. Use as many issues/tasks as you need.

**Comment by wally-mac** [comment]
@Cashe93 Nice work! This looks good to me.

**Comment by joewheaton** [comment]
> No @Cashe93 you can perform all the tasks on a single branch and issue a single pull request on that branch. Use as many issues/tasks as you need.

Minor clarification @Cashe93. You will likely make the  task(s) for QRAVe in one pull request, the task(s) for ArcRAVE in a separate pull request, and the task(s) for the web in another. This will allow progress to proceed on each those RAVE platforms separately. The tasks (like this one for testing) that do not actually result in commits or changes to code do not need to be part of any pull request unless something is found wrong. 

Nice work.

**Comment by wally-mac** [comment]
@joewheaton thanks for the useful clarification on this.
