### ISSUE TITLE
Author `*.qml` for Outputs > Management layers and test in QRAVE

### ISSUE THREAD

**Issue by Cashe93** [Riverscapes/RiverscapesXML#147]
- [x] Author .qml layers for BRAT Management layers 
-  Unsuitable/Limited Opportunites
-  Risk of Undesirable Dams
- Restoration/Conservation Opportunity 
- [x] Commit changes to the branched repository 
- [x] Include screenshots of layers
- [x] Include link to the warehouse project that was used to test layers

**Comment by Cashe93** [comment]
Here is a link to the warehouse project that was used to test layers. 

Risk of undesirable dams
![image](https://user-images.githubusercontent.com/49880208/126851825-e66cb59c-c3d6-4b20-ab92-1c0dbc332d42.png)

Restoration/conservation opportunities 
![image](https://user-images.githubusercontent.com/49880208/126851852-4e1e3b1a-9680-4b65-a8b8-b1a2374dba7f.png)

Unsuitable or limited opportunities 
![image](https://user-images.githubusercontent.com/49880208/126851889-19adbc4d-59b1-4a29-b6cd-cf94e1e37bcf.png)

**Comment by wally-mac** [comment]
@Cashe93 These look great. Question for you. Can you show legends for these instead of the table of contents?
