### ISSUE TITLE
Potential Bug in BRAT Intermediates 

### ISSUE THREAD

**Issue by Cashe93** [Riverscapes/RiverscapesXML#157]
There should be a Slope layer and a Drainage Area layer within the Topographic Index node. However, for the project that I'm working with, there are just two Drainage Area layers. In another project, there are two Slope layers but no Drainage Area layers. 

1. Open up a project in RAVE (either ArcRAVE or QRAVE) and expand the Intermediates > Topographic Index node from the tree

![image](https://user-images.githubusercontent.com/49880208/126853574-5757a8a5-360a-433f-9bc8-9fb8454f78c1.png)

**Expected behavior**
After looking at the business logic, it looks like there should be a Slope layer as well as a Drainage Area Layer

**Desktop (please complete the following information):**
 - OS: Microsoft Windows
 - Browser: chrome
 - Version: ArcRAVE v.2.1.3 or QRAVE v. 0.5.1

**Riverscape Project (please complete the following information if relevent):**
 - Type: BRAT
 - Warehouse Link: https://data.riverscapes.xyz/#/Anabranch/80ba5c6f-a492-46ec-9b38-8392c2c5ce7a
 - Layers Impacted: Drainage Area, Slope

**Comment by philipbaileynar** [comment]
This is indeed a minor bug in [BRAT business logic](https://github.com/Riverscapes/RiverscapesXML/blob/master/RaveBusinessLogic/BRAT.xml#L49-L55). We duplicate some layers to handle BRAT projects before and after we switched to geopackages. Someone has copied these lines for the topographic index intermediates but incorrectly defined the XPaths. See the network grouping above for how it should be done properly.

Here's the current broken XML:

```xml
<Node label="Topographic Index">
    <Children>
        <Node label="Slope" xpath="Vector" type="line" symbology="iGeo_Slope" />
        <Node label="Drainage Area" xpath="Geopackage/Layers/Vector[@id='BRAT_RESULTS']" type="line" symbology="totDA_SqKm" />

        <Node label="Slope" xpath="Vector" type="line" symbology="iGeo_Slope" />
        <Node label="Drainage Area" xpath="Geopackage/Layers/Vector[@id='BRAT_RESULTS']" type="line" symbology="totDA_SqKm" />
    </Children>
</Node>
```

and here's what I think it should be:

```xml
<Node label="Topographic Index">
    <Children>
        <Node label="Slope" xpath="Vector" type="line" symbology="iGeo_Slope" />
        <Node label="Drainage Area" xpath="Vector" type="line" symbology="totDA_SqKm" />

         <Node label="Slope" xpath="Geopackage/Layers/Vector[@id='BRAT_RESULTS']" type="line" symbology="iGeo_Slope" />
         <Node label="Drainage Area" xpath="Geopackage/Layers/Vector[@id='BRAT_RESULTS']" type="line" symbology="totDA_SqKm" />
    </Children>
</Node>
```

Are you able to take it from here @Cashe93? Make a pull request for @MattReimer

**Comment by Cashe93** [comment]
Thanks, @philipbaileynar, I'll make those changes and create a pull request.

**Comment by joewheaton** [comment]
Please see #165
