### ISSUE TITLE
Author `*.qml` for Intermediates > Overall Veg Dam Capacity layers and test in QRAVE

### ISSUE THREAD

**Issue by Cashe93** [Riverscapes/RiverscapesXML#158]
- [x] Author .qml layers for BRAT Overall Veg Dam Capacity layers 
-  Existing
-  Historic 
- [x] Commit changes to the branched repository 
- [x] Include screenshots of layers
- [x] Include link to the warehouse project that was used to test layers

**Comment by Cashe93** [comment]
[Here](https://data.riverscapes.xyz/#/Anabranch/80ba5c6f-a492-46ec-9b38-8392c2c5ce7a) is the warehouse link to the project that was used to test these layers

**Comment by joewheaton** [comment]
@Cashe93, these seem a little different then what is in the ArcGIS (blue feels lighter). Are my eyes just off?

**Comment by Cashe93** [comment]
@joewheaton, I've looked into this, and all of the RGB values are the same for both ArcRAVE and QRAVE symbology files. I can go in are darken the QRAVE symbology if needed.
