### ISSUE TITLE
Add compatibility for pyBRAT 3 projects

### ISSUE THREAD

**Issue by tyler1218hatch** [Riverscapes/RiverscapesXML#175]
pyBRAT 3 has been run on many projects, and as such, it would be useful to be able to view those projects using RAVE. pyBRAT 3 already generates a project XML, so this should just be a matter of creating a business logic XML and some symbology.

@philipbaileynar, can you point me in the right direction to get started on this? Thanks!

**Comment by joewheaton** [comment]
This is superseded by #165.
