### ISSUE TITLE
Update or Add Project Views to Reflect Changes (if necc.)

### ISSUE THREAD

**Issue by Cashe93** [Riverscapes/RiverscapesXML#194]
Add project views for BRAT RAVE projects 
- [x] Existing Capacity
- [x] Historic Capacity
- [ ] Brainstorm others

**Comment by Cashe93** [comment]
View of data tree
![image](https://user-images.githubusercontent.com/49880208/128052882-c8e5beb7-3d3c-4c1b-91db-a982a76178ab.png)

Existing Capacity
![image](https://user-images.githubusercontent.com/49880208/128052414-515a9b9e-13a9-42bf-aee0-6ae040b98fb8.png)

Historic Capacity 
![image](https://user-images.githubusercontent.com/49880208/128052752-44e6052e-411d-4797-8e22-f348e970a94c.png)

**Comment by joewheaton** [comment]
Some ideas for others as project views (you're done with 1 & 2):
![image](https://user-images.githubusercontent.com/9723905/128276671-75546d15-e59d-4c7f-af21-35aad1b27c2a.png)

**Comment by Cashe93** [comment]
Thanks @joewheaton, I've added these to the project views. They should be included with #193
