### ISSUE TITLE
2. Update VBET business logic for Output Polygons from six to four)

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RiverscapesXML#198]
See https://github.com/Riverscapes/riverscapes-tools/issues/362 for guidelines.

**Comment by shelbysawyer** [comment]
@joewheaton I made the changes in the business logic to reflect having only the 4 categories, but I'm a little confused about which contours I'm meant to pull for each (I'm looking at the "Notes/Rationale" column..) or if that's another update I'll make later on?

| CategoryID | Likelihood | Label in Legend | Notes/Rationale | Old Threshold |
|---|---|---|---|---|
| 1 | >= 0.99 | Estimated Active Channel |  100|
| 2 |  0.99 < Polygon >= 0.80 | Estimated Active Floodplain  |  70|
| 3 |  0.80 < Polygon >= 0.68 | Inactive Floodplain | 50|
| 4 | >= 0.68 | Plausible Valley Bottom | 50|

**Comment by shelbysawyer** [comment]
Made a graphic for myself to visualize the new breaks, dropping it here in case it's useful to anyone else
![new_categories](https://user-images.githubusercontent.com/73311751/129083293-05f359a5-1a1a-45c2-83a8-b8a424e653fc.png)
