### ISSUE TITLE
Create new Warehouse Program for Bonneville Environmental Foundation

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/RiverscapesXML#200]
We are about to produce 9 riverscapes models for the Bonneville Environmental Foundation. USU is going to review the outputs and potentially generate additional curated copies of the projects.

Where relevant you can use the abbreviation BEF, but I would prefer the program name to be spelled out in full.

Can you please create a new private program called "Bonneville Environmental Foundation". These three types of projects are:

- riverscapes context
- VBET
- BRAT

All three project types will be at the HUC8 scale.

You can make me and Wally administrators of the program. Casche and Tanner Nielson (warehouse login: tanner.a.nielsen@aggiemail.usu.edu) are users.

**Comment by MattReimer** [comment]
Quick clarification. 

Dou mean: 

* RSContext
* ChannelArea
* TauDEM
* VBET
* BRAT

becayse VBET now depends on more than just RSContext

**Comment by philipbaileynar** [comment]
That is correct. Thanks for the clarification.

**Comment by MattReimer** [comment]
This is done.
