### ISSUE TITLE
Author .qmls for pyBRAT Outputs as needed

### ISSUE THREAD

**Issue by Cashe93** [Riverscapes/RiverscapesXML#209]
- [x] Author .qml layers for pyBRAT Outputs 
-  Existing dam capacity
-  Existing dam size
- Historic dam capacity
- Historic dam size
- Unsuitable or limited opportunities 
-  Risk of undesirable dams
- Restoration or conservation 
- Validation??? 
- [x] Commit changes to the branched repository 
- [x] Include screenshots of layers

**Comment by Cashe93** [comment]
All pyBRAT Outputs 

![image](https://user-images.githubusercontent.com/49880208/129280821-9e00297d-449a-4e71-8d05-1f5265ed8b62.png)
![image](https://user-images.githubusercontent.com/49880208/129280913-2854fe11-8c09-4ded-83a8-a23fcb40fdc0.png)
![image](https://user-images.githubusercontent.com/49880208/129281026-f5cb700e-bbb1-4ae9-b359-1e14b9a33e23.png)
![image](https://user-images.githubusercontent.com/49880208/129281890-d345900a-012d-49cd-b63a-8958a32f2dac.png)
![image](https://user-images.githubusercontent.com/49880208/129282004-659e96ba-a6b2-40fe-81d6-9df29e1a6811.png)
![image](https://user-images.githubusercontent.com/49880208/129282089-3242b7e2-f1b3-43c7-b4d9-cb264c0578fc.png)
![image](https://user-images.githubusercontent.com/49880208/129282174-e1573da7-fca1-4177-9f61-9329eecb34de.png)

**Comment by joewheaton** [comment]
Colors look good, but symbology does seem rather thick on line types?

**Comment by Cashe93** [comment]
@wally-mac and @joewheaton, perhaps you guys could fill me in on what these validation layers are supposed to be portraying? 

- Risk Validation Flooding
- Risk Validation TreeCutting
- Data Capture Validation 

These are the three that would need to be included, but it would be helpful to know what they are depicting, and more specifically which attribute field is unique and should be symbolized for each validation layer? I can't see any difference between the Risk_Tree, Risk_Flood, and the Risk layer that's already included in Business logic. Any guidance would be greatly appreciated. 

Here is a pyBRAT project: https://northarrowresearchlabs.github.io/riverscapes-staging//#/Anabranch/289f7564-453a-4eb5-84a9-18b5a2f86840

**Comment by Cashe93** [comment]
Also, in order to add the Flooding and TreeCut risk validations, we would have to go back and add them to every legacy project since they weren't included in the original. However, Data Capture Validation should already be included in the project XMLs.

**Comment by wally-mac** [comment]
@Cashe93 great questions.  First off the Flooding and TreeCut risk validations was something we did only in the Idaho run of BRAT because IDF&G provided field based beaver conflict complaints (which included beaver caused flooding and tree cutting).  So, we will not have to reproduce this for other BRAT runs.  

Secondly, for the data capture validation [here is a link ](https://usu.box.com/s/ysuuwgzsd6bj93c1m0o2h05k5ckr4zht )to a layerpackage that shows the standard symbology for the validation feature classes.

**Comment by Cashe93** [comment]
Thanks,  @wally-mac!

**Comment by wally-mac** [comment]
@Cashe93 what if anything remains on the tasks related to this "ticket"? Is validation now symbolized?

**Comment by Cashe93** [comment]
Validation is now symbolized. Everything should be up to date.
