### ISSUE TITLE
Author .qmls for pyBRAT Intermediates as needed

### ISSUE THREAD

**Issue by Cashe93** [Riverscapes/RiverscapesXML#210]
- [x] Author .qml layers that are needed for pyBRAT Intermediates
- [x] Commit changes to the branched repository 
- [x] Include screenshots of layers

**Comment by Cashe93** [comment]
All pyBRAT Intermediates 

![image](https://user-images.githubusercontent.com/49880208/129277164-158988fc-c277-4715-a3cf-bc44865b52da.png)
![image](https://user-images.githubusercontent.com/49880208/129277274-81070f6a-c70a-4405-897e-4062e0128022.png)
![image](https://user-images.githubusercontent.com/49880208/129277405-f7747969-da0f-4707-b064-63ac12a1bb90.png)
![image](https://user-images.githubusercontent.com/49880208/129277674-89fb294a-c6f5-48d9-9b7f-575778da7d4b.png)
![image](https://user-images.githubusercontent.com/49880208/129277802-7f28a00e-ec9e-4f3d-b0fb-ad48b6edcaba.png)
![image](https://user-images.githubusercontent.com/49880208/129278065-acbd6234-70a9-435e-ae22-5f0c6d670fd5.png)
![image](https://user-images.githubusercontent.com/49880208/129278169-c4533cd8-eaea-49dc-8644-b7af7b080b6a.png)
![image](https://user-images.githubusercontent.com/49880208/129278252-e1f11b4c-64cb-48e1-a6e8-6530c43f082d.png)
![image](https://user-images.githubusercontent.com/49880208/129278769-121bd746-86df-4058-bdcb-6ade77ac01b9.png)
![image](https://user-images.githubusercontent.com/49880208/129278977-3842f29c-be34-415a-8186-b8e946ad3aba.png)
![image](https://user-images.githubusercontent.com/49880208/129279203-7d2d9b76-2921-4652-a0e0-73794405d2b3.png)
![image](https://user-images.githubusercontent.com/49880208/129279347-44406318-3176-4537-a43a-eb3e43699c74.png)
![image](https://user-images.githubusercontent.com/49880208/129279491-25817afe-570d-40c7-be14-3adbe69ac203.png)
![image](https://user-images.githubusercontent.com/49880208/129279598-3efc2215-f236-4365-b351-578a96f394b2.png)
![image](https://user-images.githubusercontent.com/49880208/129279747-0f2d1bcf-7b2d-4764-9c29-2cc8ca8d42b1.png)
![image](https://user-images.githubusercontent.com/49880208/129279855-f182efac-c200-463f-bc34-210be2e88f6b.png)
![image](https://user-images.githubusercontent.com/49880208/129280060-20528805-5f4e-4d71-a907-d9d28da5d245.png)
![image](https://user-images.githubusercontent.com/49880208/129280171-a3ccb3c0-ae22-4e82-9fc1-f5426b4113af.png)
![image](https://user-images.githubusercontent.com/49880208/129280286-3365e2b6-9fb7-4270-bc76-cddd509578aa.png)
![image](https://user-images.githubusercontent.com/49880208/129280386-e4bfe1e7-f380-40f9-ae51-5f03a6f50862.png)
![image](https://user-images.githubusercontent.com/49880208/129280444-06b6cf5d-4c17-4801-88b0-3e4f8f30612d.png)

**Comment by joewheaton** [comment]
Nice work @Cashe93. These look great.
