### ISSUE TITLE
Author `*.qml` for QRAVE of TauDEM layers

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/RiverscapesXML#215]

**Comment by shelbysawyer** [comment]
- [ ] rasterized_channel.qml (Rasterized Channel)
- [ ] pitfull.qml (Pitfill)
- [ ] dinfflowdir_ang.qml (D∞ Flow Directions)
- [ ] aredinf_sca.qml (D∞ Contributing Area)
- [ ] twi.qml (TWI)

**Comment by shelbysawyer** [comment]
TWI:
<img width="1117" alt="Qtwi2" src="https://user-images.githubusercontent.com/73311751/129388547-6b6368db-08bd-4424-a099-8a171078af8c.PNG">
<img width="1119" alt="Qtwi" src="https://user-images.githubusercontent.com/73311751/129388556-90f42a2d-e688-4150-a78c-11c3d481e8eb.PNG">

Rasterized Channel:
<img width="1117" alt="Qrasterized_channel" src="https://user-images.githubusercontent.com/73311751/129388604-bf45e89b-2ba4-4368-87b8-dad5f7c8bc4e.PNG">

D∞ Contributing Area:
<img width="996" alt="areadinf_sca" src="https://user-images.githubusercontent.com/73311751/129388657-9e67b28a-4d5b-454b-a481-3f2818e58f9f.PNG">
<img width="995" alt="areadinf_sca2" src="https://user-images.githubusercontent.com/73311751/129388668-e991998d-348a-4a3d-a3aa-00ec73f9c08b.PNG">

**Comment by joewheaton** [comment]
These look great @shelbysawyer. This is done.
