### ISSUE TITLE
Base Map XSD

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/RiverscapesXML#221]
We need an XSD for the new [BaseMap.xml](https://github.com/Riverscapes/RaveAddIn/blob/master/RaveAddIn/BaseMaps.xml) file that ships with RAVE. This will also be referenced by the custom file that users write in APPDATA folder.

**Comment by MattReimer** [comment]
https://github.com/Riverscapes/RiverscapesXML/blob/master/BaseMaps.xsd

This is done
