### ISSUE TITLE
Demo fmLTPBR Project

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/RiverscapesXML#23]
Create a demo riverscapes project for Nick Weber's fmLTPBR app. He has exported a set of CSV files that can be downloaded here:

https://ecologicalresearchinc.app.box.com/s/y5e6a8b9vrdqhchca4pjtaqm7u94qkij

Here is a schematic of the database relationships:

![Screen Shot 2020-05-29 at 10 56 45 AM](https://user-images.githubusercontent.com/8645379/84323692-1b1cbb80-ab2c-11ea-8c97-455edd19c723.png)

## Approach

The goal is to do this as quickly and simply as possible.

This demo riverscapes project is going to be used in RAVE, so obviously it will centre around building point geometry feature classes from those tables that have latitude and longitude attributes. 

More sophisticated, one might build a single Spatialite database which each of the spatial tables as a separate layer, linked by foreign keys. We currently don't have a way of displaying Spatialite layers in RAVE, so going this route would demand that RAVE get updated. Displaying Spatialite layers in RAVE is something we are curious about, but not an immediate priority.

The photoes are another challenge. [ArcGIS has a geoprocessing tool for doing this](https://desktop.arcgis.com/en/arcmap/10.3/tools/data-management-toolbox/geotagged-photos-to-points.htm). If we like the way ArcGIS displays the results of this tool, perhaps we mimic the data structure that this tool produces and leverage ESRI's display approach.

**Comment by MattReimer** [comment]
One thing we didn't mention was where to put this. It has different metadata than other projects so I'm not sure exactly where it fits. Did we want this in the warehouse in its own program?

**Comment by philipbaileynar** [comment]
For now just Anabranch program. Add metadataas needed.

**Comment by MattReimer** [comment]
https://northarrowresearchlabs.github.io/riverscapes/#/Anabranch/24b3a2c3-1ddd-4a56-94e9-acf35441f5eb
