### ISSUE TITLE
We need to convert all the GUT *.lyr files to *.qml files of the same name:

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RiverscapesXML#233]
-In GUT
- [x]  ev_Contours
- [x] ev_bfCh
- [x] ev_bfSlopeCat
- [x] ev_bsSDCat
- [x] ev_channelEdge
- [x] ev_contourNodes
- [x] ev_contourPolygons
- [x] ev_mBendIndex
- [ ] ev_normFill
- [x] ev_resDepth
- [ ] ev_resTopo
- [x] ev_tmp
- [ ] in_BankfullCenterline
- [x] in_BankfullExtent
- [x] in_Thalwegs_Channel
- [ ] in_Thalwegs_Type
- [x] in_WaterCenterlin
- [x] in_WaterExtent
- [x] out_Tier1_FlowUnit
- [x] out_Tier1_ValleyUnit
- [x] out_Tier2_UnitForm
- [x] out_Tier2_UnitForm_Discrete
- [x] out_Tier2_UnitShape
- [x] out_Tier3_GU
- [x] out_Tier3_GeomorphicUnit
- [x] out_Tier3_Orientation
- [x] out_Tier3_Position
- [x] out_Tier3_SubGU
- [x] raster_slope

In Shared
- [x] bf_CL
- [x] XS_qaqc
- [x] XS_type
- [x] bfIslands
- [x] wetIslands
- [x] cu_UnitNum

**Comment by CHafen** [comment]
Hey @Cashe93 I'm working on converting .lyr to .qml for GUT. I'm doing the .lyr file ev_bfSlopePer right now, which I believe is the Bankful Slope Percent (bfSlope_Percent). Anyway, when I bring in the layer file manually it is blue to red instead for green to red. So, and when I converted it, it comes in blue to red in qgis as well. See attached screen shot. Any idea why this is? Or is this lyr file not for the bfSlope_Percent? Thanks for the help
![ev_bfSlopePer](https://user-images.githubusercontent.com/39837888/131742791-46441868-b9b4-4d27-a8af-d4c40cd5fe53.png)

**Comment by Cashe93** [comment]
Hey @CHafen, 

I apologize for the delayed response on this! It looks like the business logic is pulling the 'raster_slope' symbology and not the 'ev_bfSlopePer' symbology. 
```
<Node xpathlabel="Name" xpath="Slope[@id='BFSLOPE']" type="raster" **symbology="raster_slope"** transparency="40" />
```

**Comment by joewheaton** [comment]
I'm not sure which one to go with without a screen shot of both. I would prefer something like we use in GCD, which is probably that raster_slope

**Comment by CHafen** [comment]
Hey @joewheaton here are the screen shots. The first one is using the symbology "raster_slope." This is the one that the Buisness Logic uses
![ev_bf_SlopePer_buisnesslogic](https://user-images.githubusercontent.com/39837888/132107671-021d8a36-483b-4476-94e1-128b75375a25.png)
The second one is the symbology  "ev_bfSLopePer"
![ev_bf_SlopePer_sympologymanual](https://user-images.githubusercontent.com/39837888/132107687-28a6abfd-22c8-4177-a113-7b4ff8ca7dec.png)

**Comment by CHafen** [comment]
@joewheaton I'm getting really close with this. But I have run into a few issues. First, the symbology for Tier 3 In Channel Sub Geomorphic Units does not include a category of "Riffle." The areas don't have a color in the below image are categorized as "Riffle" in the attribute table, but "Riffle" does not have an assigned color.
![Tier3GU_image1](https://user-images.githubusercontent.com/39837888/134417589-3be442b7-ecfc-459a-82f3-bde52765b72d.png)
Also, the areas categorized as "Other" in the symbology are blank in the attribute table. So, when the lyr file is converted to a qml that color doesn't transfer over. This means right now in Q both the areas categorized as "Riffle" and the areas with no assigned subGU are assigned the "all other values" default color. 
![Tier3GU_image2](https://user-images.githubusercontent.com/39837888/134418502-26872406-65a9-4e2b-9997-4d3307e8dcdf.png)
So, looks like we need to update the .lyr file to include riffle, right? Is there a specific color that should be? Once that is fixed I can remake the .qml file and then I think I can just manually change it so the "all other values" is changed to match the "other" category from the .lyr file.

**Comment by joewheaton** [comment]
Hi @CHafen we do have riffle symbology for Tier 3 GU that is orange. It is in the https://github.com/Riverscapes/pyGUT/blob/master/GUTSymbology/LYR/out_Tier3_GU.lyr 

They should be orange. Here they are working in ArcRAVE:
![image](https://user-images.githubusercontent.com/9723905/134431566-5ad058c6-4c45-4551-beb1-df33b1193499.png)

You are helpfully pointing out that the sub GUs look like garbage and doesn't include riffle:

![image](https://user-images.githubusercontent.com/9723905/134431825-bddf3865-6d0a-4a85-a567-3d223f9484c7.png)

Please include the riffle and completely re-do these to be more consistent with the other Tier 3 and Tier 2 colors we've used.

**Comment by joewheaton** [comment]
> Hey @joewheaton here are the screen shots. The first one is using the symbology "raster_slope." This is the one that the Buisness Logic uses

Lets change these slope to be consistent with what GCD does:
Degrees:
![image](https://user-images.githubusercontent.com/9723905/134432529-95b7f274-6322-4695-9d9f-b20295542b26.png)
Percent can use similar colors but maybe:
0 to 0.5%
0.5 to 1%
1% to 2%
2% to 5%
5% to 10%
10% to 15%
15% to 30%
30% to 50%
> 50%

In other words, lets make them categorical. Thanks!

**Comment by CHafen** [comment]
Thanks for the feedback @joewheaton. I will work on updating the Tier 3 sub GU symbology.
Do you want me to just change the bfSlope_Percent raster to categorical or should I change all 5 slope raster files in GUT ( In-Channel DEM Slope Raster, Bed Slope SD Raster, bfSlope_Percent, bfSlope_Percent_Smooth and Smoothed Bankfull Surface Slope Raster) to categorical ?

**Comment by joewheaton** [comment]
@CHafen go ahead and change all 5 slope raster files please. That change will need to be for all 3 I'm afraid (i.e. QRAVE, ArcRAVE and WebRAVE). But lets keep chipping away. Thanks. @nick4rivers FYI...

**Comment by CHafen** [comment]
Ok, sounds good @joewheaton I was having trouble with converting the symbology for those files anyway and I think it will convert to a qml better if it's categorical.

**Comment by CHafen** [comment]
@joewheaton here is what I came up with for the new Tier3_SubGU symbology. Let me know what you think.
![Tier3GU_newsymbology1](https://user-images.githubusercontent.com/39837888/134580839-d8f7e244-f720-44ff-8cd4-fb72d8fcad09.png)

**Comment by CHafen** [comment]
@joewheaton, I've been working on the categorical symbology for the slope rasters for GUT. Images below of what the bfSlope_Percent and In-Channel DEM Slope Raster look like with the new categorical symbology I've create.
The Bed Slope Standard Deviation Raster has a corresponding Shapefile that is categorical already (High, Moderate, Low). Do you still want this raster to be categorical too? If so, what categories should I use for that?
![bfSlopePercent](https://user-images.githubusercontent.com/39837888/135530793-cef3c237-e0c1-4a22-a280-46f7f8307612.png)
![In_ChannelDEMSlopeRaster](https://user-images.githubusercontent.com/39837888/135530844-d08c86f7-8616-4932-95fc-be2658b4a70a.png)

**Comment by CHafen** [comment]
I'm having some issues with converting the raster stretched symbology. When I convert them to a .qml it always brings it in with different parameters than ArcMap making it so they don't look the same. See figure below. I'm not sure why the .qml seems to be changing the parameters or how to fix it.  I think the only exception to this is the DEM which comes in just fine, but the DEM symbology was already in the shared symbology folder, and is not a qml I created.
![RasterStretchedSymbology](https://user-images.githubusercontent.com/39837888/136103472-d4801900-6287-4266-a0e1-6d4c06ad5343.png)
.
