### ISSUE TITLE
Add log files to business logic

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/RiverscapesXML#235]
Add the log file for each model to the top of the business logic (similar to how we show the database and report for BRAT)

* [ ] RSC
* [ ] VBET
* [ ] BRAT
* [ ] TauDEM
* [ ] ChannelArea
* [ ] Confinement
* [ ] GNAT
* [ ] RVD

**Comment by MattReimer** [comment]
Moving this to RiverscapesXML since that's where it's supposed to go.

**Comment by philipbaileynar** [comment]
@MattReimer I keep forgetting why this is so hard? I know that the tool software is using the log file during execution and we don't want anything to jeopardize execution. But why can't the top level routine of each software simply instantiate the log singleton (that has already be configured with a file path during the main routine) and then write the log path to the project file. It doesn't need to open, use or disrupt the log file in anyway. Its a super safe one line of code that then makes the log file visible in RAVE.

Failing that, how about if RAVE just looks for *.log in the root of the project and includes the first (or all) log files found in the root. I like this less because its risky (legacy projects might have unrelated junk log files in the root from arc geoprocessing or whatever).

**Comment by MattReimer** [comment]
This isn't hard but it does involve kind of two phases. This ticket is talking about the XML and XSD schema changes needed to implement this. We'll need to:

1. Extend the `<Realization>` definition to [include a standardized log file node directly after the realization metadata](https://github.com/Riverscapes/RiverscapesXML/pull/237/files#diff-e197150061f790b1e33e7cd38f4c0dda04d51c15cd970685ffed48e1b0279f89R35)

In the `project.rs.xml` file this would look something like:

```xml
<Realizations>
    <RSContext dateCreated="2019-09-12T16:42:24.619206" guid="f8c8efcc-d5b6-11e9-be3c-acde48001122" id="RSContext1" productVersion="4.0.0">
    <Name>Riverscapes Context for HUC 17010216</Name>
    <LogFile>
        <Name>RSContext Log file</Name>
        <Path>RSContext.log</Path>
    </LogFile>
```

**_Note how this takes the same form as any other simple file type._**

2. Then, if we can agree on this we need to update the  **Business logic** to put the log file where we want it. This will need to be done for all tools with log files (they don't all have them of course)

something like: 

```xml
<Node xpathlabel="Name" xpath="LogFile" type="file" />
```

-----------------------------------------------------------

Then we'll need a separate `riverscapes-tools` ticket to update all our tools to write this node in the appropriate place in the XML files.

```
<LogFile>
    <Name>RSContext Log file</Name>
    <Path>RSContext.log</Path>
</LogFile>
```

This will become a standard though (even though it should be backwards compatible) so I think it's worth pausing for just a second before merging the change to ask ourselves if this is really the best way to do this.

**Comment by joewheaton** [comment]
@MattReimer I like the suggested order of attack here. As to your question as where we want it in the business logic, my suggestion is that this comes immediately after wherever the report is. For example in HAND:
https://github.com/Riverscapes/RiverscapesXML/blob/e0b4805fd7f9d659b61dd110c3a60c10013f7529/RaveBusinessLogic/HAND.xml#L6-L13

The report is on L12, so maybe we add a L13:
`<Node xpathlabel="Name" xpath="LogFile" type="file" />`

Just a few silly questions @MattReimer for how the user experiences this. 

1. How do you handle the event of "open" for things of "type" `file` ?  I'm guessing most people don't have a file association already for *.log files? Whereas if this was RSContext.log.txt, it would at least open in the users default text editor? Thoughts? 
2. Also, how would this be dealt with in the web browser? I imagine a text file could at least be displayed right there in browser and not require any special download (or could be linked to another tab). I am wondering if this warrants adding a new type that is specifically `"txtfile"`?

**Comment by joewheaton** [comment]
@philipbaileynar of all our model types, which don't have log files? Is this only the Cybercastor models? I edited the list for business logic at start of ticket to reflect this.

**Comment by MattReimer** [comment]
All tools "CAN" have log files but I don't think any of the legacy pyBRAT/RVD etc do. The CHaMP ones might but it's not consistent and certainly we don't want to go back and edit 1000+ legacy project XMLs just to add them.

All the `riverscapes-tools` tools standardize how log files are written so they are somewhat predictable. I'm kind of aiming this strategy at them and then others can choose to follow

**Comment by philipbaileynar** [comment]
All the "new" tools that are intended for cybercaster and that you listed above have log files. Some are better than others. RSC and BRAT and extremely verbose.

Let's ignore log files for legacy projects (pyXXX and CHaMP) unless they already exist. We just need to ensure that whatever we implement in RAVE(s) works when a log file is absent.

**Comment by MattReimer** [comment]
@philipbaileynar on the suggestion above the log file nodes need to be explicitly added to each project business logic so legacy projects won't even know about it

**Comment by MattReimer** [comment]
Also @philipbaileynar for the record (and before I forget again) I finally remembered what  I said was hard about this stuff

There was some discussion about writing a summary of the log files to the report. 

That is a bit ouroborian so if we go there we need to play some gymnastics

**Comment by joewheaton** [comment]
> Also @philipbaileynar for the record (and before I forget again) I finally remembered what I said was hard about this stuff
> 
> There was some discussion about writing a summary of the log files to the report.
> 
> That is a bit ouroborian so if we go there we need to play some gymnastics

Understood... Lets punt on that for now.
