### ISSUE TITLE
ChannelArea BL and symbology Q

### ISSUE THREAD

**Issue by lauren-herbine** [Riverscapes/RiverscapesXML#242]
Hi @MattReimer-
I am trying to do [QC on a new ChannelArea](https://github.com/Riverscapes/RiverscapesData/issues/38) project; when I open it in Q, however, it opens without any business logic or curation. I checked to make sure my BL was all good on github, and it looks like it is ([here](https://github.com/Riverscapes/RiverscapesXML/blob/master/RaveBusinessLogic/ChannelArea.xml)). I can't find symbology (maybe I didn't do a pull request correctly?), but I can see all of the commits I did in #166. I have a feeling this is yet *another* simple fix, but for some reason I can't figure out why the project isn't grabbing the BL and symbology from github! Anything jump out at you? Thanks!

**Comment by MattReimer** [comment]
Hmmm. Did these go away? I'll take a look

**Comment by MattReimer** [comment]
Ok. first off I was able to get things working (I think. Correct me if I'm wrong)

<img width="889" alt="Screenshot 2021-09-03 143824" src="https://user-images.githubusercontent.com/1063391/132067704-6f8629a3-a216-4070-8e15-9e0b0a2aed50.png">

Doesn't mean you don't have a legitimate issue but it is somewhat reassuring. 

Things to check

1. Make sure you haven't got an old business logic xml file next to the project xml. That can sometimes cause weird things, especially if it's old. 
2. I found all the channel area symbology files in the Shared folder. Did you look there?

Let me know if any of this helps. There's a new version of QRave (0.6.0) submitted and pending approval so it's possible that will make things better too.

**Comment by lauren-herbine** [comment]
Yes, that looks like it is supposed to! Especially if it opened with the one Project View ("Channel Area") as the default. 

1. I am 99% sure I don't have an old bl xml file next to the project xml. This is a new project I just downloaded and unzipped from the warehouse:
![image](https://user-images.githubusercontent.com/73319684/132068177-72ed1934-5639-4909-aca6-37f2bd755a4a.png)


2. Ah, yes, I found them! However, now I am even more confused as to why this isn't working... 

For context, it comes in looking like this: 
![image](https://user-images.githubusercontent.com/73319684/132068293-2f455acb-cf1a-4127-b338-2d6bd947f8da.png)

**Comment by MattReimer** [comment]
Hmmm. That's really weird. Can you verify the version number of qrave for me?

I might suggest that you try uninstalling and reinstalling. 

Failing that let me know and we can try troubleshooting it together if you have a minute

**Comment by lauren-herbine** [comment]
Woo! Ok, so I have 0.5.1 and I see that there is a new 0.6.0 release from a couple of hours ago. I did an update, an un-install and re-install, and re-loaded everything. I am not sure what in there made it work, but the project is now pulling the correct symbology and business logic!

**Comment by lauren-herbine** [comment]
Thanks @MattReimer !

**Comment by MattReimer** [comment]
Whoa. did you get 0.6.0?!? I show that it's not available yet. let me know if you did. I'm guessing you got 0.5.2

**Comment by lauren-herbine** [comment]
No I did not! I can see that 0.6.0 is there, but I was only able to update to 0.5.2

**Comment by MattReimer** [comment]
Well, anyway you're unblocked and 0.6.0 should be happening soon. I'll send out a wider message when it's available to everyone.
