### ISSUE TITLE
TauDEM symbology in ArcRAVE

### ISSUE THREAD

**Issue by nick4rivers** [Riverscapes/RiverscapesXML#256]
## The Problem
I am for some reason not getting much of the symbology for a TaDEM project (18030002) in ArcRAVE. i.e., raster layers are only showing grey scale symbology and the custom business logic is not showing.

**_NOTE_** - I run ArcMAP 10.7.1 on a parallels virtual machine on my mac - which could explain the problem.

Please see this issue in the RiverscapesDATA repo for a more complete description and video showing the problem: [https://github.com/Riverscapes/RiverscapesData/issues/42#issuecomment-916502850](https://github.com/Riverscapes/RiverscapesData/issues/42#issuecomment-916502850)

## Reproduction steps

1. Upgraded my ArcRAVE toolbar to the latest version.
2. Updated my resources.
3. shut down ArcMap and reopened and still no symbology.

![Screen Shot 2021-09-10 at 9 43 14 AM](https://user-images.githubusercontent.com/34071692/132890784-3380ecad-4324-412f-adf9-f82350880b6d.png)

everything worked fine in QRAVE.

## Anything else?
_This could easily be user error - but maybe something to do with my virtual machine._

**Update 11/1/2021**
Some of the symbology fell through with BL updates and the necessary changes were sitting on an old branch that I never initiated a pull request on... oops. A few others were not in the Shared folder. Overall, I just had to track down the lyr files for these. They should all be in the right place and working now.

Outputs:
- [x] D∞ Slope Analysis (percent)
- [x] Pit-filled DEM
- [x] D∞ Flow Directions (bearing)
- [x] D∞ Contributing Area
- [x] TWI
- [x] HAND
- [x] D8 Slope Analysis

Inputs
- [x] Channel Area
- [ ] #344
- [x] DEM
- [x] DEM Hillshade

Intermediates
- [x] Rasterized Channel

**Comment by shelbysawyer** [comment]
> notice here how the pitfill layer uses "dem" for symbology. Not sure that's intended.
> https://github.com/Riverscapes/RiverscapesXML/blob/master/RaveBusinessLogic/TauDEM.xml#L29
> 
> @nick4rivers can you coordinate with @shelbysawyer and maybe close this issue if it's already covered by something she's working on?

@MattReimer yes-- "dem" is the intended symbology key for the pit-filled dem

@nick4rivers Let's leave this open for now and I'll get you an update on this in a few hours. I haven't worked on ArcRAVE for TauDEM for a while and need a little bit of time to dive back in and get things working again with the changes we've made over the past month. Does that work for you?

**Comment by nick4rivers** [comment]
@shelbysawyer - no hurry on my end. Just thought I'd bring it up and make people aware of this.

@joewheaton and @philipbaileynar - seems like maybe this QC effort is a bit premature given that we haven't finished sketching out the business logic and we don't really have a way to check on WebRAVE?

**Comment by shelbysawyer** [comment]
> @shelbysawyer - no hurry on my end. Just thought I'd bring it up and make people aware of this. I tested the ArcMap stuff but won't actually be using it.
> 
> @joewheaton and @philipbaileynar - seems like maybe this QC effort is a bit premature given that we haven't finished sketching out the business logic and we don't really have a way to check on WebRAVE?

Nic, the business logic is done and the curation for QRAVE TauDEM is running fine. ArcRAVE TauDEM will get some TLC from me today and likely also on Monday.

**Comment by philipbaileynar** [comment]
Once the business logic is released, @nick4rivers remember to use the new shiny "[update resources](http://rave.riverscapes.xyz/Software_Help/arcrave_help.html#getting-the-latest-arcrave-resources)" feature to pull down the latest business logic.

**Comment by MattReimer** [comment]
@nick4rivers we should be ready to close this issue. Can you just check quickly that it's working for you?
