### ISSUE TITLE
Updated VBET business Logic to reflect layer name changes

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/RiverscapesXML#263]
We have changed the VBET layer names to make them less dependent on the threshold levels. Please update the VBET business logic. Note the linked ticket specifies the name and has an example project.

https://github.com/Riverscapes/riverscapes-tools/issues/427#event-5314753902

FYI @joewheaton and @KellyMWhitehead

**Comment by joewheaton** [comment]
@philipbaileynar and I already fixed this in: https://github.com/Riverscapes/RiverscapesXML/pull/266
