### ISSUE TITLE
New public Riverscapes Warehouse Program

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/RiverscapesXML#27]
We are inviting people to pay for riverscapes projects that are then made public and available to anyone who wants them. We need a new program to host these projects.

* Riverscapes Context
    * HUC8
    * HUC10
    * HUC12
* VBET
    * HUC8
    * HUC10
    * HUC12
* BRAT
    * HUC8
    * HUC10
    * HUC12

**Comment by MattReimer** [comment]
This is done
