### ISSUE TITLE
Potential Bug in `BRAT.xml` Business logic or XSD error checking?

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RiverscapesXML#270]
**Describe the bug**
![image](https://user-images.githubusercontent.com/9723905/134536516-e5a608d3-008a-4e76-9e09-13220bc1eb7d.png)

Report does actually work and is showing up correctly in QRAVE though.
![image](https://user-images.githubusercontent.com/9723905/134536896-420ba10b-8407-49f5-a556-5976b2c25b79.png)

So, maybe this is just an XSD validation thing? I vaguely recall @MattReimer mentioning some problem about this?

**Riverscape Project (please complete the following information if relevant):**
 - Type: 'sqlBRAT`
 - Warehouse Link: [e.g. [BRAT for 18010202](https://data.riverscapes.xyz/#/UKUSFWS/7385205e-95e7-45cf-bbc5-33036f0f75c8)]
 - Layers Impacted Report

Noticed when reviewing #269

**Comment by MattReimer** [comment]
hey @joewheaton. I'm not 100% sure but this is likely an old cached copy of the XSD that's causing problems

1. shut down VSCode completely
2. Go to your used folder (usually somethin like `c:\Users\MYNAME\`) 
3. Look for a `.lemminx` folder. Inside that you should find a `cache` folder
4. Delete the `cache` folder completely.
5. Open up VSCode

**Comment by joewheaton** [comment]
Well voilà! As instructed goes away:
![image](https://user-images.githubusercontent.com/9723905/134545905-0c50fd37-20b0-4093-ad0e-9262d1d9ca39.png)

Thanks @MattReimer. I made https://github.com/Riverscapes/riverscapes-website/commit/818a9de777a7a680517887b3ed05a49bf2e5e88f to update documentation here: https://riverscapes.xyz/Tools/Technical_Reference/videos.html#xml-validation-in-visual-studio-code
