### ISSUE TITLE
Decide what to do about exposing databases with BL

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RiverscapesXML#271]
I noticed this minor problem in #270 that is a legacy from when BRAT was truly just a sqlite DB and shapefiles. We have this line in our business logic which is causing RAVE to break, but is not displaying anything because the `xpath="SQLiteDB"` no longer exists in the project file.

https://github.com/Riverscapes/RiverscapesXML/blob/691108896b92158cea56ae9f67cfbdb3112f9922/RaveBusinessLogic/BRAT.xml#L10

What does exist in `project.rs.xml` is three sqLite DB in the form of geopackages:
``` XML
<Path>inputs/inputs.gpkg</Path>
<Path>intermediates/intermediates.gpkg</Path>
<Path>outputs/brat.gpkg</Path>

```
So @philipbaileynar way back when I think the logic was that we expose the DB, because for users that re DB nerds like yourself, they can then have a play. Also, I strongly suspect that a lot of sqLite DB users will not realize a Geopackage is a special sqLite DB. However, when you open it up it is a little intimidating, but when you get down to views (at least in `brat.gpk`) there is some familiar useful stuff:

![image](https://user-images.githubusercontent.com/9723905/134538059-cf2e244f-6fb2-4b37-8f72-abcf25aad59f.png)

So @philipbaileynar questions:
1. Do we expose all three of these in BL or just `brat.gpk`?
2. Do we wait to expose until we have better curated some views?
3. Do we just fix empty reference?
4. @MattReimer do we need to do anything different for type 'file' on these geopackages specifically?

**Comment by philipbaileynar** [comment]
Definitely fix the empty reference to point to the brat.gpkg. I wouldn't elevate the other ones. They are on disk if people want them.

Views are easy peasy to create. And if the views has less than say 50 records then I say promote it to the report.

**Comment by MattReimer** [comment]
@joewheaton this line is leftover like you said. It doesn't cause any harm at all and will be totally ignored when loading newer projects that don't have a sqlitedb. We left it in here as a transition while there were both types of projects in the system. It's kind of a neat but unintended feature of BL xmls that they can support a few similar versions of project xmls in a limited way.

the xml node this line is looking for is:

```
< SQLiteDB guid="eaaea4f9-dbf9-446c-841a-57e38eb871c7" id="SOMEDBID">
  <Name>I Am a legacy file</Name>
  <Path>whatevername.sqlite</Path>
</SQLiteDB >
```

**Comment by philipbaileynar** [comment]
As a DB nerd, I like quick access to the geopackage SQLite database in the software of my choosing (i.e. outside GIS) to run some queries. I say we keep the `SQLiteDB` node and point the path to the brat.gpkg file.

**Comment by MattReimer** [comment]
> As a DB nerd, I like quick access to the geopackage SQLite database in the software of my choosing (i.e. outside GIS) to run some queries. I say we keep the SQLiteDB node and point the path to the brat.gpkg file.

I don't think this will work as intended @philipbaileynar since the default action on a lot of systems for a gpkg file will be to load QGIS. For this to work people would need to have sqlite DB software installed AND have gpkg keyed to that software as a default mime type. This is potentially confusing for anyone that isn't you or I and that's definitely not where we want the confusion to sit.

My (not very strong) preference is just to remove the node. It's semantically not quite right.

**Comment by philipbaileynar** [comment]
OK, I don't feel strongly. Agreed. Remove node.

**Comment by joewheaton** [comment]
So @MattReimer file associations are always a shit-show, but I have the most recent version of QGIS installed and a `*.gpkg` has no file association. Even the old exposure of this only worked based on the file association being there and for those with some SQLite viewer it worked. We have other things potentially exposed (e.g. PDFs and images) that only work according to the user's file associations. I am kind of partial to @philipbaileynar first instinct:

> As a DB nerd, I like quick access to the geopackage SQLite database in the software of my choosing (i.e. outside GIS) to run some queries. I say we keep the SQLiteDB node and point the path to the brat.gpkg file

However, I could see demoting these way down to the bottom (same with log files) of most business logic (just above views). 
.

**Comment by joewheaton** [comment]
Excellent points @MattReimer. I am going to give this a try and see how we like or don't like it.

**Comment by joewheaton** [comment]
BTW @MattReimer if we take your suggestion of 
> keep this node right next to where the other layers from this geopackage are so that people can clearly see it's part of the same file.

, which  I like, the syntax needs to be:
``` XML
<Node xpathlabel="Name" xpath="Geopackage" type="file" /> 
```
because the `Inputs\`, `Intermediates\` and `Outputs\` is already specified in the parent node xpaths on most these BLs.

**Comment by joewheaton** [comment]
@philipbaileynar, lets see if this annoys us or we like it and if we like it I will have @Cashe93 or someone do it for all our Production grade tools.

**Comment by philipbaileynar** [comment]
Talked to @MattReimer and he made me realize that referencing all our files multiple times creates a lot of noise and maintenance. It also bloats the business logic tree, which if we are not careful will end up resembling the folder/file path tree, which is exactly what we set out to avoid.

I now prefer not listing Geopackages. Down the road we can contemplate ways of doing right click on data layers in the project tree to achieve this same goal.
