### ISSUE TITLE
Expose Channel Area and TauDEM Projects to have log files, reports and geopackages exposed

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RiverscapesXML#276]
When I did quick QC for https://github.com/Riverscapes/RiverscapesData/issues/89 I noticed some inconsistencies and lack of exposing our logs and reports. Copying what we just did for BRAT (#271) for geopackages too.

**Comment by MattReimer** [comment]
This is merged so I'm closing it. I manually checked the ChannelArea and Taudem projects and they have these items.
