### ISSUE TITLE
WebRAVE VBET Curation

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/RiverscapesXML#283]
[VBET Project to test
](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/73d8f3b4-88e0-49c2-b17b-eb0361699f04)

**Updated 10/25/2021**

- [x] Author symbology files for WebRAVE
- [x] Provide link in commit to webRAVE of project it can be tested on
- [x] Make pull request for just WebRAVE changes. Choose appropriate reviewer(s)
- [x] After pull request(s) merged, test in WebRAVE and review layers:
- [x] Likelihood of being Valley Bottom
- [x] Estimated Active Channel
- [x] Estimated Active Floodplain
- [x] Estimated Inactive Floodplain
- [x] Valley Bottom Extent (Hollow)
- [x] Valley Bottom Extent (Filled)
- [x] Slope
- [x] #298
- [x] TWI
- [x] Rasterized Channel
- [x] Normalized Slope
- [x] Normalized HAND
- [x] Normalized TWI
- [x] Normalized Topographic Evidence
- [x] Catchment Wing Stream Order https://github.com/Riverscapes/rs-web-monorepo/issues/167
- [x] Channel Area Polygons
- [x] #285
- [x] Hillshade

**Comment by shelbysawyer** [comment]
After merged, review layers:
- [ ] Likelihood of being Valley Bottom
- [ ] Estimated Active Channel
- [ ] Estimated Active Floodplain
- [ ] Estimated Inactive Floodplain
- [ ] Valley Bottom Extent (Hollow)
- [ ] Valley Bottom Extent (Filled)
- [ ] Slope
- [ ] HAND
- [ ] TWI
- [ ] Normalized Slope
- [ ] Normalized HAND
- [ ] Normalized TWI
- [ ] Normalized Topographic Evidence
- [ ] Catchment Wing Stream Order
- [ ] Channel Area Polygons
- [ ] DEM
- [ ] Hillshade

**Comment by shelbysawyer** [comment]
@MattReimer I tested the layers after the merge in the VBET project linked above. Some layers are working (checked off on list) and some aren't (unchecked). For some reason, a lot of the rasters aren't working (coming in fine, but without color). I did the steps you listed [here](https://github.com/Riverscapes/RiverscapesXML/blob/master/docs/Symbology/webRAVERasters.md#palletted-unique-colors), which I also followed for the TauDEM rasters. All of them are singleband pseudocolor. TauDEM layers are showing up correctly, but the VBET layers are not. Any idea what could be happening?

**Comment by MattReimer** [comment]
@shelbysawyer webrave rasters are tricky because the tiles have to be rebuilt entirely every time you make a change to the symbology. 

Luckily I've queued a rebuild earlier today so you should start seeing the updated rasters getting populated.

Next week I expect to have some of the more functional problems of webRave solved and then I'll be turning my attention to individual layers and things like color ramps and vector symbology. At that point I'll be in touch if there's something you need to change but overall I think just getting the color ramps I to the system is enough for now. The rest is on me until further notice.

**Comment by MattReimer** [comment]
FYI: Here's a taudem that seems to be symbolized correctly:
https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/6146ca4d-5068-488c-b4ab-e6f7892ecbad

Here's a VBET

https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/95a6498e-d9ff-4f59-a544-dd1b573a4576

I seem to have broken vectors in the process though.... DOH! Oh well. That's monday.

**Comment by shelbysawyer** [comment]
@lauren-herbine Nope, just having it in Shared will do the trick :) Thanks!

**Comment by joewheaton** [comment]
Thanks @shelbysawyer. Answers below
> 
> * [ ]  0:12 The Valley Bottom Extent (hollow) outline needs to be dashed instead of solid
> * [ ]  0:25 Estimated Active Channel needs an outline - @joewheaton Is this important?

Yes, please fix. It is hard to see with out that darker outline.

> * [ ]  0:42 There are some shading differences that cause some layers (ex. active valley bottom) to appear slightly different in color. @joewheaton Is this important?

I can live with these differences for now. Someday maybe we will figure out how to get them close, but lets move on ;).

Great job.

**Comment by shelbysawyer** [comment]
After one final look-through today, I'm closing this issue. No major issues remain. Minor issues (ex. tone of color for some fills) will be addressed later.
