### ISSUE TITLE
HAND Raster symbology for WebRAVE does not match QGIS

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/RiverscapesXML#288]
The color ramp does not match the current one for QRAVE.

https://github.com/Riverscapes/RiverscapesXML/blame/master/Symbology/web/Shared/hand.txt

**Comment by MattReimer** [comment]
The fix for the DISCRETE rasters seems to have solved this.

Tiles are rebuilding now but here's an example of HAND that's already rebuilt
https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/8f4e9bac-ea2b-4034-8deb-199384daf911

**Comment by joewheaton** [comment]
Looks good to me now! Spot checks:
HAND in a [VBET](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/a221138b-668b-4d65-b15d-f4bf1679374b)
![image](https://user-images.githubusercontent.com/9723905/137573196-317f39f4-9ced-4b2f-8550-3fa314ad3d55.png)

HAND in a [TauDEM](https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/ac92e105-8d66-43fe-bc7e-2b3b24537f12)
![image](https://user-images.githubusercontent.com/9723905/137573235-4bd45b97-7a56-46d4-b08c-6f9c6500dedb.png)
