### ISSUE TITLE
HAND class for values >250 m not being represented

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/RiverscapesXML#298]
referring to 
#283

I'm pretty sure this is fixed thanks to this fix:
- https://github.com/Riverscapes/rs-web-monorepo/issues/151

But I'll need to rebuild the raster tiles and see if that's true

**Comment by MattReimer** [comment]
And finally. Just for completeness I'll mention that the tile rebuild is done. 

the following raster symbologies are affected so you might notice some changes with them too:
`detrendDEM,fair_market,hand,dinfflowdir_slp`
