### ISSUE TITLE
Potential Bug in VBET for ArcRAVE

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RiverscapesXML#299]
**Describe the bug**
I have not looked at VBET for a long time in ArcRAVE. It is not  working correctly for symbology.  I suspect @shelbysawyer we either never got back around to this (now is the time) or we broke it in other updates that @MattReimer or I made to BL. Either way, can you please fix it to be consistent with QRAVE? 

**Updated 10/31/2021 by @shelbysawyer:**
Outputs
- [x] Valley Bottom Extent (Hollow)
- [x] Valley Bottom Extent (Filled)
- [x] Estimated Active Channel
- [x] Estimated Active Floodplain
- [x] Estimated Inactive Floodplain
- [x] Likelihood of being Valley Bottom

Intermediates
- [x] Slope
- [x] HAND
- [x] TWI
- [x] Rasterized Channel Area
- [x] Normalized Slope
- [x] Normalized HAND
- [x] Normalized TWI
- [x] Combined Topo Evidence
- [x] Catchment Wing Stream Order

Inputs
- [x] Channel Area Polygons
- [x] Digital Elevation Model

Hillshade
- [x] Hillshade

Views
- [x] Default (VBET Extent Hollow, Likelihood Raster, Hillshade)
- [x] Geomorphic Units (Active channel, active floodplain, inactive floodplain)
- [x] Normalized Evidence (norm topo, hillshade)
- [x] VBET Inputs (Channel Area Polygons, DEM, Hillshade)

**Comment by shelbysawyer** [comment]
Hey @CHafen, @Cashe93, @Tanmanfalcon or any other ArcMap aficionados.. I'm having an issue with getting some of the symbology that I have in QRAVE to behave the same way in ArcRAVE, summarized in this video:

[![Video Link](http://img.youtube.com/vi/6_jgGTjeQU4/0.jpg)](http://www.youtube.com/watch?v=6_jgGTjeQU4"")

Any help is greatly appreciated!

**Comment by shelbysawyer** [comment]
Hey @MattReimer and/or @philipbaileynar I'm still seeing a drawing issue in VBET with RAVE 3.1 for the Catchment Wing Stream Order layer in [this](https://data.riverscapes.xyz/#/BLM/871f96ef-ec4f-4eaf-91bb-7f702e0cca36) project, shown in the video below:

[![Video Link](http://img.youtube.com/vi/xBeH9SmrJ3E/0.jpg)](http://www.youtube.com/watch?v=xBeH9SmrJ3E"")

**Comment by MattReimer** [comment]
hmm. I'm going to defer to @philipbaileynar or others on this one. I'm not really an Arc user so I don't know what the best conventions or fixes are for this stuff
