### ISSUE TITLE
Test sqlBRAT in WebRAVE

### ISSUE THREAD

**Issue by Cashe93** [Riverscapes/RiverscapesXML#300]
**BRAT in WebRAVE**
*Project Type*: BRAT 
*Layer(s)*: All (Vectors and Raster) 
*Project Tested*: https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/f20d6d07-6d2c-4188-bbf4-5d4405ddad4b

1. Compile a list of layers that need edited symbologies 
- [x] Risk (complete)
- [x] Zero or Null DA (complete)
- [ ]  Flow Direction
- [x] River Polygons (complete) 

2. Compile a list of potential issues that need to be addressed in Business Logic or Project.xml
- [x] Riparian rasters not being symbolized (complete)
- [x] #307

**Comment by Cashe93** [comment]
**Existing Dam Capacity**

![image](https://user-images.githubusercontent.com/49880208/138156999-73a3fb11-8bec-4c10-bc3c-5b9bff36398d.png)

**Existing Dam Size**

![image](https://user-images.githubusercontent.com/49880208/138157197-bbf488bd-ee60-4bfb-ac65-e67382bb06d5.png)

**Historic Dam Capacity**

![image](https://user-images.githubusercontent.com/49880208/138157525-cb5e8770-feb1-4b53-9649-6b34913f5e5b.png)

**Historic Dam Size**

![image](https://user-images.githubusercontent.com/49880208/138157641-dcf4d7de-4343-4145-8f56-4880c3f0908e.png)

**Unsuitable or Limited Opportunities**

![image](https://user-images.githubusercontent.com/49880208/138157846-c086a774-146e-4817-b583-7a328d1a8e0d.png)

**Risk of Undesirable Dams**

**Comment by Cashe93** [comment]
**Perennial**

![image](https://user-images.githubusercontent.com/49880208/138160901-8d612a59-3209-4496-806d-1e3cd620ebb8.png)

**Zero or Null DA**

This symbology needed to be updated. Fixed on 10/20/21 and will be part of the next pull request. 

**Slope**

![image](https://user-images.githubusercontent.com/49880208/138166904-c752951d-379b-433d-8854-6723eb887b59.png)

**Drainage Area**

![image](https://user-images.githubusercontent.com/49880208/138166999-f09f7c46-8bf1-4942-948d-d533ab263763.png)

**High Flow Stream Power**

![image](https://user-images.githubusercontent.com/49880208/138167162-4937b6d1-765f-48a2-8d76-80a799307b06.png)

**Base Flow Stream Power**

![image](https://user-images.githubusercontent.com/49880208/138167234-d9f48e0c-efe0-4a7a-b9cc-ba3694966c7f.png)

**Existing Veg Dam Building Capacity**

![image](https://user-images.githubusercontent.com/49880208/138167340-595d1184-194f-429e-b3da-7f5e414bf2ae.png)

**Historic Veg Dam Building Capacity**

**Comment by joewheaton** [comment]
@Cashe93 this is really great with the screen shots. Can you for other ones include the link to project you are testing on: https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/f20d6d07-6d2c-4188-bbf4-5d4405ddad4b

I found inconsistent display of many of these layers in that project at coarser zoom levels. For example, capacity does not show up at all from zoom extents (9) down to 11
![image](https://user-images.githubusercontent.com/9723905/138193668-0d55664f-43c7-4f4f-bbe5-5199d761bc14.png)
Only shows up at > 11.5  but with lots of gaps initally:
![image](https://user-images.githubusercontent.com/9723905/138193773-2f5b568e-3e58-45c8-aff3-8d60fb20b918.png)

**Comment by MattReimer** [comment]
@Cashe93 don't change the zoom values in the "select data" tab.  What you want to do is "Style across zoom ranges"
<img width="939" alt="Screen Shot 2021-10-21 at 2 10 16 PM" src="https://user-images.githubusercontent.com/1063391/138357315-fb507d94-3c4b-401b-8f35-b564a00d4e29.png">

That will let you have different styles on different ranges.

**Comment by Cashe93** [comment]
@MattReimer, poor choice of words on my end. I haven't been manually changing the zoom values, I've just been leaving defaults which as far as I can tell are the lowest Min and the highest Max. But, even when you style across zoom range and set the Min to 0, it still doesn't move below 11.
