### ISSUE TITLE
Distance to ... Intermediates not displaying

### ISSUE THREAD

**Issue by Cashe93** [Riverscapes/RiverscapesXML#307]
**The following layers are not displaying in WebRAVE but do display in both QRAVE and ArcRAVE**

- Distance to nearest infrastructure
- Distance to Railroad
- Distance to Railroad in Valley Bottom
- Distance to Road
- Distance to Road Crossing
- Distance to Road in Valley Bottom
- Distance to Points of Diversion 
- Distance to Canals/Ditches 

I've looked at xpaths as well as symbology references and everything looks correct. This one has me stumped, at least for the time being. 

Project: https://northarrowresearchlabs.github.io/webrave-staging/#/Anabranch/7dd3c992-c395-4ad2-8d44-802287b08883

Screenshot: 
![image](https://user-images.githubusercontent.com/49880208/138347526-4a4ef6a6-635b-4103-afec-25e8e3196dce.png)

**Comment by MattReimer** [comment]
Found the problem. The first parameter of value "0" is implicit so

```json
          "line-color": [
              "step",
              ["get", "iPC_RailVB"],
              0,
              "hsl(8, 100%, 50%)",
              30,
              "hsl(8, 100%, 50%)",
              30.00001,
              "hsl(36, 100%, 50%)",
              100,
              "hsl(36, 100%, 50%)",
              100.00001,
              "hsl(60, 100%, 50%)",
              300,
              "hsl(60, 100%, 50%)",
              300.00001,
              "hsl(77, 100%, 34%)",
              1000,
              "hsl(77, 100%, 34%)",
              1000.00001,
              "hsl(120, 100%, 19%)",
              1000000,
              "hsl(120, 100%, 19%)"
          ]
```

should actually be

          "line-color": [
              "step",
              ["get", "iPC_RailVB"],
              "hsl(8, 100%, 50%)",
              30,
              "hsl(8, 100%, 50%)",
              30.00001,
              "hsl(36, 100%, 50%)",
              100,
              "hsl(36, 100%, 50%)",
              100.00001,
              "hsl(60, 100%, 50%)",
              300,
              "hsl(60, 100%, 50%)",
              300.00001,
              "hsl(77, 100%, 34%)",
              1000,
              "hsl(77, 100%, 34%)",
              1000.00001,
              "hsl(120, 100%, 19%)",
              1000000,
              "hsl(120, 100%, 19%)"
          ]
```

The first color you give is assumed to be everything below the value that comes next. Let me know if this doesn't make sense
