### ISSUE TITLE
pyBRAT naming

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/RiverscapesXML#31]
Hey @joewheaton,

Right now our new automated BRAT is just called  BRAT or "BRAT Models (Huc8)" in the long name. 

@tyler1218hatch is currently working on getting project files for the legacy BRAT runs. Right now the running name is  "pyBRAT".

Is this confusing? How do we want to see/name the legacy BRAT projects represented in the warehouse? I'm going to need a short machine name and a longer name

Totally up to you guys but I'll throw out a suggestion:

```
name: Legacy BRAT runs
machineName: pyBRAT
```

**Comment by joewheaton** [comment]
Sorry @MattReimer I missed this. 

Instead of 
> ```
> name: pyBRAT 3.x Operational Grade Models
> machineName: pyBRAT
> ```
Lets do for sqlBRAT 
 ```
name: sqlBRAT 4.x Production Grade Models
machineName: sqlBRAT
```

Sorry if I am too late.

**Comment by MattReimer** [comment]
Ok, so I'm not 100% clear on what you meant by that. 

The new BRAT (the one that runs in Cybercastor) is as follows:
 ```
name: BRAT Models 
machineName: BRAT
``` 
I can change the `name` but the `machineName` is locked in because it's already in use.

The older pyBRAT models that have yet to be uploaded to the warehouse (and what this ticket is about) are as follows
 ```
name: Legacy BRAT runs
machineName: pyBRAT
``` 
I can change both `name` and `machineName` for these.

**Comment by joewheaton** [comment]
Got you.... A okay on sqlBRAT and cyber castor.

lets go with for pyBRAT:


 ```
 name: pyBRAT 3.x Models
 machineName: pyBRAT
 ```
