### ISSUE TITLE
WebRAVE w/ RSContext PRISM data symbology

### ISSUE THREAD

**Issue by leallysmith** [Riverscapes/RiverscapesXML#319]
Following screenshots are from RSContext for 17060304
[https://northarrowresearchlabs.github.io/riverscapes-staging//#/BRAT_CRB/9330f8f2-6139-47fb-a0dc-d185476b030c](url)

All PRISM data for project have the same color ramp but the value breaks are assigned differently for each PRISM data in WebRAVE

minimum temperature note value breaks in legend
![image](https://user-images.githubusercontent.com/89225401/139147954-c9ff19e9-e438-4f34-b6e1-0ef34372acbf.png)

mean dewpoint note different value breaks for the same colors in the ramp.
![image](https://user-images.githubusercontent.com/89225401/139148049-265e2dfe-7915-4417-870b-94bdf073157e.png)

**Comment by MattReimer** [comment]
@Cashe93 this one is a pretty easy fix I think

Take a look a this:
https://github.com/Riverscapes/RiverscapesXML/blob/master/Symbology/web/RSContext/temperature.txt#L2

If you change `INTERPOLATION:INTERPOLATED` to `INTERPOLATION:EXACT` then it will use the ramp values literally and not rescale them to the extents of the raster data.

This fix applies everywhere too in cases where the absolute value of the color ramp matters.

I hacked one layer up just to show you. Check out "Minimum temperature" on this project:
<https://northarrowresearchlabs.github.io/webrave-staging/#/BRAT_CRB/9330f8f2-6139-47fb-a0dc-d185476b030c>

<img width="1028" alt="Screen Shot 2021-10-29 at 11 59 55 AM" src="https://user-images.githubusercontent.com/1063391/139488378-9a1a5d7f-dd73-4527-92e0-8189b2d314eb.png">
<img width="787" alt="Screen Shot 2021-10-29 at 12 00 26 PM" src="https://user-images.githubusercontent.com/1063391/139488386-d8791156-c2b4-4551-92f7-3b9f6a190967.png">

**Comment by Cashe93** [comment]
Awesome @MattReimer! I've just submitted a pull request with these changes. #337

**Comment by MattReimer** [comment]
This fix is in. I'm rebuilding the tiles for these layers now. @Cashe93 check back in an hour, refresh your browser and let me know if it looks ok

**Comment by Cashe93** [comment]
Im out for the day,  but @Tanmanfalcon might be able to give it a look. If not, Ill try to get to it this evening.
