### ISSUE TITLE
WebRAVE - Triangle or Arrow SVG as part of Flow Direction Symbology 

### ISSUE THREAD

**Issue by Cashe93** [Riverscapes/RiverscapesXML#322]
**Description**

The Flow Direction network symbology requires arrows, indicating the direction of flow. I have not been able to find a way to do this in MapBox

Here is an example of what we are going for from ArcRAVE

![image](https://user-images.githubusercontent.com/49880208/139155978-15a61148-9229-463d-b9c5-e4a1bee89cb8.png)

**Comment by MattReimer** [comment]
Punting this to 0.3 and re-assigning @Cashe93. I think the UTF8 workaround is our best bet here. No rush on this though

**Comment by Cashe93** [comment]
@MattReimer, would I use a decimal or a hexadecimal reference? Also, where would I enter the reference?

**Comment by MattReimer** [comment]
You can actually just copy and paste the character directly from the UTF-8 website. No need for codes.
https://www.w3schools.com/charsets/ref_utf_geometric.asp

Like so:
<img width="1272" alt="Screen Shot 2021-11-01 at 10 53 23 AM" src="https://user-images.githubusercontent.com/1063391/139717441-a14a0938-d9e2-4385-b329-e8961c972a7e.png">

You can style the colors by copying and pasting the color codes from the lines section and if direction is a field in your data you can use "▶" for one direction and "◀" for the other. 

(huh. github renders them as emojiis. that's weird. Edit this comment if you're curious what it's supposed to look like)

**Comment by Cashe93** [comment]
Thanks, @MattReimer. I think this worked. I've just submitted a pull request.

**Comment by MattReimer** [comment]
I've merged it but I don't see anything in there about which direction the arrow should point. Isn't there a field that tells you which way downstream is?

**Comment by Cashe93** [comment]
The symbology for both Arc and Q are just applied to the entire network as a single symbol, but are somehow (mostly) accurate? However, there is a field for flow direction with 0 and 1. Assuming 1 is downstream and 0 is upstream, I'll update the symbology across all three RAVE platforms.

**Comment by Cashe93** [comment]
@wally-mac here is an image of the flow direction in WebRAVE. The only issue I can see is that in Arc and Q, the triangles rotate to follow the line angle. Since that's not happening here, there are some areas that look a bit funky. However, it generally displays the direction of flow accurately. If this passes, we can close this issue. 

![image](https://user-images.githubusercontent.com/49880208/139748430-696bbb30-915b-4101-974d-ecb915526d82.png)

**Comment by wally-mac** [comment]
@Cashe93 I think this works for the short term fix but down the road we should look for a better solution.￼

**Comment by MattReimer** [comment]
@Cashe93 Mapbox does have a method for rotating the symbol to follow the geometry.

<img width="1058" alt="Screen Shot 2021-11-01 at 5 18 36 PM" src="https://user-images.githubusercontent.com/1063391/139759473-75c829f3-34e7-4188-89c3-0d0a5385f89c.png">

**Comment by Cashe93** [comment]
Nice @MattReimer. I'll make this fix tonight or tomorrow.

**Comment by Cashe93** [comment]
Alright, these changes are in and everything looks good.
