### ISSUE TITLE
Testing RSContext in WebRAVE

### ISSUE THREAD

**Issue by leallysmith** [Riverscapes/RiverscapesXML#327]
RSContext in QRAVE
Project Type: RSContext
Layer(s): All (Vectors and Raster)
project: 05140201 [https://northarrowresearchlabs.github.io/riverscapes-staging//#/Anabranch/21d84bcb-f433-492f-a039-ecbf355268e4](url)

HUC ID: 05140201

# Issues 

**Fixed 10/28/21** 
~~**Perennial Drainage Layer**
3 symbologies in Q but only 1 in Web~~
![image](https://user-images.githubusercontent.com/89225401/139314311-74f52dba-5900-4f63-9e49-03951f816b01.png)
![image](https://user-images.githubusercontent.com/89225401/139314378-8e2850c6-d737-4714-bff4-2c3fc30c95f6.png)

**Fixed 10/28/21** 
 ~~HUCs in Web are filled polygons, Q has outlines~~

**Fixed 10/28/21** 
 ~~**Estimated Bankfull Width**
Line weights for increased width in Q but not in Web~~
![image](https://user-images.githubusercontent.com/89225401/139314835-c356805f-1181-479c-94fa-705c236898d7.png)

**Fixed 10/28/21** ~~**Bankfull Channel** 
has no specified symbology so it defaults to one random color~~

**Fixed 10/28/21** ~~**Rail**
Layer is symbolized differently in q/arc than in web~~

**Fixed 10/29/21**  ~~**Intermittent Drainage layer**
The lines for the intermittent drainage network shift around or appear as you zoom in~~
Zoom level: 8.8 ![image](https://user-images.githubusercontent.com/89225401/139153072-5d47269d-ce41-4258-a1cc-ab91fc9e4d24.png) 
Zoom level: 9.3 ![image](https://user-images.githubusercontent.com/89225401/139153182-56fde355-aeb6-4631-9d90-165826182df5.png)

In another spot
zoom: 9.9 
![image](https://user-images.githubusercontent.com/89225401/139153521-5d73e21b-ce33-4c02-8b96-de1b315f23f8.png)
zoom: 10.6
![image](https://user-images.githubusercontent.com/89225401/139153680-ed3e5d45-9444-44d0-9205-5c3f518b66fa.png)

**Fixed 10/29/21** ~~Similar problem in **Full NHD HR+ layer**, **Estimated Bankfull Channel** sections of lines don't appear at all until more zoomed in~~
Is this issue with lines related to the tiling you mentioned in this comment @MattReimer? https://github.com/Riverscapes/RiverscapesXML/discussions/249#discussioncomment-1533465

**Fixed 10/28/21**  ~~**Canals and ditches layer**
does not appear despite existing in QRave~~
Fixed 10/28/21 ~~**Pipes and ditches layer** 
also not appear though that may be due to missing symbology, legend in WebRave does not show any symbology for this layer~~

See also issue #319 where **prism climate** data symbology is changing project to project.

**Ecoregions Layer** 
Appears blue or red in WebRAVE but green in Q and Arc

**Comment by Tanmanfalcon** [comment]
# Screenshots
all taken at zoom: 8.6 except larger HUC areas and Ecoregions
zoomed in shots at zoom 10.6

##Transportation

**Roads**
![image](https://user-images.githubusercontent.com/89225401/139304684-455dc58e-2a0f-4023-b843-42c71d997cbe.png)
![image](https://user-images.githubusercontent.com/89225401/139310605-60c094aa-8611-4885-afa3-e510fb6b9d1d.png)

**Rail**
![image](https://user-images.githubusercontent.com/89225401/139304781-b830e4ed-6629-46fd-ac20-25255dde5eb9.png)
![image](https://user-images.githubusercontent.com/89225401/139310650-d11edd96-c77c-4591-8110-5821bbb241e3.png)


##Hydrology

**Perennial Drainage Network**
![image](https://user-images.githubusercontent.com/89225401/139305425-95c60e40-1dcc-4815-aaf0-c1ac09e1845a.png)
![image](https://user-images.githubusercontent.com/89225401/139310865-864c60d8-febf-4973-b038-4f08b038acf2.png)

**Intermittent Drainage Network**
![image](https://user-images.githubusercontent.com/89225401/139305663-ccfb68ab-754f-4436-90ba-c620d329da35.png)
![image](https://user-images.githubusercontent.com/89225401/139310896-8b874419-1393-4a2a-9cd1-6e7d95a24246.png)

**Ephemeral Drainage Network**
![image](https://user-images.githubusercontent.com/89225401/139305749-cd0f4dec-0d46-4af1-a211-a76aecedc8b3.png)
no network seen in Q, Web, or Arc 

**Network- Upstream Drainage Area**
![image](https://user-images.githubusercontent.com/89225401/139306019-6bf6ac0e-370a-4312-9643-812a7826ae21.png)
![image](https://user-images.githubusercontent.com/89225401/139310976-25341e39-b10e-4b89-b0ea-de3232a5e0ba.png)

**Full NHD HR+ Drainage Network**
![image](https://user-images.githubusercontent.com/89225401/139306135-b63846de-76db-44d8-b014-c94500bf5ed1.png)
![image](https://user-images.githubusercontent.com/89225401/139311013-b457b77c-6f76-4daf-a6f4-3639362416df.png)

**Drainage Wings**
![image](https://user-images.githubusercontent.com/89225401/139306437-b3f5bd37-ed84-4e9d-ae3f-7af8df1b3836.png)
![image](https://user-images.githubusercontent.com/89225401/139311068-d88ae6ec-fc66-4cbc-bf86-5e96555421ff.png)

**River Polygons (NHD Area)**
![image](https://user-images.githubusercontent.com/89225401/139306516-7aaad8dd-b2e8-4390-af2d-6fb019b86c64.png)
![image](https://user-images.githubusercontent.com/89225401/139311107-c8667241-30cd-4e79-8b72-8e66c93993ff.png)

**Lakes, Ponds, Reservoirs and Water Bodies**
![image](https://user-images.githubusercontent.com/89225401/139306610-82a7eaa4-25d5-46dd-ad9b-25bdc29bab75.png)
![image](https://user-images.githubusercontent.com/89225401/139311155-08c3a1f7-2c03-46ac-a45b-294e560db551.png)

**Canals and Ditches**
![image](https://user-images.githubusercontent.com/89225401/139306714-3cc2dae9-c177-4463-9c04-b69c122aec95.png)
not appearing in WebRAVE

**Pipes and Ditches**
![image](https://user-images.githubusercontent.com/89225401/139306831-c480ed15-d6fe-4d0f-91f0-2ac08374b4fb.png)
not appearing/missing symbology

**Estimated Bankfull Width**
![image](https://user-images.githubusercontent.com/89225401/139304839-c93b959c-62f5-4089-a200-6662fe418f93.png)
![image](https://user-images.githubusercontent.com/89225401/139310699-059c36df-ba43-44a2-b1e2-99dda063e646.png)

**Estimated Bankfull Channel**
![image](https://user-images.githubusercontent.com/89225401/139304891-fd00dcbf-a234-4ecf-9d25-b0acb9dbbd33.png)
![image](https://user-images.githubusercontent.com/89225401/139310740-60cc73a2-a44d-4557-8345-652e97956e0f.png)

**NHD Flowlines Segmented 300m**
![image](https://user-images.githubusercontent.com/89225401/139305151-3968c7d8-1108-4301-9e36-52f5bbcec411.png)
![image](https://user-images.githubusercontent.com/89225401/139310795-2b0d0d9f-b4e3-4f49-a3c0-b8ead017b92a.png)

**NHD Flowlines intersected with road, rail and...
![image](https://user-images.githubusercontent.com/89225401/139305303-fd1e4cd0-b6fc-4062-9962-41b66cb7c1bb.png)
![image](https://user-images.githubusercontent.com/89225401/139310826-89b2da55-c3a5-4dea-825f-617818fd6a8c.png)

##Watershed Boundaries

**Region - 2-digit HUC**
![image](https://user-images.githubusercontent.com/89225401/139307119-2e7bc7be-4659-4f78-92c6-a34719e516ad.png)

**Subregion - 4-digit HUC**
![image](https://user-images.githubusercontent.com/89225401/139307208-9f8a5365-7827-40de-af20-426ba518e208.png)

**Basin - 6-digit HUC**
![image](https://user-images.githubusercontent.com/89225401/139307304-6d68d4bb-1da7-4a7e-910a-cb8b061f9fa5.png)

Sub-Basin - 8-digit HUC**
![image](https://user-images.githubusercontent.com/89225401/139307394-71e0aed5-0db9-45cb-bd9d-a479c4ef4789.png)

**Watersheds 10-digit HUC**
![image](https://user-images.githubusercontent.com/89225401/139307527-3224f34f-a4c5-4282-a83f-7b2a7747f895.png)

**Sub-watersheds - 12-digit HUC**
![image](https://user-images.githubusercontent.com/89225401/139307906-e23768d7-abf5-4c85-acca-ab9107a7df9b.png)

##Climate

**Mean Annual Precipitation (mm)**
![image](https://user-images.githubusercontent.com/89225401/139308079-17ad6856-663b-4335-93df-eec38663cd79.png)
![image](https://user-images.githubusercontent.com/89225401/139311241-8c9de720-ce55-47e3-a504-ec6c377873cd.png)

**Mean Temperature (C)**
![image](https://user-images.githubusercontent.com/89225401/139308134-1b350bd5-a36d-47ef-a3ce-acc75a417b76.png)
note legend and value breaks changing
![image](https://user-images.githubusercontent.com/89225401/139311274-7a494bb7-15d9-4e04-8237-09d72a5dd48e.png)

**Minimum Temperature (C)**
![image](https://user-images.githubusercontent.com/89225401/139308323-c0c16fa1-a00c-4011-be77-6ab98e764c7b.png)

**Maximum Temperature (C)**
![image](https://user-images.githubusercontent.com/89225401/139308421-f10f6a27-cee1-4634-81a9-47b99f8e00a9.png)

**Mean Dewpoint Temperature (C)**
![image](https://user-images.githubusercontent.com/89225401/139308547-7eb44e5b-1d46-4ec1-813b-c4e20ede1e1b.png)

**Minimum Vapor Pressure Deficit (hPa)**
![image](https://user-images.githubusercontent.com/89225401/139308664-0517da52-e76b-42dd-a48c-a7395ece9e3b.png)
![image](https://user-images.githubusercontent.com/89225401/139311343-80a30d88-2a20-4701-adcc-3556a53aeb60.png)

**Maximum Vapor Pressure Deficit (hPa)**
![image](https://user-images.githubusercontent.com/89225401/139308806-3098d789-6eb7-4821-a737-8a859cca06a1.png)

##Ecoregions

**Ecoregion 1**
![image](https://user-images.githubusercontent.com/89225401/139308960-49c74096-a60b-459a-ae7d-ce3b4e39fc0d.png)

**Ecoregion 2**
![image](https://user-images.githubusercontent.com/89225401/139309007-b45aa526-3af5-4225-acc2-b9a786a96e80.png)

**Ecoregion 3**
![image](https://user-images.githubusercontent.com/89225401/139309043-420490ec-7cda-4863-81b6-eee76be15a83.png)

##Land Management

**Land Ownership**
![image](https://user-images.githubusercontent.com/89225401/139309200-ef3d56e8-9fc8-4e9e-9d15-6a40ffb79de8.png)

**Fair Market Value**
![image](https://user-images.githubusercontent.com/89225401/139309254-378760a7-a29e-44eb-889f-ccd2dc27a7da.png)

##LANDFIRE

**Veg Type- EVT Class**
![image](https://user-images.githubusercontent.com/89225401/139309330-597a36f1-f7b0-47a4-8b7d-d60604973b9a.png)
![image](https://user-images.githubusercontent.com/89225401/139311433-e340bda0-64b7-4aa5-9a44-6df184cbd872.png)

**Veg Type- EVT Name**
![image](https://user-images.githubusercontent.com/89225401/139309413-2658745c-31c6-49f2-b9f5-efe6793c8479.png)
![image](https://user-images.githubusercontent.com/89225401/139311484-72da1b56-4bcc-4fc4-bd9d-2515a21be500.png)

**Veg Type- EVT Riparian**
![image](https://user-images.githubusercontent.com/89225401/139309490-78c31ed7-94aa-47a0-81c6-8ce4ec52c4a3.png)
![image](https://user-images.githubusercontent.com/89225401/139311529-f1feddd1-8821-4f14-83c1-aa8cf2aaa0da.png)

**Veg Type- BPS Name**
![image](https://user-images.githubusercontent.com/89225401/139309602-4a1818d4-cabb-4c90-95f7-c782b95e5917.png)
![image](https://user-images.githubusercontent.com/89225401/139311578-49a56c42-36ff-4627-8fde-6db7b7135022.png)

**Veg Type- BPS Riparian**
![image](https://user-images.githubusercontent.com/89225401/139309674-a15f7e9a-26c7-4896-ab00-7b005e2b147b.png)

##Topography and Derivitives

**DEM (10 m NED)**
![image](https://user-images.githubusercontent.com/89225401/139309752-382f3f4f-8046-4b6a-9b94-92ce67f001b6.png)

**Slope Analysis**
![image](https://user-images.githubusercontent.com/89225401/139309816-1b014cc6-b2d4-4b87-a496-c37a01504261.png)
![image](https://user-images.githubusercontent.com/89225401/139311775-d98355e9-0c48-41ae-833b-293b84532304.png)

**Flow Accumulation**
![image](https://user-images.githubusercontent.com/89225401/139309881-4f0a5ff9-70f3-4230-9a2c-51a1a8865e01.png)

**Drainage Area**
![image](https://user-images.githubusercontent.com/89225401/139310095-9d337cea-1338-4592-a094-974388d70cca.png)
zoom: 12.9
![image](https://user-images.githubusercontent.com/89225401/139340509-6e72cdee-7531-4027-bdb1-8e2f1548274e.png)

**Detrended DEM (HAND)**
![image](https://user-images.githubusercontent.com/89225401/139310193-e26462d5-951d-4df3-9549-cdc4ebe60155.png)

**Hillshade**
![image](https://user-images.githubusercontent.com/89225401/139310250-96b3cc41-87d0-4fe3-8e25-2200e07f5b99.png)

**Comment by Cashe93** [comment]
@MattReimer, here is a short video pointing out a small but weird issue I've been having with RS Context projects in WebRAVE. When I open up a project the default project view doesn't display properly, but when I add the layers individually they work. The weird thing is that I can't recreate the issue unless I restart my entire system. 

https://youtu.be/ozWtbwSvVNo

**Comment by Tanmanfalcon** [comment]
> @MattReimer, here is a short video pointing out a small but weird issue I've been having with RS Context projects in WebRAVE. When I open up a project the default project view doesn't display properly, but when I add the layers individually they work. The weird thing is that I can't recreate the issue unless I restart my entire system.
> 
> https://youtu.be/ozWtbwSvVNo

@Cashe93, @MattReimer 
Here are some screenshots of what he is describing since I haven't opened WebRAVE on my personal laptop yet.

This is what it looks like when I first opened it
<img width="609" alt="Capture5" src="https://user-images.githubusercontent.com/79670857/139712515-9f671cee-a4d7-45a3-862a-055b26055ec6.PNG">


After I delete everything in the view panel, I re-added the same layers and this is the result
<img width="586" alt="capture6" src="https://user-images.githubusercontent.com/79670857/139712528-2f658180-3abb-4925-9634-c2cbb253ec04.PNG">

**Comment by Tanmanfalcon** [comment]
# Screenshots with resolved Issues
**RSContext in WebRAVE**
*Project Type*: RSContext
*Layer(s)*: All (Vectors and Raster) 
*Project Tested*: https://northarrowresearchlabs.github.io/riverscapes-staging//#/Anabranch/9ed46e80-1b73-4051-ae04-f8082fc9d871

HUC ID: 10130203

# Transportation

**Roads**


**Rails**


# Hydrology

**Perennial Drainage Network**


**Intermittent Drainage Network**


**Ephemeral Drainage Network**

There was no Ephemeral Reaches in this project

**Network - Upstream Drainage Network**


**Full NHD HR+ Drainage Network**


**Drainage Wings**


**River Polygons (NHD Area)**


**Lakes, Ponds, Reservoirs and Water Bodies**


**Canals and Ditches**


**Pipes and Ditches**


# Estimated Bankfull

**Estimated Bankfull Width (m)**


**Estimated Bankfull Channel**


# Segmented Hydrography

**NHD Flowlines Segmented 300m**


**NHD Flowlines intersected with road, rail, and ownership, segmented to 300m**

There is no permanent symbology associated with this layer

# Watershed Boundaries

**Region - 2-Digit HUC**

Nothing Displayed for Region 2-Digit HUC

**Subregion - 4-Digit HUC**


**Basin - 6-Digit HUC**


**Sub-Basin - 8-Digit HUC**


**Watersheds - 10-Digit HUC**


**Sub-Watersheds - 12-Digit HUC**


# Climate

**Mean Annual Precipitation (mm)**


**Mean Temperature (°C)**


**Minimum Temperature (°C)**


**Maximum Temperature (°C)**


**Mean Dewpoint Temperature (°C)**


**Minimum Vapor Pressure Deficit (hPa)**


**Maximum Vapor Pressure Deficit (hPa)**


# Ecoregions 


**Level 1 Ecoregions**


**Level 2 Ecoregions**


**Level 3 Ecoregions**
Nothing Displays for Level 3 Ecoregions

# Land Management 

**Land Ownership**

**Fair Market Value**


# LANDFIRE 


**Veg Type - EVT Class**


**Veg Type - EVT Name**


**Veg Type - BPS Name**


# Topography and Derivatives

**DEM (10 m NED)**


**Slope Analysis**


**Flow Accumulation**


**Drainage Area**


**Detrended DEM (HAND - Height Above Nearest Drainage)**


# Hillshade 


**DEM Hillshade**

**Comment by MattReimer** [comment]
> > @MattReimer, here is a short video pointing out a small but weird issue I've been having with RS Context projects in WebRAVE. When I open up a project the default project view doesn't display properly, but when I add the layers individually they work. The weird thing is that I can't recreate the issue unless I restart my entire system.
> > https://youtu.be/ozWtbwSvVNo
> 
> @Cashe93, @MattReimer I am having the same issue as Cashe since I haven't opened WebRAVE on my personal laptop yet.
> 
> This is what it looks like when I first opened WebRAVE for the first time <img alt="Capture5" width="609" src="https://user-images.githubusercontent.com/79670857/139712515-9f671cee-a4d7-45a3-862a-055b26055ec6.PNG">
> 
> After I delete everything in the view panel, I re-added the same layers and this is the result <img alt="capture6" width="586" src="https://user-images.githubusercontent.com/79670857/139712528-2f658180-3abb-4925-9634-c2cbb253ec04.PNG">

I've dropped this into its own issue:

- https://github.com/Riverscapes/rs-web-monorepo/issues/173

**Comment by Tanmanfalcon** [comment]
After reviewing WebRAVE and comparing with ArcRAVE (#335) and QRAVE (#330), here are a list of problems that I have found

-Precipitation map is different from Arc, probably since the color ramp is not copying over correctly

-The Fair Market Value layer will not load, but instead is stuck on "Building..."
![image](https://user-images.githubusercontent.com/79670857/139722514-d012a608-f3f5-4105-9bee-f4f203acb26a.png)

-The Level 1 and 2 Ecoregions do not symbolize correctly and do not have a legend

-Estimated Bankfull Width (m) layer symbolizes correctly but does not have a legend to describe the different line widths

**Comment by Cashe93** [comment]
@Tanmanfalcon, in response to the Bankfull Width legend descriptions:

@MattReimer, correct me if I'm wrong, but there is no way to reference line width in the WebRAVE legend. I believe it's a limitation in Mapbox.

**Comment by MattReimer** [comment]
@Tanmanfalcon the fair market value not loading is nothing you can control. Hopefully as I move through the system we'll be able to re-run anything that's stuck or failed. If you're looking to validate a layer try to find a project where the tiles built. 

Not a limitation in mapbox. Just a limitation in the way I've written the legend. If we want a dimension other than color that will need to be added as a feature later (@joewheaton, are your ears burning). 

We can have a longer conversation about what's needed for legends across projects but for now none of that is possible here.

**Comment by Tanmanfalcon** [comment]
@MattReimer So what I understand is that none of these issues can be fixed in the near future, except for maybe the precipitation raster discussed in #310 and #319?

**Comment by MattReimer** [comment]
That's about right. Any legend enhancements will come in a future version.

Tile building problems are all known and being worked on in separate issues.

The color ramps are able to be tweaked (probably)

I suggest we break any problems I to their own tickets so we can tackle them separately and close this issue.

Nice work @Tanmanfalcon
