### ISSUE TITLE
Testing RSContext in QRAVE

### ISSUE THREAD

**Issue by leallysmith** [Riverscapes/RiverscapesXML#330]
RSContext in QRAVE
Project Type: RSContext
Layer(s): All (Vectors and Raster)
Project Tested: https://northarrowresearchlabs.github.io/riverscapes-staging//#/Anabranch/9ed46e80-1b73-4051-ae04-f8082fc9d871

HUC ID: 10130203

**Comment by Tanmanfalcon** [comment]
### Screenshots
**Roads**
![image](https://user-images.githubusercontent.com/89225401/139341232-a4ea5f55-a887-46da-b8b5-2a261db9f760.png)

**Rail**
![image](https://user-images.githubusercontent.com/89225401/139341434-f62937ce-f6a9-4131-b0b4-6e4ba94ffce4.png)

**Estimated Bankfull Width**
![image](https://user-images.githubusercontent.com/89225401/139343055-8eb17c2f-2f6e-4c2f-b644-310a09cf831e.png)

**Estimated Bankfull Channel**
![image](https://user-images.githubusercontent.com/89225401/139343079-82855852-6f6a-48cc-8a11-4d89a1d80eae.png)

**NHD Flowlines Segmented 300m**
![image](https://user-images.githubusercontent.com/89225401/139343321-0ffe8235-f023-48f7-864c-60ed49835e20.png)

**NHD Flowlines intersected with road, rail and...
![image](https://user-images.githubusercontent.com/89225401/139343355-6568ad13-596e-4a47-a7d3-e1b19e4b4256.png)

**Perennial Drainage Network**
![image](https://user-images.githubusercontent.com/89225401/139341490-5a730bd2-52c1-4e19-aed1-37de32e45a04.png)

**Intermittent Drainage Network**
![image](https://user-images.githubusercontent.com/89225401/139341565-34314570-69f7-49c2-b27c-c19f6f8ed7c5.png)

**Ephemeral Drainage Network**
![image](https://user-images.githubusercontent.com/89225401/139341617-8df88a81-cdc9-446f-ae09-3689e034ac46.png)

**Network- Upstream Drainage Area**
![image](https://user-images.githubusercontent.com/89225401/139341675-caa430ae-5151-4be9-a234-ca45d57d7001.png)

**Full NHD HR+ Drainage Network**
![image](https://user-images.githubusercontent.com/89225401/139341705-db48cbc0-3740-4d68-ae17-7c98994221ce.png)

**Drainage Wings**
![image](https://user-images.githubusercontent.com/89225401/139341752-0259c8aa-de45-4651-9004-4058e7f00a95.png)

**River Polygons (NHD Area)**
![image](https://user-images.githubusercontent.com/89225401/139341873-bb11c067-52ff-47b3-9ec5-ccfd8a9c6d2b.png)

**Lakes, Ponds, Reservoirs and Water Bodies**
![image](https://user-images.githubusercontent.com/89225401/139341904-0e8328bc-22d2-4e21-b179-d8675dae563c.png)

**Canals and Ditches**
![image](https://user-images.githubusercontent.com/89225401/139342003-1d12a86c-c779-4ec5-8330-f0de3467c7f2.png)

**Pipes and Ditches**
![image](https://user-images.githubusercontent.com/89225401/139342040-92c9f0e3-fa4d-453b-9bc8-4100104d2010.png)

**Region - 2-digit HUC**
does not display in q, arc, web

**Subregion - 4-digit HUC**
![image](https://user-images.githubusercontent.com/89225401/139342689-0bc64014-acf8-4c5a-8d70-5e6967d19033.png)

**Basin - 6-digit HUC**
![image](https://user-images.githubusercontent.com/89225401/139342832-d5dc2e2c-0252-45ff-8290-e68a74a20ee8.png)

Sub-Basin - 8-digit HUC**
![image](https://user-images.githubusercontent.com/89225401/139342866-a87b4bb1-1620-4f20-9838-5269a0c502f7.png)

**Watersheds 10-digit HUC**
![image](https://user-images.githubusercontent.com/89225401/139342891-f5e6a7f2-8dff-4ed4-a268-1eecf57f470a.png)

**Sub-watersheds - 12-digit HUC**
![image](https://user-images.githubusercontent.com/89225401/139342922-5a1b2739-8524-4328-bad2-d67ae02b9ac5.png)

**Mean Annual Precipitation (mm)**
![image](https://user-images.githubusercontent.com/89225401/139343430-a8ba507c-41dd-4146-9752-02c5ceeef9c7.png)

*note all temperature and vapor pressure images look like they might be displaying incorrectly but the temperature data is just very similar so it looks all one color
**Mean Temperature (C)**
![image](https://user-images.githubusercontent.com/89225401/139343489-8da7177e-0ad6-4ae3-b327-9dfe10fd6d3f.png)

**Minimum Temperature (C)**
![image](https://user-images.githubusercontent.com/89225401/139343545-43497eb8-c043-4a8b-98c3-f21ef5c5a0b2.png)

**Maximum Temperature (C)**
![image](https://user-images.githubusercontent.com/89225401/139343632-c6d32654-e328-438f-8457-c7537786124c.png)

**Mean Dewpoint Temperature (C)**
![image](https://user-images.githubusercontent.com/89225401/139343695-c8956162-8109-4a62-911e-aec79707278d.png)

**Minimum Vapor Pressure Deficit (hPa)**
![image](https://user-images.githubusercontent.com/89225401/139343803-c25279af-0d4d-4ab6-acac-f471d0a84b69.png)

**Maximum Vapor Pressure Deficit (hPa)**
![image](https://user-images.githubusercontent.com/89225401/139343965-571a7660-c161-468c-8566-735acc389eea.png)

**Ecoregion 1**
not displaying anything

**Ecoregion 2**
![image](https://user-images.githubusercontent.com/89225401/139344170-f659632f-ad7a-4678-9c99-c452d6dcc059.png)

**Ecoregion 3**
not displaying

**Land Ownership**
![image](https://user-images.githubusercontent.com/89225401/139344629-819ce85a-bc0a-4e0b-944d-d8a4425d040a.png)

**Fair Market Value**
![image](https://user-images.githubusercontent.com/89225401/139344651-b9e5423a-280e-4a70-9e82-e8d2d7f63ce2.png)

**Veg Type- EVT Class**
![image](https://user-images.githubusercontent.com/89225401/139344719-dd6d1c92-a212-4c74-a917-fb675b0d198a.png)

**Veg Type- EVT Name**
![image](https://user-images.githubusercontent.com/89225401/139344784-a4d0621e-635f-43cd-ac49-0b2143eb0b29.png)

**Veg Type- EVT Riparian**
![image](https://user-images.githubusercontent.com/89225401/139344813-10eb87e1-ce30-4761-9b74-2466afd73805.png)

**Veg Type- BPS Name**
![image](https://user-images.githubusercontent.com/89225401/139344848-8181507f-9cfc-4048-9e1c-12b3940a0e46.png)

**Veg Type- BPS Riparian**
![image](https://user-images.githubusercontent.com/89225401/139344914-51b5dc98-ef2d-4c59-98c6-396c3c31b95b.png)

**DEM (10 m NED)**
![image](https://user-images.githubusercontent.com/89225401/139344975-54308fdc-2ad8-43ad-aa22-0db172c9320a.png)

**Slope Analysis**
![image](https://user-images.githubusercontent.com/89225401/139345006-2ba28d62-3bb1-4c61-9cd5-1a766d7e04d1.png)

**Flow Accumulation**
![image](https://user-images.githubusercontent.com/89225401/139345068-9b28accb-aa06-44e3-b6a7-e56407fb5ee9.png)
![image](https://user-images.githubusercontent.com/89225401/139346071-0ed62fca-b43c-4161-bdcc-a987c1d60d64.png)

**Drainage Area**
![image](https://user-images.githubusercontent.com/89225401/139345282-b5fc5c1a-33f5-465b-83bc-b9302c5a6e35.png)
![image](https://user-images.githubusercontent.com/89225401/139346091-2837272d-e72e-41a0-98d7-e8247caca691.png)

**Detrended DEM (HAND)**
![image](https://user-images.githubusercontent.com/89225401/139345304-b24db886-8782-4fe4-901a-4d0b3685d4ca.png)

**Hillshade**
![image](https://user-images.githubusercontent.com/89225401/139345336-f80fd7ea-14eb-4793-9c49-ca4deb470b10.png)

**Comment by Tanmanfalcon** [comment]
# Issues 
After reviewing QRAVE and comparing with ArcRAVE (#335), I have found the following issues

## Mean Annual Precipitation
min/max values for color ramp are not the same as Arc and cause Q to display precipitation as one solid color.
**Symbology in QRAVE:**
![image](https://user-images.githubusercontent.com/89225401/139336081-0f4ffffe-c24b-4037-a5ca-9f6137287931.png)
![image](https://user-images.githubusercontent.com/89225401/139337228-59667ce2-a44b-4337-94f2-243d42e39d90.png)
**Symbology in ArcRAVE:**
![image](https://user-images.githubusercontent.com/79670857/139709516-aa5436c4-df7b-46a8-a48d-da61a5eb7134.png)


## Flow Accumulation
**Symbology in QRAVE:**
![image](https://user-images.githubusercontent.com/79670857/139709865-33746f47-bc62-425d-8fc3-052d1fbbfc98.png)
![image](https://user-images.githubusercontent.com/89225401/139339369-e5546b30-3d02-4921-86c9-47e22f42f10e.png)
**Symbology in ArcRAVE:**
![image](https://user-images.githubusercontent.com/79670857/139709924-642cad96-f08d-4768-8e0b-07936234432a.png)
![image](https://user-images.githubusercontent.com/89225401/139339402-909f6db4-e64b-457c-be5b-b65202f57dff.png)

**Comment by Tanmanfalcon** [comment]
All layers are symbolizing equal to ArcRAVE, other than the precipitation layer mentioned above.

**Comment by CHafen** [comment]
I think the Drainage area also doesn't quite match ArcRAVE
![Arc_DrainageArea](https://user-images.githubusercontent.com/39837888/139943952-c3f72057-8c17-4097-8b04-84e00f729451.png)
![QRAVE_DrainageArea](https://user-images.githubusercontent.com/39837888/139943958-7778d927-0acd-4aeb-a1e7-d02f0fbdc7fc.png)
 Images are from HUC 05020004.
I wonder if this is the same symbology transfer problem that the 
I wonder if this is the mean annual precip has.
