### ISSUE TITLE
Author symbology files for WebRAVE and provide link in commit to webRAVE of project it can be tested on

### ISSUE THREAD

**Issue by lauren-herbine** [Riverscapes/RiverscapesXML#338]
- [x] "[Channel Area (hollow)](https://github.com/Riverscapes/RiverscapesXML/blob/master/Symbology/web/Shared/ChannelArea_hollow.json)" "ChannelArea_hollow"

  [shared](https://github.com/Riverscapes/RiverscapesXML/tree/master/Symbology/web/Shared)

- [x] "[Channel Area (filled)](https://github.com/Riverscapes/RiverscapesXML/blob/master/Symbology/web/Shared/ChannelArea.json)" "ChannelArea"

  [shared](https://github.com/Riverscapes/RiverscapesXML/tree/master/Symbology/web/Shared)

- [x] "[NHD Waterbodies (Filtered)](https://github.com/Riverscapes/RiverscapesXML/blob/master/Symbology/web/ChannelArea/FILTERED_WATERBODY.json)" "FILTERED_WATERBODY"

  [ChannelArea](https://github.com/Riverscapes/RiverscapesXML/tree/master/Symbology/web/ChannelArea)

- [ ] "[NHD Flow Areas (Filtered)](https://github.com/Riverscapes/RiverscapesXML/blob/master/Symbology/web/ChannelArea/FILTERED_FLOWAREAS.json)" "FILTERED_FLOWAREAS"

  [ChannelArea](https://github.com/Riverscapes/RiverscapesXML/tree/master/Symbology/web/ChannelArea)

- [ ] "[Flow Areas, No Islands](https://github.com/Riverscapes/RiverscapesXML/blob/master/Symbology/web/ChannelArea/FLOW_AREA_NO_ISLANDS.json)" "FLOW_AREA_NO_ISLANDS" 

  [ChannelArea](https://github.com/Riverscapes/RiverscapesXML/tree/master/Symbology/web/ChannelArea)

- [x] "[Combined Flow Areas and Waterbodies](https://github.com/Riverscapes/RiverscapesXML/blob/master/Symbology/web/ChannelArea/COMBINED_FA_WB.json)""COMBINED_FA_WB"

  ChannelArea

- [x] "[Bankfull Network](https://github.com/Riverscapes/RiverscapesXML/blob/master/Symbology/web/ChannelArea/BANKFULL_NETWORK.json)" "BANKFULL_NETWORK"

  [ChannelArea](https://github.com/Riverscapes/RiverscapesXML/tree/master/Symbology/web/ChannelArea)

- [x] "[Bankfull Polygons](https://github.com/Riverscapes/RiverscapesXML/blob/master/Symbology/web/ChannelArea/BANKFULL_POLYGONS.json)" "BANKFULL_POLYGONS"

  [ChannelArea](https://github.com/Riverscapes/RiverscapesXML/tree/master/Symbology/web/ChannelArea)

- [x] "[Difference Polygons](https://github.com/Riverscapes/RiverscapesXML/blob/master/Symbology/web/ChannelArea/DIFFERENCE_POLYGONS.json)" "DIFFERENCE_POLYGONS"

  [ChannelArea](https://github.com/Riverscapes/RiverscapesXML/tree/master/Symbology/web/ChannelArea)

- [x] "[NHD Flowlines](https://github.com/Riverscapes/RiverscapesXML/blob/master/Symbology/web/Shared/FLOWLINES.json)" "FLOWLINES"

  shared and [ChannelArea](https://github.com/Riverscapes/RiverscapesXML/tree/master/Symbology/web/ChannelArea)

- [x] "[NHD Flow Areas](https://github.com/Riverscapes/RiverscapesXML/blob/master/Symbology/web/ChannelArea/FLOWAREAS.json)" "FLOWAREAS"

  [ChannelArea](https://github.com/Riverscapes/RiverscapesXML/tree/master/Symbology/web/ChannelArea)

- [x] "[NHD Waterbody Areas](https://github.com/Riverscapes/RiverscapesXML/blob/master/Symbology/web/ChannelArea/WATER_BODIES.json)" "WATER_BODIES"

  [ChannelArea](https://github.com/Riverscapes/RiverscapesXML/tree/master/Symbology/web/ChannelArea)

**Comment by joewheaton** [comment]
@lauren-herbine can you provide an update on this one? If done, please close this and parent.

**Comment by lauren-herbine** [comment]
@joewheaton I still need to get 
- [ ] filtered flow areas
- [ ] flow areas
- [ ] waterbodies

up and running with FCodes properly symbolized. It looks like my xml for the filtered waterbodies worked, so I'll work through that in the same manner

**Comment by lauren-herbine** [comment]
Assuming latest pull request gets the symbology to work nicely, closing

**Comment by joewheaton** [comment]
> Assuming latest pull request gets the symbology to work nicely, closing

Did it @lauren-herbine? @MattReimer does this just automatically work? I tested on https://webrave.riverscapes.xyz/#/BLM/4a63ee98-d3bb-44f2-83e4-1de0d8f76994 and it worked in intermediates but not inputs.

**Comment by lauren-herbine** [comment]
@joewheaton I just tested it on the same one you linked to, and it worked for me in both intermediates and inputs...

**Comment by joewheaton** [comment]
> > Assuming latest pull request gets the symbology to work nicely, closing
> 
> Did it @lauren-herbine? @MattReimer does this just automatically work? I tested on https://webrave.riverscapes.xyz/#/BLM/4a63ee98-d3bb-44f2-83e4-1de0d8f76994 and it worked in intermediates but not inputs.

Well this seems like it is more likely a problem with WebRAVE so I posted issue here: https://github.com/Riverscapes/rs-web-monorepo/issues/186 (it seems like symbology is working otherwise). @MattReimer if you discover otherwise you can move it.
