### ISSUE TITLE
New Project Type: Project Planning and Design Definition

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/RiverscapesXML#35]
1. [ ] Weber creates example project with populated geopackage(s) organized in folders.
1. [ ] Weber and Matt meet to author project XML. Also add empty report HTML file.
1. [ ] Weber empties the example Geopackage of data and puts in placeholders in XML. Then zips this "template" and puts it in GitHub attached to a release.
1. [ ] Weber authors instructions for Anabranch staff to download and populate the template with their project data.
1. [ ] Anabranch staff populate their projects and send them to Weber.
1. [ ] Weber validates projects as he receives them and uploads them in to the warehouse.
1. [ ] Philip and Weber collaborate on defining business logic and symbology.
1. [ ] Anabranch staff start downloading and viewing projects in RAVE.

@joewheaton @MattReimer

**Comment by joewheaton** [comment]
Note, this was not done (just discussed), but now is superseded by QRiS. Design and Planning will be split into their own projects. See #182.
