### ISSUE TITLE
Data Capture Validation layer has inconsistent symbology between arc and Q rave

### ISSUE THREAD

**Issue by leallysmith** [Riverscapes/RiverscapesXML#351]
## Specification
*Project*: Idaho_BRAT HUC 14040104 https://northarrowresearchlabs.github.io/riverscapes-staging//#/Anabranch/a4ac8fcc-3b84-4e94-a534-3654cb30b5a2
*Project Type*:  `pyBRAT` 
*Layer(s)*: Data Capture Validation Layer in Outputs/Validation
*Type(s)* - Vector

### Issue

Data Capture Validation Layer is not symbolized in QRAVE or ArcRAVE and green in WebRAVE

**Comment by Cashe93** [comment]
Fixed: 11/2/21
