### ISSUE TITLE
Symbology for ArcRAVE Perennial Layer doesn't match other RAVE platforms

### ISSUE THREAD

**Issue by leallysmith** [Riverscapes/RiverscapesXML#352]
## Specification
*Project*: Idaho_BRAT HUC 14040104 https://northarrowresearchlabs.github.io/riverscapes-staging//#/Anabranch/a4ac8fcc-3b84-4e94-a534-3654cb30b5a2
*Project Type*:  `pyBRAT` 
*Layer(s)*: Perennial in intermediates
*Type(s)* - Vector

### Issue

Perennial layer for arc rave is not symbolized by perennial or non perennial, displays all sections of stream as one color
ArcRAVE
![image](https://user-images.githubusercontent.com/89225401/139919764-0cbb66de-891f-4b76-89de-37a29d21ad64.png)

WebRAVE
![image](https://user-images.githubusercontent.com/89225401/139919803-c6e5356d-c706-40d6-b909-985277b75a10.png)

**Comment by Cashe93** [comment]
Fixed: 11/2/2021

![image](https://user-images.githubusercontent.com/49880208/139987486-58c32d0c-5f88-4de9-90f0-7963fa2688e8.png)
