### ISSUE TITLE
pyBRAT webRAVE is incorrectly displaying historic veg dam building capacity

### ISSUE THREAD

**Issue by leallysmith** [Riverscapes/RiverscapesXML#353]
## Specifications
*Project*: Idaho_BRAT HUC 14040104 https://northarrowresearchlabs.github.io/riverscapes-staging//#/Anabranch/a4ac8fcc-3b84-4e94-a534-3654cb30b5a2
*Project Type*: pyBRAT
*Layer*: Historic Veg Dam Building Capacity
Type - Vector

## Issue
WebRAVE has a legend for this layer but symbolizes everything as one color
![image](https://user-images.githubusercontent.com/89225401/139923576-e3f2a38d-c8d4-485b-87f7-113021ee644a.png)

**Comment by MattReimer** [comment]
Look for a field name mispelling or change here. Smells like it can't find the right column OR that column is actually missing data for this project.

**Comment by Cashe93** [comment]
@MattReimer and @leallysmith, the attribute field attempting to be referenced was oVC_HPE but the actual name was oVC_Hpe. Easy fix; it will be included in my next pull request.
