### ISSUE TITLE
Land Ownership per Reach not symbolized the same in QRAVE and WebRAVE

### ISSUE THREAD

**Issue by leallysmith** [Riverscapes/RiverscapesXML#354]
## Specifications
*Project*: Idaho_BRAT HUC 14040104 https://northarrowresearchlabs.github.io/riverscapes-staging//#/Anabranch/a4ac8fcc-3b84-4e94-a534-3654cb30b5a2
*Project Type*: pyBRAT
*Layer*: Land Ownership per Reach
Type - Vector

## Issue
Land Ownership layer is inconsistently symbolized between QRAVE and WebRAVE
Qrave
![image](https://user-images.githubusercontent.com/89225401/139924461-a6786925-392d-448a-b174-ee5712868c65.png)
![image](https://user-images.githubusercontent.com/89225401/139924704-607ebfef-94ab-4d83-a2eb-976ccefd7558.png)

WebRAVE
![image](https://user-images.githubusercontent.com/89225401/139924488-b19cb35b-fcc6-46e2-a17d-226d54357025.png)
![image](https://user-images.githubusercontent.com/89225401/139924666-8217a05d-73ad-461f-a232-6965e7607a11.png)

**Comment by Cashe93** [comment]
Fixed: 11/2/2021
Will be part of the next pull request.
