### ISSUE TITLE
pyBRAT Canals and Ditches layer symbolized with different lines in web vs q

### ISSUE THREAD

**Issue by leallysmith** [Riverscapes/RiverscapesXML#356]
## Specifications
*Project*: Idaho_BRAT HUC 14040104 https://northarrowresearchlabs.github.io/riverscapes-staging//#/Anabranch/a4ac8fcc-3b84-4e94-a534-3654cb30b5a2
*Project Type*: pyBRAT
*Layer*: Canals and ditches
Type - Vector

## Issue
Qrave has symbolized canals and ditches as lines with marks off the side while webrave has canals and ditches as plain lines
QRAVE
![image](https://user-images.githubusercontent.com/89225401/139928082-14126868-63f5-48b9-8690-04f79f489d0b.png)
WebRAVE
![image](https://user-images.githubusercontent.com/89225401/139928134-5cad56ac-2615-457b-b189-6d69f8257e95.png)

**Comment by Cashe93** [comment]
@leallysmith, well done on spotting these differences. Unfortunately, for some layers, we haven't been able to duplicate WebRAVE symbology to be exactly what we have in Arc and Q. This is a good example of that; for now, I think this symbology is close enough to Arc and Q.
