### ISSUE TITLE
Land Use is symbolized entirely different across all 3 RAVE platforms

### ISSUE THREAD

**Issue by leallysmith** [Riverscapes/RiverscapesXML#361]
## Specifications
*Project*: Idaho_BRAT HUC 14040104 https://northarrowresearchlabs.github.io/riverscapes-staging//#/Anabranch/a4ac8fcc-3b84-4e94-a534-3654cb30b5a2
*Project Type*: pyBRAT
*Layer*:  Land Use in inputs
Type - Raster

## Issue
Land Use layer has very different symbologies for each RAVE. Land use is also not displaying in QGIS
ArcRAVE image only has part of a very long legend
![image](https://user-images.githubusercontent.com/89225401/139959734-5ada2779-1f49-4a67-82bb-0c4177172303.png)
QRAVE
![image](https://user-images.githubusercontent.com/89225401/139959221-95739688-e490-454f-a61d-433403b4aee6.png)
WebRAVE
![image](https://user-images.githubusercontent.com/89225401/139959266-d9fb9c08-d8c6-43cb-b728-feecf011f56e.png)

**Comment by Cashe93** [comment]
I was able to fix the ArcRAVE symbology. @MattReimer, for Q and ultimately Web, this appears to be another categorized raster issue similar to the vegetation rasters.
