### ISSUE TITLE
Existing riparian layer in pyBRAT for ArcRAVE not symbolized like other platforms

### ISSUE THREAD

**Issue by leallysmith** [Riverscapes/RiverscapesXML#368]
## Specifications
*Project*: Idaho_BRAT HUC 14040104 https://northarrowresearchlabs.github.io/riverscapes-staging//#/Anabranch/a4ac8fcc-3b84-4e94-a534-3654cb30b5a2
*Project Type*: pyBRAT
*Layer*:  Existing Riparian
Type - Raster

## Issue
Existing Riparian input layer is not classed into riparian and not riparian like in other platforms
arcrave
![image](https://user-images.githubusercontent.com/89225401/140171731-24603677-06eb-4dc9-abde-0499b4e53d03.png)

webrave
![image](https://user-images.githubusercontent.com/89225401/140172134-b3fb0bc7-07b7-4e4f-8df5-9efa239db925.png)

**Comment by Cashe93** [comment]
Fixed 11/4/2021: Should be included in pull request #363
