### ISSUE TITLE
Historic Riparian layer in pyBRAT for ArcRAVE project symbolized incorrectly

### ISSUE THREAD

**Issue by leallysmith** [Riverscapes/RiverscapesXML#369]
## Specifications
*Project*: Idaho_BRAT HUC 14040104 https://northarrowresearchlabs.github.io/riverscapes-staging//#/Anabranch/a4ac8fcc-3b84-4e94-a534-3654cb30b5a2
*Project Type*: pyBRAT
*Layer*: Historic Riparian
Type - Raster

## Issue
Symbology is different between arcrave and other platforms.
arcrave
![image](https://user-images.githubusercontent.com/89225401/140172771-4d08ad2c-021e-4bb7-af82-0fbc8e3d5687.png)
webrave
![image](https://user-images.githubusercontent.com/89225401/140173074-6856f1f5-4d49-40b6-b7fb-5a3668c807df.png)

**Comment by Cashe93** [comment]
This has been fixed:

![image](https://user-images.githubusercontent.com/49880208/142468686-f78dc955-e87d-4d6c-a490-17638e16066b.png)
