### ISSUE TITLE
Symbology for 5 layers for pyBRAT in ArcRAVE

### ISSUE THREAD

**Issue by leallysmith** [Riverscapes/RiverscapesXML#371]
## Specifications
*Project*: Idaho_BRAT HUC 14040104 https://northarrowresearchlabs.github.io/riverscapes-staging//#/Anabranch/a4ac8fcc-3b84-4e94-a534-3654cb30b5a2
*Project Type*: pyBRAT
*Layer*: Land Ownership per Reach, Anabranch Types, Roads, Land Ownership, Flow Accumulation
Type - Vector and Raster

## Issue
Those 5 layers have no assigned symbology so they just generate random symbology.

**Comment by Cashe93** [comment]
These have been all been fixed as of 11/15. Changes will be included within next pull request.
