### ISSUE TITLE
Trouble Replicating Symbology between QRAVE and ArcRAVE

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/RiverscapesXML#372]
This was posted a while ago, and I still need help with it if/when folks have time. Should I just classify them?

> Hey @CHafen, @Cashe93, @Tanmanfalcon or any other ArcMap aficionados.. I'm having an issue with getting some of the symbology that I have in QRAVE to behave the same way in ArcRAVE, summarized in this video:
> 
> [![Video Link](http://img.youtube.com/vi/6_jgGTjeQU4/0.jpg)](http://www.youtube.com/watch?v=6_jgGTjeQU4"")
> 
> This is the same issue I'm having for symbolizing TWI, Likelihood of Valley Bottom, and Normalized TWI. Any help is greatly appreciated!
> 

_Originally posted by @shelbysawyer in https://github.com/Riverscapes/RiverscapesXML/issues/299#issuecomment-955821270_

**Comment by CHafen** [comment]
@shelbysawyer I'm not sure how to fix this problem. I'm having the same issue symbolizing rasters but in reverse, I can't get them to match up going from Arc to Q.

**Comment by Cashe93** [comment]
@shelbysawyer, are you just trying to reinforce the breaks at 0.05 intervals?

**Comment by shelbysawyer** [comment]
@Cashe93 No, and that's what's causing the problem-- the breaks are different for a few different layers, but I know one is like 0.5, 0.68, 0.80, 0.85, 0.99, 0.995.

**Comment by shelbysawyer** [comment]
> @shelbysawyer I'm not sure how to fix this problem. I'm having the same issue symbolizing rasters but in reverse, I can't get them to match up going from Arc to Q. I guess I don't have to legend problem. I just can't get stretched symbology to look the same at all between Arc and Q.

Okay, no worries-- thanks!

**Comment by Cashe93** [comment]
Hmmmm. That's a tricky one. Unfortunately, I don't have any solutions off the top of my head. The closest I was able to get it was just by relabeling the interval by 0.05. I'll let you know if anything else comes to mind. Sorry I couldn't be of assistance!

**Comment by shelbysawyer** [comment]
That's okay! I'll just classify it-- it won't look the same in the legend, but the data will be displayed the same way through the platforms. I'll take it! Thanks!

**Comment by joewheaton** [comment]
@shelbysawyer you don't need to use labels (I don't think), that's what's making your ramp legend look weird. I think it is just a matter of finding the closest thing you can on a stretch.

**Comment by shelbysawyer** [comment]
@joewheaton I was being forced into using labels because the I was using custom breaks (0.5, 0.68, 0.80, 0.85, 0.99, 0.995) instead of regular ones. But yeah, I'll just get it as close as I can.

**Comment by shelbysawyer** [comment]
Closing this. I got the symbology as close as I could manage.
