### ISSUE TITLE
Need help getting GUT symbology working on webRAVE.

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RiverscapesXML#385]
Hey @Riverscapes/riverscape-project-curators I'm trying to get GUT symbology working on webRAVE. It's my first time doing symbology for webRAVE, so I'm following along with the videos @lauren-herbine posted from the webRAVE workshop. But when I tried to upload my GEOJSON files to mapbox I got an error as shown in the screen shot. I'm not familiar with mapbox and have no idea what this means or how to fix it. Anyone know what I might be doing wrong or how to fix this?
![mapbox error](https://user-images.githubusercontent.com/39837888/142280328-2b618a32-0306-4798-b666-30577b75ae64.png)

_Originally posted by @CHafen in https://github.com/Riverscapes/RiverscapesXML/discussions/249#discussioncomment-1660827_

**Comment by joewheaton** [comment]
Your ears are burning @CHafen. See also: https://github.com/Riverscapes/riverscapes-website/discussions/23 and https://github.com/Riverscapes/rs-web-monorepo/issues/62. However, @MattReimer can confirm, but I think you can still get stuff going (and get help from fellow @Riverscapes/riverscape-project-curators) on this work. You just will not have the instant checking capability. @MattReimer is it worth having @CHafen edit just one GUT or Topo project to remove windows paths so we have one to test on?

**Comment by lauren-herbine** [comment]
Posted this on the curator discussion board, but didn't realize it had it's own issue as well:

@CHafen Hmmm... I am not familiar with this error- it looks like it has something to do with the spatial extent of your project. The only thing I can quickly think to troubleshoot is to ask if you deleted the line starting with "crs" in the geojson (using visual studio code or the like) before uploading to mapbox? I have a feeling that's not the problem, but just something to check.

You could also try clipping a piece of your map in Q or Arc to export a much smaller spatial extent- perhaps that would help?

**Comment by Cashe93** [comment]
I have a vague memory of getting this error in the past; I think @lauren-herbine 's suggestion of making sure the "crs" line is deleted is a good first step. Post here if that doesn't work.

**Comment by MattReimer** [comment]
I replied on the other board first so I'll repeat it here:

I think what may be happening here is you're trying to upload projected data instead of WGS84.

If you reproject you should be able to upload. Mapbox doesn't do projected data.

**Comment by CHafen** [comment]
Thanks @MattReimer it was projected so I changed it to WGS84 and that worked

**Comment by CHafen** [comment]
@Riverscapes/riverscape-project-curators does anyone have any experience or ideas how to do patters in mapbox? I'm trying to do the symbology for the image below and don't know how to go about it in mapbox.
![symbolizing_in_mapbox](https://user-images.githubusercontent.com/39837888/143314241-6166fdff-84a3-480a-b019-f7d71df4934a.png)

**Comment by Cashe93** [comment]
@CHafen, take a look at [this](https://github.com/Riverscapes/RiverscapesXML/discussions/249#discussioncomment-1522208) previous discussion between @MattReimer and @shelbysawyer. It looks like there isn't a way (yet) to add hatch patterns in Mapbox, but I could be wrong. @shelbysawyer, did you ever figure out a way to do this?

**Comment by MattReimer** [comment]
[There is is a way to do this in mapbox](https://docs.mapbox.com/mapbox-gl-js/example/fill-pattern/) but I haven't implemented the complementary call in webRAVE so we can use this. 

If we want to do this we're going to need to start curating images that correspond to the textures we want.

I made an issue to track this request as it has come up a couple of times recently.

- https://github.com/Riverscapes/rs-web-monorepo/issues/211

I'll circle back here when it's done but for now can you just use solid colors and we'll sort out the rest later.

**Comment by CHafen** [comment]
Hey @Riverscapes/riverscape-project-curators, I got the .JSON files up and the legends look good, but it looks like the symbology didn't work. Could someone look over the .JSON files 
https://github.com/Riverscapes/RiverscapesXML/tree/master/Symbology/web/GUT
 and see if I did something wrong? All the outputs for GUT are up and the legends are showing up, but nothing else. Could this possibly be because it's reach scale instead of the network scale that everything else so far has been. The DEM works though so maybe it's something on my end. See images below. And here's the webRAVE link for what I'm looking at. https://webrave.riverscapes.xyz/#/AsotinIMW/160fe239-5d8a-45f0-b3d7-546f3c8df4c4
Thanks
![GUT_symbology_not_working](https://user-images.githubusercontent.com/39837888/144122508-9234a397-8058-4318-a081-55047712e412.png)

![Gut_dem](https://user-images.githubusercontent.com/39837888/144122524-3289eb78-b015-4545-ae85-e0591ac921af.png)

**Comment by joewheaton** [comment]
I am not sure, but I think that this might simply be because we don't _yet_ render these tiles above a zoom level of 15 and these are 10 cm resolution reach-scale derivatives. We might need to wait a little bit for @MattReimer to make the fixes to handle tiling for reach-scale projects separately.

@philipbaileynar please let us know if:
a) this is something that will get fixed eventually and just sit tight
b) this is something @CHafen can do herself
c) if we need dedicated development funds (e.g. IMW for Asotin from ELR/Anabranch and @stephen-bennett.

**Comment by MattReimer** [comment]
I can confirm that the tiles for this are being built correctly. There is no issue with the scale of vector layers right now. the only issue we have is with raster layers not being able to go above zoom level 15 without blurriness. 

I suspect this is a problem with the mapbox symbology. @CHafen did you test this first in mapbox?

I'm seeing an error on the console:  **"layers.USRLYR_2011/Output/GUT_2.1/Run_01/Tier3_InChannel_GU.shp/Tier3_out_Tier3_GeomorphicUnit_0.paint.fill-color: Expected an even number of arguments."**

This is what I'm seeing in that JSON file:

```json
          "fill-color": [
              "match",
              ["get", "GU"],
              ["Bank"],
              "hsl(240, 100%, 0%)",
              ["Pool"],
              "hsl(213, 100%, 33%)",
              ["Pond"],
              "hsl(214, 100%, 50%)",
              ["Pocket Pool"],
              "hsl(213, 100%, 73%)",
              ["Chute"],
              "hsl(186, 100%, 50%)",
              ["Rapid"],
              "hsl(160, 51%, 60%)",
              ["Cascade"],
              "hsl(158, 34%, 40%)",
              ["Glide-Run"],
              "hsl(60, 100%, 45%)",
              ["Riffle"],
              "hsl(40, 100%, 45%)",
              ["Step"],
              "hsl(19, 42%, 73%)",
              ["Mid Channel Bar"],
              "hsl(19, 34%, 40%)",
              ["Margin Attached Bar"],
              "hsl(0, 100%, 33%)",
              ["Barface"],
              "hsl(0, 100%, 23%)",
              ["Transition"],
              "hsl(0, 0%, 80%)"
          ]
```

You're missing a "hsl()" reference at the end corresponding to a fallback color for everything else.

**Comment by CHafen** [comment]
Ok, thanks @MattReimer. With the other ones if I fix them to include the fallback color, should that make them show up do you think? It was hard to find these on mapbox because they're just reach scale, but I was able to find the reach and I made sure out_Tier1_FlowUnit is working on mapbox and it looks good. And it now includes the fallback color so hopefully that'll work with webRAVE now. And if it does I'll fix the other outputs, too.
I'm having an issue with Tier 3 Geomorphic Units (GU) and SubGUs because I don't think there are any reaches that have all the GU or SubGUs. So, I'm not sure how to do the symbology to include all of them. @joewheaton do you know of any that have them all or is there a way to symbolize these without having all on the same reach?

**Comment by MattReimer** [comment]
> Ok, thanks @MattReimer. With the other ones if I fix them to include the fallback color, should that make them show up do you think? 

I think so. Testing in Mapbox every single time isn't 100% required but I don't have any syntax checking so it's hard to catch these kinds of problems. Better to let Mapbox do that work for us.

As a kind of FYI or Pro tip: Very often if it's a mapbox style error you'll see it pop up in the browser console with the name "MAP ERROR". That's how I found the problem.


![Screen Shot 2021-12-03 at 12 36 43 PM](https://user-images.githubusercontent.com/1063391/144669629-b4ad2c60-feb0-4d0b-bb36-05bd2342b775.png)
