### ISSUE TITLE
Land Ownership - needs to be added to sqlBRAT project.xml's

### ISSUE THREAD

**Issue by Cashe93** [Riverscapes/RiverscapesXML#392]
@joewheaton I've updated the business logic to include the 'Land Ownership' Input layer, but this layer appears to be missing from the project.xml/inputs.gpkg. Is it possible to write this layer to the inputs.gpkg, similar to whats being requested in [#488?](https://github.com/Riverscapes/riverscapes-tools/issues/488)

Here is the updated sqlBRAT BL line for this layer

````
<Node label="Land Ownership" xpath="Geopackage/Layers/Vector[@id='OWNERSHIP']" type="polygon" symbology="ownership"/>
````

**Comment by philipbaileynar** [comment]
@KellyMWhitehead hopefully this is just a minor oversight and easy to include in the BRAT Build step?

**Comment by KellyMWhitehead** [comment]
This was added to the [December 2021 Release](https://github.com/Riverscapes/riverscapes-tools/releases/tag/Dec2021_release) per (#498)[https://github.com/Riverscapes/riverscapes-tools/issues/498]

@philipbaileynar, @joewheaton  please close or reassign if next steps are needed.

**Comment by Cashe93** [comment]
I've updated the Land Ownership symbology to be compatible with both pyBRAT and sqlBRAT. 

![image](https://user-images.githubusercontent.com/49880208/147155893-f9058455-0f30-420e-9f1f-2b163df15af8.png)

**Comment by MattReimer** [comment]
Stale issue. Closing.
