### ISSUE TITLE
Fix needed for the Perennial Network layer in BRAT

### ISSUE THREAD

**Issue by Cashe93** [Riverscapes/RiverscapesXML#408]
**Describe the bug**

The 'IsPeren' attribute field has Artificial Paths (FCode = 55800) coded as non-perennial (0). 

[![Video Link](http://img.youtube.com/vi/dpc1aMo0NIk/0.jpg)](http://www.youtube.com/watch?v=dpc1aMo0NIk "")

## TO-DO

- [x] Investigate and educate @Cashe93 as to why this is happening
- [x] Brainstorm fixes
- [x] Create branch, fix issue, create a pull request. 

**Expected behavior**
Artificial paths should be showing up as perennial.

**Additional context**
This is an issue for all RAVE projects.

**Comment by Cashe93** [comment]
@jtgilbert, would you be able to assist me in solving this issue?

**Comment by jtgilbert** [comment]
I think @KellyMWhitehead might have addressed this today here:
https://github.com/Riverscapes/riverscapes-tools/commit/cff978a4b35a965737a92cc0dd84fbd6f304fce9

Can you confirm Kelly?

**Comment by KellyMWhitehead** [comment]
Yes, `IsPeren` = 1 will now show up for artificial flowlines.

**Comment by joewheaton** [comment]
@KellyMWhitehead 

> Yes, `IsPeren` = 1 will now show up for artificial flowlines.
Isn't that only true if we re-run all the sqlBRAT projects? Is that the plan? @jtgilbert I don't think this is a fix you will be able to take care of as this was a fix of the model code and the models need to be re-run. Once they are, the symbology will be working just fine.

**Comment by jtgilbert** [comment]
@joewheaton @KellyMWhitehead  Yeah I think i rerun of everything is going to be needed eventually. There were the changes to the business logic (to add those intermediates), and I'm still working through a bit of QA/QC on hydrology with @Cashe93
