### ISSUE TITLE
Clear VSCode's XSD Cache

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/RiverscapesXML#41]
Couldn't find a good place to put this tip. Eventually it should end up where the XSD validation docs live.

Sometimes the old XSD gets stuck in cache. It's pretty easy to fix.

On a mac look for a `.lemminx` folder. Traverse it until you find the the XSD you want to remove and just delete the file

```
/Users/MYUSERNAME/.lemminx/cache/http/xml.riverscapes.xyz/Projects/XSD/V1/VBET.xsd
```

**Comment by philipbaileynar** [comment]
Done. Nice to have as issue for future reference.
