### ISSUE TITLE
[QA/QC] Schema for Riverscapes project XML

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/RiverscapesXML#410]
This task will allow for all QA/QC work in the system.

This is a stub ticket I'm using for project management purposes. It will be filled out with a full spec shortly and then tickets for specific actions will descend from it.

### The order of operations here is as follows:

- [x] 1. @MattReimer and Joe to meet and review all the discussions and data collected so far and discuss challenges/surprises (see below)
- [x] 2. @MattReimer and @joewheaton  to debate the merits of the XML schema and discuss things like future-proofing, flexibility and dimensionality
- [x] 3. @MattReimer to commit this change to `master` branch on `RiverscapesXML`
- [x] 4. @MattReimer and Tyler to discuss how we display this on the warehouse.
- [x] 5. @MattReimer to write a ticket for how the QA/QC crud is implemented in QRave and then move all work over to the QRave repo for implementation there.

### Kickoff meeting

Need to meet with Joe to talk about things like scope and workflow. Topics to be covered include:

1. We've been using GH issues for this now. Let's review how that's gone and what the major challenges are. 
2. How do we collect/interact with QA/QC data
3. How do we show QA/QC data in the warehouse and what role does that serve?
4. What is the dimensionality of this data?
5. Finally: Nuts and Bolts. What is the XML needed and how do we write it. 

### Relevant Discussions

- https://github.com/Riverscapes/RiverscapesData/discussions/1
- https://github.com/Riverscapes/RiverscapesData/discussions/8
- https://github.com/Riverscapes/RiverscapesData/discussions/9

**Comment by MattReimer** [comment]
Here's a first pass at what could end up in the Riverscapes project XML after adding QA/QC based on conversations with @joewheaton and @philipbaileynar 

This is a very rough first pass so let me know if anyone has any concerns about field names, dimensionality, edge cases etc.

``` xml
  <QAQCEvents>

    <!-- Here is some automated testing we do in Cybercastor -->
    <QAQCEvent state="passed" dateCreated="2022-04-11T17:56:39Z">
      <name>Manual Calibration</name>
      <performedBy>Cybercastor Automation</performedBy>
      <Summary>Automated Project QC Testing</Summary>
    </QAQCEvent>

    <!-- Here is the same event from before but passed -->
    <QAQCEvent state="failed" dateCreated="2022-04-11T17:56:39Z">
      <name>Manual Calibration</name>
      <performedBy>John Johnson</performedBy>
      <Summary>Failed to load layer X (see github link)</Summary>
      <Description><![CDATA[ This is a long-form commment deserunt elit ut nisi veniam pariatur eu excepteur in. Adipisicing ea qui id do incididunt deserunt sint est ullamco consectetur eu deserunt laboris excepteur. Consectetur nulla deserunt amet velit. Pariatur incididunt esse nulla nisi elit deserunt. Ad non ex aliqua officia et excepteur dolore Lorem veniam duis. Et amet nostrud exercitation do Lorem. Laborum fugiat ipsum labore eiusmod aliqua qui et dolore ipsum laboris ut.

Esse officia minim mollit nulla pariatur ut ipsum do qui est et ea esse minim. Duis commodo laboris sint enim qui esse ipsum in. Officia sunt tempor fugiat fugiat culpa elit elit. Mollit nostrud ea cupidatat fugiat adipisicing reprehenderit.

Ex labore minim ea magna minim reprehenderit ullamco labore exercitation ea sunt officia sunt. Occaecat aliqua sunt reprehenderit sit sit duis mollit irure tempor elit aute proident quis consequat. Est deserunt occaecat deserunt non tempor irure ut ea pariatur ullamco non irure consectetur.]]></Description>
      <Links>
        <URL text="github Link">https://github.com/Riverscapes/RiverscapesXML/issues/410</URL>
      </Links>
      <MetaData>
        <Meta name="SOMEKEY">SOMEVALUE</Meta>
      </MetaData>
    </QAQCEvent>
    
    <!-- Here is the same event from before but passed -->
    <QAQCEvent state="passed" dateCreated="2022-04-13T18:56:39Z">
      <name>Manual Calibration</name>
      <performedBy>John Johnson</performedBy>
      <Summary>This was a task of calibration performed by someone</Summary>
    </QAQCEvent>
  </QAQCEvents>

```

**Comment by philipbaileynar** [comment]
I like the "time line" approach to QAQC, but I have two questions (sorry if they are more appropriate elsewhere):

1. How do we measure "completeness" with a simple QC timeline?
    - How do we know 50% of QC is complete as opposed to 75%?
    - How does a reader know which layers are QC and which are yet to be looked at?

**Comment by MattReimer** [comment]
> I like the "time line" approach to QAQC, but I have two questions (sorry if they are more appropriate elsewhere):
> 
> 1. How do we measure "completeness" with a simple QC timeline?
>    
>    * How do we know 50% of QC is complete as opposed to 75%?

Short answer: We don't. QA/QC is going to mean different things for different projects, different organizations (and even different grades of projects i.e. research/production) So the idea of "completeness" is not something we can really track.

Given the challenges of how diverse our needs are this system just gives folks the ability to define what they mean by QA/QC and then lets the user decide if there's "enough" of it for their confidence level.

>    * How does a reader know which layers are QC and which are yet to be looked at?

There is no provision for layer-specific QA/QC at this time. We operate solely on the project-level.
