### ISSUE TITLE
Add Geology to RAVE as Basemap

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RiverscapesXML#415]
### Discussed in https://github.com/Riverscapes/riverscapes-website/discussions/29

<div type='discussions-op-text'>

<sup>Originally posted by **stephen-bennett** November 30, 2021</sup>
I'd like to request that a geology layer be added to riverscapes projects as it is a fundamental driver of riverscape form and function </div>

**Comment by joewheaton** [comment]
@philipbaileynar I believe that your suggestion of
> My recommendation is that we add this as a basemap in QRAVE

is spot on. My understanding is that for services that work in both Arc and Q, we can just add to the basemaps.xml? 

@jtgilbert this sort of explains it, but is out of date documentation: http://rave.riverscapes.xyz/Technical_Reference/base-maps.html... see https://github.com/Riverscapes/RaveAddIn/issues/182

**Comment by philipbaileynar** [comment]
There seem to be so many web mapping standards and each has a different URL format. This is an ESRI web mapping service and I'm unsure how it will play with both Q and Arc.

I recommend experimenting with your local copy of BaseMaps.xml for both QRAVE and ArcRAVE to see what works.

**Comment by jtgilbert** [comment]
@philipbaileynar I have it displaying in basemaps for both Q and Arc. However, it brings in a legend in Q and does not in Arc. Is this something you guys have dealt with before?

**Comment by philipbaileynar** [comment]
We have definitely encountered very different behaviour between how the two platforms handle web mapping layers! Sorry, I don't have much more to add. 

Remind me, do other web mapping layers in ArcGIS display legends?

**Comment by jtgilbert** [comment]
Yeah it looks like they generally don't. Should I push the changes as is then?

**Comment by philipbaileynar** [comment]
Web mapping layers are the wild west of GIS!

I think push. Can do no harm. Just less useful in ArcGIS. The original request for this layer came from a Mac/QGIS user...
