### ISSUE TITLE
Jekyll site upgrade to use HTTPS

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/RiverscapesXML#44]
**_This is a minor issue and has LARGE consequences for the warehouse so it should not be done lightly._** 

Maybe coordinate with a Warehouse release so that we can make adjustments quickly if we need to.

**Comment by philipbaileynar** [comment]
How does Jekyll relate to warehouse?

**Comment by MattReimer** [comment]
xml.riverscapes.xyz is called upon by the warehouse. If we start monkeying with the address we could break everything.

**Comment by joewheaton** [comment]
@MattReimer is this still a relevant issue?

**Comment by MattReimer** [comment]
yes. Still relevant. We can implement as part of the Warehouse 2.0. That's a good time for it.

**Comment by MattReimer** [comment]
I'm closing this. The xml repo accepts http AND https and this is important for testing webApps using create-react-app locally.
