### ISSUE TITLE
Potential Bug in

### ISSUE THREAD

**Issue by Arsinam80m** [Riverscapes/RiverscapesXML#472]
**Describe the bug**
A clear and concise description of what the bug is.  Including a video is super helpful (post it to YouTube and use this syntax to "embed it": [![Alt-text](https://img.youtube.com/vi/YTID/0.jpg)](https://www.youtu.be/watch?v=YTID){:target="_blank"} and [substitute the YouTube video ID](https://riverscapes.xyz/Tools/Technical_Reference/Documentation_Standards/WebSites/Common.html#markdown-alternative) for `YTID`)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Version [e.g. Web Rave v.1.3.2 or QRAVE v. 0.5]

**Riverscape Project (please complete the following information if relevent):**
 - Type: [e.g. RSContext]
 - Warehouse Link: [e.g. [3801fe70-9fbc-4f1a-ae35-6aa0e065d9da](https://data.riverscapes.xyz/#/BLM/3801fe70-9fbc-4f1a-ae35-6aa0e065d9da)]
 - Layers Impacted [e.g. DEM, Roads]

**Additional context**

**Comment by Arsinam80m** [comment]
> **Describe the bug** A clear and concise description of what the bug is. Including a video is super helpful (post it to YouTube and use this syntax to "embed it": [![Alt-text](https://camo.githubusercontent.com/66fe3d72426fa591bfb8ca9fa9141ef937d6d7a49cf1d164fa20d291cd7dbd6c/68747470733a2f2f696d672e796f75747562652e636f6d2f76692f595449442f302e6a7067)](https://www.youtu.be/watch?v=YTID){:target="_blank"} and [substitute the YouTube video ID](https://riverscapes.xyz/Tools/Technical_Reference/Documentation_Standards/WebSites/Common.html#markdown-alternative) for `YTID`)
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Go to '...'
> 
>     2. Click on '....'
> 
>     3. Scroll down to '....'
> 
>     4. See error
> 
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
>     * OS: [e.g. iOS]
> 
>     * Browser [e.g. chrome, safari]
> 
>     * Version [e.g. Web Rave v.1.3.2 or QRAVE v. 0.5]
> 
> 
> **Riverscape Project (please complete the following information if relevent):**
> 
>     * Type: [e.g. RSContext]
> 
>     * Warehouse Link: [e.g. [3801fe70-9fbc-4f1a-ae35-6aa0e065d9da](https://data.riverscapes.xyz/#/BLM/3801fe70-9fbc-4f1a-ae35-6aa0e065d9da)]
> 
>     * Layers Impacted [e.g. DEM, Roads]
> 
> 
> **Additional context** Add any other context about the problem here.

**Comment by Arsinam80m** [comment]
M

**Comment by joewheaton** [comment]
@jtgilbert please investigate.

**Comment by jtgilbert** [comment]
There's no info here....just copied and paste issue format. Closing for now.
