### ISSUE TITLE
Author VBET_SEP2022.xml

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/RiverscapesXML#476]

**Comment by joewheaton** [comment]
@shelbysawyer please talk to @philipbaileynar or @MattReimer about a better future proof way of versioning business logic.  Avoid things like "final" in a name. We need some guidelines on naming #477

**Comment by shelbysawyer** [comment]
Sounds good @joewheaton. This is the name @philipbaileynar instructed me to use during our meeting.

**Comment by joewheaton** [comment]
Thanks @shelbysawyer. @philipbaileynar I don't like that name. The notion that this will be the final is a pipedream at best. We need a way for these to get adapted and changed in future, without breaking previous versions. See updates to #477

**Comment by philipbaileynar** [comment]
The word "final" was merely a euphemism and not intended to be the last ever version. I just used this word to distinguish it from the temporary version that lists all layers and attributes for review.

**Comment by shelbysawyer** [comment]
@joewheaton Just adding on to say that this file is local on my computer, to be used for testing local changes only, and I more than likely missed the implied understanding that I shouldn't actually name the XML file as such when I share it. Sorry about that.

**Comment by shelbysawyer** [comment]
Closing, as this is finished. Will create new issue to update the XML when VBET is more stable.
