### ISSUE TITLE
Update VBET BusinessLogic to work with newer version

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/RiverscapesXML#497]
We've recently [revamped the way VBET](https://github.com/Riverscapes/riverscapes-tools/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22New+VBET+%282022%29%22) works so we need to update the Businesslogic in anticipation

**Comment by jtgilbert** [comment]
closing, opened a new issue assigning this to @shelbysawyer
