### ISSUE TITLE
Update VBET BL

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/RiverscapesXML#508]
remove:

- [x] Intermediates/Evidence Rasters/TWI Raster
- [x] Intermediates/Evidence Rasters/Normalized TWI Evidence
- [x] Intermediates/Transform Zones/ slope, Hand, TWI Transform Zones
- [x] Intermediates/Normalized Evidence Rasters/Combined Topographic Evidence (this is the same as output likelihood now)

add: 

- [x] Intermediates/Valley Bottom Rasters/Valley Bottom Level Paths (xpath="Intermediates/Raster[@id='VBET_ZONES']")
- [x] Intermediates/Valley Bottom Rasters/Estimated Active Valley Bottom Level Paths (xpath="Intermediates/Raster[@id='ACTIVE_FP_ZONES']")
- [x] Intermediates/Valley Bottom Rasters/Estimated Inactive Valley Bottom Level Paths (xpath="Intermediates/Raster[@id='INACTIVE_FP_ZONES']")

- [x] Change xpath for composite hand raster to "Intermediates/Raster[@id='HAND_RASTER']"
- [x] All xpaths for transformed rasters should be "Intermediates/Raster[@id='TRANSFORMED_HAND']" (or SLOPE)
- [x] Change "normalized" to "transformed" labels

THIS IS ALL FOR V1 XML. IF YOU'D LIKE YOU CAN UPDATE V2 XML SO THAT THEY ARE THE SAME. I'm not sure if you're familiar with the differences between v1 and v2...if not don't worry about it for now.

For layers that need symbology, @wally-mac has techs working on it so we can pass that along to them.

**Comment by shelbysawyer** [comment]
@jtgilbert I just created a pull request with the above changes made. I'm probably going to make additional changes to the BL after I finish checking out the 0.8.9 projects, but this will get the necessary layers exposed and working. Thanks!

**Comment by shelbysawyer** [comment]
Closing this for now #509

**Comment by jtgilbert** [comment]
Sounds good, I like the idea of you and @lauren-herbine customizing the BL to what makes sense to you prior to the actual release since you guys interact with it a lot.
