### ISSUE TITLE
Weber Pull

### ISSUE THREAD

**Issue by nick4rivers** [Riverscapes/RiverscapesXML#51]
@MattReimer  - I am trying to submit a pull request (I think), and am getting a 403 error.

I did the following
 - cloned this repo
 - created a new branch
 - added my .qml file
 - added a commit to my branch
 - tried to `git push origin my-branch-name`

Any ideas, sorry to bother you with these basics? but I'd like to keep fleshing out the .qml symbology for our riverscapes projects.

**Comment by MattReimer** [comment]
@nick4rivers  I may have had the security too tight on this repo. Try it again

**Comment by MattReimer** [comment]
Checked that you have access so I'm closing this
