### ISSUE TITLE
Integrated Geographic Objects (IGOs)

### ISSUE THREAD

**Issue by leallysmith** [Riverscapes/RiverscapesXML#515]
Before the lab gets started on the various IGO layers it would be helpful to work on this "base" symbology first to get the shape hammered out. In our meeting a couple weeks ago @joewheaton touched on how he wants these to look. If I recall right, Joe wanted these to look like a continuous line at various zooms? 

My best thought is to symbolize as a point without borders or @emilySarge had mentioned rectangles without borders. 

More detail/confirmation about how you want this to look before we dive into the various IGOs would be helpful @joewheaton !

**Comment by joewheaton** [comment]
> Before the lab gets started on the various IGO layers it would be helpful to work on this "base" symbology first to get the shape hammered out. In our meeting a couple weeks ago @joewheaton touched on how he wants these to look. If I recall right, Joe wanted these to look like a continuous line at various zooms?
> 

Thanks @leallysmith for this. So the IGOs are really just the points and for every IGO metric we can potentially symbolize.  We have it symbolized as a point-based sampling frame in VBET right now for Q (needs updating for WebRV and ArcRV). One idea for some of these is to make them look like a line (this will require using the bearing field that @KellyMWhitehead is providing) , whereas others may make sense (e.g. VB width) to orient using bearing perpendicularly and scale symbol size (length) to value.  There are lots of different ways we will need to explore and play with and different classes of metrics will make sense. IT might be helpful for you to meet with @shelbysawyer and @lauren-herbine on some of this too.

> My best thought is to symbolize as a point without borders or Paige had mentioned rectangles without borders.
> 

That does tend to be less distracting when zoomed out and the symbols overlap. It might be good to have different size scaling for different zoom levels.

> More detail/confirmation about how you want this to look before we dive into the various IGOs would be helpful @joewheaton !
> 
> (Will assign and tag Paige when I can)

Noted.... I will bring this up in the scrum with @lauren-herbine, @shelbysawyer and @jtgilbert tomorrow. Then we'll get some different ideas.

**Comment by leallysmith** [comment]
Any news on this front @joewheaton ? We can also dive in with our imaginations if no specific ideas of what people would like these IGOs to look like have come up.

**Comment by shelbysawyer** [comment]
@joewheaton I met today with @leallysmith and @Cashe93 to talk through some of this and I'm wondering if your thinking has changed on what you've outline above? Currently, VBET IGOs/DGOs are symbolized like this, with IGOs symbolized as solid points and DGOs symbolized as transparent polygons. I think this symbology pattern works well for information transparency and consistency reasons.
![igolarge](https://user-images.githubusercontent.com/73311751/231581146-c5c0bb1f-484d-47c3-b61c-510140c4820e.JPG)
![igozoomed](https://user-images.githubusercontent.com/73311751/231581161-2dff4dee-0268-44f8-8476-035ca5f1905d.JPG)

**These are the attributes available for VBET IGOs**
_italicized attributes are ones we are currently symbolizing_
LevelPathI
seg_distance
stream_size
active_floodplain_area
active_channel_area
inactive_floodplain_area
floodplain_area
**_integrated_width_**
**_window_size_**
window_area
centerline_length
**_active_floodplain_proportion_**
active_channel_itgr_width
**_active_channel_proportion_**
active_channel_itgr_width
**_inactive_floodplain_proportion_**
inactive_floodplain_itgr_width
floodplain_proportion
floodplain_itgr_width
**_vb_acreage_per_mile_**
**_vb_hectares_per_km_**
active_acreage_per_mile
active_hectares_per_km
inactive_acreage_per_mile
inactive_hectares_per_km

**These are the attributes available for VBET DGOs**
_italicized attributes are ones we are currently symbolizing_
LevelPathI
seg_distance
active_floodplain_area
**_active_floodplain_prop_**
active_channel_area
**_active_channel_prop_**
inactive_floodplain_area
**_inactive_floodplain_prop_**
floodplain_area
floodplain_prop
centerline_length
segnment_area

- I know we are moving away from using the terms "active/inactive" and "floodplain". Do you see this change being reflected in the field titles?
- Are there additional fields from the list above that you want to see exposed?

**Comment by leallysmith** [comment]
FYI @MB-Turnage and @emilySarge We're going to start with simple circles that have nice color ramps which match layers as appropriate (eg land use intensity IGO should match land use intensity raster). We'll focus on shapes and rotations later on. Just get some symbology going for eyes to see it.

**Comment by joewheaton** [comment]
> I know we are moving away from using the terms "active/inactive" and "floodplain". Do you see this change being reflected in the field titles?

Good question. Lets flag and discuss with @jtgilbert in our scrum this week. I'm fine with it just being reflected in business logic as long as documentation makes it clear.

> Are there additional fields from the list above that you want to see exposed?
On DGOs, this is good for now. On IGOs, yes please:

- active_channel_itgr_width
- inactive_floodplain_itgr_width
- floodplain_itgr_width

We also need a new one: active_prop (i.e. active_channel_prop plus active_floodplain_prop). It can be done symbolically (i.e. as opposed to creating a new field). 

> There is not currently a bearing field. Will there be?

@KellyMWhitehead, we talked about this. Did you ever get it working in VBET? @jtgilbert FYI. As a refresher, it is the bearing of the valley bottom centerline as it intersects the IGO point.

**Comment by joewheaton** [comment]
> FYI @MB-Turnage and @emilySarge We're going to start with simple circles that have nice color ramps which match layers as appropriate (eg land use intensity IGO should match land use intensity raster). We'll focus on shapes and rotations later on. Just get some symbology going for eyes to see it.

That's right @leallysmith. I think our default should be the same symbology (like @shelbysawyer shows) colors as what we use on a polygon, but the polygon would be 40% transparent, so these will pop a little. 

I do think we need to play with different symbol sizes at different zoom levels. At most HUC 10 zoom levels, symbols should get smaller instead of just fixed at any zoom level.
