### ISSUE TITLE
Diversions

### ISSUE THREAD

**Issue by leallysmith** [Riverscapes/RiverscapesXML#518]
![image](https://user-images.githubusercontent.com/89225401/225937230-6bdc2d3a-67ed-4895-9b99-6922f6d4b0aa.png)
This is the diversion symbology from pyBRAT, should I create a new symbology rather than using pyBRAT's?

- [x] ArcRAVE
- [x] QRAVE
- [x] WebRAVE

**Comment by jtgilbert** [comment]
Nope, if we have it might as well use it!

**Comment by leallysmith** [comment]
Additional question to go with this. If I move the py_div_pts from pyBRAT to Shared symbology will that break anything? Thanks! @jtgilbert
