### ISSUE TITLE
Floodplain Accessibility (Raster)

### ISSUE THREAD

**Issue by leallysmith** [Riverscapes/RiverscapesXML#519]
![image](https://user-images.githubusercontent.com/89225401/225969169-3ccf1372-af86-41a5-be17-d86bf3ac96f8.png)
Used active/inactive floodplain symbology from Geomorphic Mapping/Digitizing standards, should this be changed?

- [x] ArcRAVE
- [x] QRAVE
- [ ] WebRAVE

**Comment by jtgilbert** [comment]
I would probably change the colors to avoid confusion between this layer and estimated active/inactive vb

**Comment by jtgilbert** [comment]
I think that works.

**Comment by joewheaton** [comment]
Just make it transparent please. Nice work.
