### ISSUE TITLE
Conversion

### ISSUE THREAD

**Issue by MB-Turnage** [Riverscapes/RiverscapesXML#533]
![conversion_q](https://user-images.githubusercontent.com/127990296/227319974-e1c472ac-9f53-47e5-b3fa-390e44cab3b8.PNG)
![conversion_at](https://user-images.githubusercontent.com/127990296/227319991-d12db07f-f91b-4047-8bc7-215bd8acd012.PNG)

Is there any documentation or information on what each value means for conversion?

**Comment by jtgilbert** [comment]
Here are the values and their associated labels:
https://github.com/Riverscapes/riverscapes-tools/blob/anthro/packages/rcat/database/data/ConversionVals.csv

for any of the values that aren't in this table, they can be lumped into a 'Non-riparian conversions' class.

The color scheme we used in the first version of this tool is in the maps here for you to get an idea:
https://rcat.riverscapes.net/UtahR-CATMapAtlas

**Comment by MB-Turnage** [comment]
Thank you. 

One follow up, there are not -35 or 35 values in the attribute table (corresponding to From Deciduous or Deciduous conversion names). There is also not a 100 value for multiple conversions. Are there other values that might be associated with these things?

**Comment by jtgilbert** [comment]
@MB-Turnage Not every HUC will have every conversion type (e.g., how this one is missing -35 and 35, so you'll just have to add them manually to the symbology even though they're not present here. All of the values that aren't in that table can be lumped into a category called "Other Upland Vegetation Conversions"

**Comment by Cashe93** [comment]
@jtgilbert could you resend the csv with the conversion values? The link you sent appears to be broken.

**Comment by jtgilbert** [comment]
https://github.com/Riverscapes/riverscapes-tools/blob/master/packages/rcat/database/data/ConversionVals.csv
try that @Cashe93

**Comment by Cashe93** [comment]
That worked @jtgilbert. Thanks!

**Comment by Cashe93** [comment]
![image](https://github.com/Riverscapes/RiverscapesXML/assets/49880208/d8649e98-e4ac-4e5f-ba76-adab676a46a5)
