### ISSUE TITLE
Symbology Channel Area (active channel) layer for PBR Project Type

### ISSUE THREAD

**Issue by Cashe93** [Riverscapes/RiverscapesXML#547]
@jtgilbert or @MattReimer, the webRAVE symbology for the channel area doesn't seem to be working. I tried creating a new symbology layer to test out with the PBR project, but it still shows up as red instead of transparent blue. 
 
![image](https://user-images.githubusercontent.com/49880208/231012560-9276a078-bde9-4c14-b420-d3bbd8b6ae3b.png)

The JSON file is as follows: 
```{
  "$schema": "https://xml.riverscapes.xyz/Symbology/web/vector.schema.json",
  "legend": [
    ["hsl(206, 54%, 47%)", "Pre-Restoration Space (Active Channel)"]
  ],
  "layerStyles": [
    {
      "id": "off-habit-8qzfes",
      "type": "fill",
      "source": "composite",
      "source-layer": "off_habit-8qzfes",
      "layout": {},
      "paint": {"fill-color": "hsl(206, 54%, 47%)"}
  }
  ]
}
```

I've already made sure that the Business Logic is referencing the correct layer (it works for in both Q and Arc as well). Do you see any glaring issues, or have any suggestions? Thanks.

**Comment by Cashe93** [comment]
Hey @MattReimer, any luck with determining the cause of this?

**Comment by MattReimer** [comment]
I'm putting together some tilerizer investigations today so hopefully I'll have some answers for you.

**Comment by MattReimer** [comment]
I'm not sure where we left this. @Cashe93 did this get fixed eventally?

**Comment by Cashe93** [comment]
@MattReimer this appears to be working now. Thank you!
