### ISSUE TITLE
Rail (not even showing in webRAVE)

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RiverscapesXML#554]

**Comment by joewheaton** [comment]
So, I'm not sure about this one the symbology is ugly as sin, but it did show up for me in https://warehouse.riverscapes.net/rv/3a8993d5-c129-488a-8236-200400effbd8. Maybe the initial HUC 10s we looked at just didn't have railroads? Roads are not working.

**Comment by MattReimer** [comment]
Roads are definitely broken but I get Rail on some projects so I'm assuming something (maybe broken geometry) is making the tilerizer choke.

**Comment by joewheaton** [comment]
> Roads are definitely broken but I get Rail on some projects so I'm assuming something (maybe broken geometry) is making the tilerizer choke.

I can't yet prove to myself this is an issue. So I would ignore it for now @MattReimer. If someone else finds it, reopen or make new ticket and refer to this one.
