### ISSUE TITLE
Unnecessary Legend Items in Region - 2-Digit HUC legend in WebRV

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/RiverscapesXML#566]
Looks like there might be some unnecessary legend items for the HUC 2 layer:

![huc2legend](https://user-images.githubusercontent.com/73311751/231856306-23e5ea2e-e48e-428d-b1d7-02be076b5457.JPG)

**Comment by leallysmith** [comment]
Looks fixed on my end. I'm closing this issue @shelbysawyer, we can reopen if it didn't fix for you.
