### ISSUE TITLE
Update symbology for Acres of VB per mile and Hectares of VB per Kilometer

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/RiverscapesXML#578]
## Acres of VB per Mile
![ac_vb_mile_60percent](https://user-images.githubusercontent.com/73311751/232633193-7fb0cfce-5fbe-4f31-9a08-a4fdb49b0d54.JPG)
## Hectares of VB per Kilometer
![hec_vb_km_60percent](https://user-images.githubusercontent.com/73311751/232633063-13f82b82-7d85-447b-afb5-249072ec274f.JPG)
## Acres of Estimated Low-Lying VB per Mile
- Uses same color scheme as the "Acres of Estimated Elevated VB per mile"
![ac_est_lowlying_vb_mile_3colorramp](https://user-images.githubusercontent.com/73311751/232632488-24c55950-4bee-4e48-bd94-1a85551002ad.JPG)

## Acres of Estimated Elevated VB per Mile
- Uses the same breaks and color scheme (just inverted) as the "Acres of Estimated Low-Lying VB per mile"
![ac_est_elevated_vb_mile](https://user-images.githubusercontent.com/73311751/232632893-4da2967a-623f-451b-97e8-57c083e06082.JPG)

## Hectares of Estimated Low-Lying VB per Kilometer
- Same breaks & color scheme as Hectares of Elevated VB per Kilometer
- I will be pushing a qml for this despite [this bug](https://github.com/Riverscapes/riverscapes-tools/issues/772)
![hec_lowlying_km](https://user-images.githubusercontent.com/73311751/232838930-a43a27ec-7077-4f0d-8237-8adb5301c7e0.JPG)
## Hectares of Estimated Elevated VB per Kilometer
- Same breaks & color scheme as Hectares of Low-Lying VB per Kilometer
- Also pushing this qml despite bug and will reassess later
![hec_elevated_km](https://user-images.githubusercontent.com/73311751/232838945-f85a302d-de8c-41c2-90e6-607596a41b9b.JPG)

**Comment by joewheaton** [comment]
I agree @shelbysawyer . Option 2. Maybe add more categories then I had to resolve more differences. But I like option 2.

**Comment by jtgilbert** [comment]
I agree!
