### ISSUE TITLE
Update VBET Symblology: QRV

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/RiverscapesXML#583]
## QRV (.qml) 
Check indicates that I have either authored a qml or confirmed the function of existing qmls and have confirmed that qmls match the business logic
## Outputs
- [x] Valley Bottom Extent (Hollow) - "vbet_extent_hollow" 
- [x] Valley Bottom Extent (Filled) - "vbet_extent_filled" 
- [x] Relative Likelihood of being Valley Bottom (composite) - "vbetLikelihood" 

**Categorized VBET (2-class)**
- [x] Estimated Low-Lying Valley Bottom - "vbet_lowlying" 
- [x] Estimated Elevated Valley Bottom - "vbet_elevated" 

**Categorized VBET (3-class)**
- [x] Estimated Channel (Channel Area Input) - "vbet_channel_area"
- [x] Estimated Low-Lying Valley Bottom (without channel) - "vbet_lowlying" 
- [x] Estimated Elevated Valley Bottom - "vbet_elevated"

**Sample Frames**
- [x] Integrated Geographic Objects (IGOs) - "igo"
- [x] Centerline of Valley Bottom - "CL_vb"
- [x] Discrete Geographic Objects (DGOs) - "DGO"

**Sample Frame Metrics (DGO)**
- [x] Est. Prop. of Channel (DGOs) " - "dgo_prop_vb_channel"
- [x] Est. Prop of VB Low-Lying (DGOs) - "dgo_prop_vb_lowlying"
- [x] Est. Prop of VB Elevated (DGOs) - "dgo_prop_vb_elevated"

**Moving Window Metrics**
- [x] Acres of VB per Mile - "igo_ac_vb_mile"
- [x] Hectares of VB per Kilometer - "igo_hec_vb_km"
- [x] Est. Prop. of VB: Channel - "igo_est_prop_vb_channel"
- [x] Est. Prop. of VB: Low-Lying - "igo_est_prop_vb_lowlying"
- [x] Est. Prop of VB: Elevated - "igo_est_prop_vb_elevated"
- [x] Integrated VB Width - "igo_integrated_vb_width"
- [x] Moving Window Analysis Distance - "igo_moving_window_distance"
- [x] Acres of Estimated Low-Lying Valley Bottom per Mile - "igo_ac_lowlying_vb_mile"
- [x] Aces of Estimated Elevated Valley Bottom per Mile - "igo_ac_elevated_vb_mile"
- [x] Hectares of Estimated Low-Lying Valley Bottom per Kilometer - "igo_hec_lowlying_vb_km"
- [x] Hectares of Estimated Elevated Valley Bottom per Kilometer - "igo_hec_elevated_vb_km"

## Intermediates
- [x] SS: Slope Raster - "slope" 
- [x] SS: HAND Raster (composite) - "hand" 
- [x] SS: Transformed Slope Evidence - "norm_slope"
- [x] SS: Transformed HAND Evidence - "norm_hand" 
- [x] Valley Bottom Level Paths - "levelpaths_unique"
- [x] Catchment Wing Drainage Area - "catchment_wing_da"

## Inputs
- [x] Channel Area Polygons - "vbet_channel_area" 
- [x] Digital Elevation Model - "dem" 

## Hillshade
- [x] Hillshade - "hillshade"

**Comment by Cashe93** [comment]
@shelbysawyer @jtgilbert @joewheaton 
## QRV Video Walkthrough
https://youtu.be/vNoJV1E1BZM
