### ISSUE TITLE
Build roads.qml

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RiverscapesXML#59]
Build a `roads.qml` eqivalent to [roads.lyr](https://github.com/Riverscapes/RiverscapesXML/blob/master/Symbology/esri/Shared/roads.lyr)

**Comment by lauren-herbine** [comment]
pull request #61 addresses most of this. TNMFRC 6-8 symbology not where it needs to be yet. Current Arc symbols: 
![image](https://user-images.githubusercontent.com/73319684/118568642-7e986b80-b735-11eb-8a05-be74ec057338.png)
Current Q symbols:
![image](https://user-images.githubusercontent.com/73319684/118568661-9112a500-b735-11eb-9a94-67b2ed17b5a9.png)

**Comment by MattReimer** [comment]
#61 closes this
