### ISSUE TITLE
Integrated Geographic Objects (IGOs)

### ISSUE THREAD

**Issue by Cashe93** [Riverscapes/RiverscapesXML#602]
- [x] QRAVE
- [x] WebRAVE
- [x] ArcRAVE

**Comment by shelbysawyer** [comment]
Hey @Cashe93 just FYI I have this done for Q & Web already, I'll put it in the shared folder later today

**Comment by Cashe93** [comment]
Also, @shelbysawyer could you let me know when these have been moved to the shared folder?

**Comment by shelbysawyer** [comment]
@Cashe93 Sorry, I just realized the web symbology file I have for IGOs & DGOs is actually an old one that I did before I saw the updated documentation. I'll tag you when I move the Q symbology for DGOs & IGOs over to shared.

**Comment by Cashe93** [comment]
![image](https://github.com/Riverscapes/RiverscapesXML/assets/49880208/9aabab47-dc8b-4fff-92af-4f89b1f821ec)
