### ISSUE TITLE
Discrete Geographic Objects (DGOs)

### ISSUE THREAD

**Issue by Cashe93** [Riverscapes/RiverscapesXML#603]
- [x] QRAVE
- [ ] WebRAVE
- [ ] ArcRAVE

**Comment by Cashe93** [comment]
Oh, right on. Thanks, @shelbysawyer ! Which attribute did you end up using?

**Comment by shelbysawyer** [comment]
For the "base" DGO, I just did a single symbol-- no attribute. I used the proportion-style attributes (ex. prop active channel) for the "metric" DGOs that VBET displays.

**Comment by Cashe93** [comment]
![image](https://github.com/Riverscapes/RiverscapesXML/assets/49880208/eff91ed7-5484-41a4-a19b-2e6757f42d8a)
