### ISSUE TITLE
Vegetation Rasters

### ISSUE THREAD

**Issue by Cashe93** [Riverscapes/RiverscapesXML#604]
RCAT vegetation rasters appear to have been simplified into binary classes and require new symbology. @jtgilbert please correct me if I'm mistaken. 

- [x] Existing Riparian 
- [x] Historic Riparian 
- [x] Existing Vegetated 
- [x] Historic Vegetated

**Comment by Cashe93** [comment]
Riparian Vegetation 
---
![image](https://github.com/Riverscapes/RiverscapesXML/assets/49880208/40b287da-0086-4816-8e4b-aabc85af7de2)

Vegetated 
---
![image](https://github.com/Riverscapes/RiverscapesXML/assets/49880208/5c71de65-c71e-4a36-a61b-bc1f1d6e1c1b)

**Comment by jtgilbert** [comment]
yep this looks right.
