### ISSUE TITLE
Labels not showing up in WebRAVE 

### ISSUE THREAD

**Issue by Cashe93** [Riverscapes/RiverscapesXML#628]
## Specification

*Project Type*:  Riverscapes Context & VBET  
*Layer(s)*: 
- Channel Network Levelpaths (https://github.com/Riverscapes/RiverscapesXML/blob/master/Symbology/web/VBET/channel_levelpath.json)
- Stream names (https://github.com/Riverscapes/RiverscapesXML/blob/master/Symbology/web/VBET/streamnames.json)
- Counties (https://github.com/Riverscapes/RiverscapesXML/blob/master/Symbology/web/RSContext/counties.json)
- States (https://github.com/Riverscapes/RiverscapesXML/blob/master/Symbology/web/RSContext/states.json) 

### Description 

None of the recently curated labels are showing up in WebRAVE. I've noticed this with the layers that are using the new JetBrains or Karla text. I've attached links to the symbology JSON files and was hoping someone could point out the flaw.

**Comment by MattReimer** [comment]
@Cashe93 I've looked into it and it's 100% the font tag. Remove `text-font` from all symbologies so we can fall back to the defaults that webRave uses

**Comment by Cashe93** [comment]
Thanks, @MattReimer! I will dive back into this when I return from the field next week.

**Comment by Cashe93** [comment]
Alright, I think I got them all. Closing this issue. Thanks @MattReimer
