### ISSUE TITLE
Preparing `rsxml` module for PyPi deployment

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/RiverscapesXML#638]
In order to publish our `rsxml` we need our best foot forward. That includes metadata, help, readmes etc.

Here's what we need:

- [x] A good Readme: Introduction. why you need this, installation, basic usage, where to go for help, link to examples folder in the repo.
- [x] A `CHANGELIST.md` file we link to from the readme. It can be empty to start. 
- [x] Need a LICENSE file. MIT license is probably fine.
- [x] Improvements to metadata (`pyproject.toml` and `setup.py`) ([see docs](https://packaging.python.org/en/latest/tutorials/packaging-projects/))
- [x] More python examples (especially for the XML writing stuff)
    - [x] Better comments on examples to let people know why we're doing every step.
    - [x] Different use cases: (i.e. here's how you create a NEW xml, here's how you update an existing one)
- [x] A thought to versioning. What version should we start with? 
- [x] @philipbaileynar please make a [PyPi](https://pypi.org/manage/project/rsxml/releases/) account so that I can add you to the project

## Resources

- [Packaging Python Projects](https://packaging.python.org/en/latest/tutorials/packaging-projects/)

A good example of a package the looks good are:

- https://pypi.org/project/morecantile/
- https://pypi.org/project/convertbng/
- https://pypi.org/project/actinia-core/

You can probably steal a lot of config and ideas from them.

**Comment by philipbaileynar** [comment]
`ecosystem_id` was updated on production at 9:12 PST on 5 July 2023. CSV file of changes in git.

**Comment by MattReimer** [comment]
Looks good. Thanks for doing this.
