### ISSUE TITLE
D-inf flow direction symbology

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/RiverscapesXML#640]
The current symbology in TauDEM for D-inf flow direction goes from 0 to 8 which each integer separation being equated to a new cardinal direction. This isn't correct, though, because the output raster is assigned values from 0 to 2 pi (which is ~6.28) so the breaks associated with the different directions need to be recalculated and the symbology updated.

**Comment by jtgilbert** [comment]
@Cashe93 feel free to reassign

**Comment by Cashe93** [comment]
@jtgilbert the new symbology will now be based on the following values: 

0.79 - East
1.57 - Northeast
2.35 - North
3.14 - Northwest
3.93 - West
4.71 - Southwest
5.49 - South
6.28 - Southeast 

If this is incorrect, please advise.

**Comment by jtgilbert** [comment]
yep looks right
