### ISSUE TITLE
rsxml output elements

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/RiverscapesXML#654]
@Jdgilby is testing out building a custom project xml with rsxml. The output project.rs.xml file ends up with <ProjectType> after <Description> and the elements inside of <BoundingBox> in the wrong order so it doesn't validate.

**Comment by jtgilbert** [comment]
![rsxml](https://github.com/Riverscapes/RiverscapesXML/assets/21687931/3f63d5f2-6ee4-4171-b805-abbc85ac6477)

**Comment by MattReimer** [comment]
THis is a non-issue as it is likely related to an old copy of the `.lemminx` cache for vscode. Please delete that cache then close this issue if it's fixed.

**Comment by jtgilbert** [comment]
thanks @MattReimer I remember this now.
