### ISSUE TITLE
build temperature.qml

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/RiverscapesXML#66]
Please create a new temperature.qml equivalent to temperature.lyr

**Comment by shelbysawyer** [comment]
@joewheaton Running into a snag on this one. I'm not sure how to create the .qml so that the range the gradient is being stretched over is the same, no matter the "local" huc12 extent being looked at. Pictures below to demonstrate what I mean:
<img width="1113" alt="arc" src="https://user-images.githubusercontent.com/73311751/118720785-45b8cf00-b7e7-11eb-81c4-21e3194d5760.PNG">
<img width="1023" alt="Q" src="https://user-images.githubusercontent.com/73311751/118720797-4b161980-b7e7-11eb-9800-3f0b2e28d570.PNG">

**Comment by joewheaton** [comment]
Yes... We need to both tap Weber for his experience and expertise as well as find some better documentation out there.

**Comment by shelbysawyer** [comment]
@nick4rivers Hi Nick, do you have time to lend a little knowledge on this for @lauren-herbine and I? I used Visual Studio Code to manually set the max/min, but it ended up changing the stretch on my color ramp.

**Comment by nick4rivers** [comment]
Arggg...Sorry - @shelbysawyer and @lauren-herbine, I haven't played with this enough to know how everything behaves. You're going to have to let me know what you find? Sorry I couldn't be of help.

**Comment by joewheaton** [comment]
@philipbaileynar and @wally-mac , I am wondering if we can think about who would be good to task with figuring this out a little better and providing some documentation for everyone else. The symbology is powerful, but some things are hard to dial in.

**Comment by shelbysawyer** [comment]
@tyler1218hatch [Here](https://youtu.be/EAQDQ-EgkN8) is a little more information about my specific questions regarding this layer. Thank you!

**Comment by tyler1218hatch** [comment]
@shelbysawyer Here's my thoughts. I'm not an expert here, but this might help clarify things a little bit: [https://youtu.be/ATop3qhVf6Y](https://youtu.be/ATop3qhVf6Y)

**Comment by shelbysawyer** [comment]
@tyler1218hatch Thanks for this! I watched it last week and am just now circling back.. I'm going to play around with it a bit more, but I think what you've laid out in your video is a very workable solution.

**Comment by lauren-herbine** [comment]
@shelbysawyer let's go over this in the office on Tuesday- everything @tyler1218hatch laid out in his video makes sense, but I want to make sure I am incorporating the text file color ramps into the right part of the business logic process.

**Comment by shelbysawyer** [comment]
@lauren-herbine I'm in office Monday and Tuesday this week 7am - 3pm MT and Wednesday, roughly 6am - 10:30am. Wanna check this out together?

**Comment by joewheaton** [comment]
This is superseded by #191
