### ISSUE TITLE
Update Channel Network Levelpaths symbology in VBET

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/RiverscapesXML#684]
## Specification
*Project Type*:  `VBET 3.1.0` 
*Layer*: Channel Network Level Paths
*Type* - Vector

Example project: (https://data.riverscapes.net/rv/daa1a33e-faf2-42b1-9b3f-eb77f1817f4f)

## Description and/or Explanation of Need
1. In Q Viewer, the current labels for the VBET Level Paths layer have decimal points. As they are IDs and shouldn't have this, it would be great to get rid of them.

![Screenshot 2024-01-12 100545](https://github.com/Riverscapes/RiverscapesXML/assets/73311751/b00f3ff4-69a7-423d-b514-214736bc8075)

2. In Web Viewer, the labels are very difficult to make sense of (visually) at the project scale:

![Screenshot 2024-01-12 101551](https://github.com/Riverscapes/RiverscapesXML/assets/73311751/96eab0f6-6ac8-4ebb-bd14-19a29a5ad17c)

## Example of Inspiration
1. In Q Viewer, I can drop the decimal points by using an expression `to_real("vbet_level_path")` on the label value (`vbet_level_path`):

![Screenshot 2024-01-12 101154](https://github.com/Riverscapes/RiverscapesXML/assets/73311751/441b196e-6433-4f93-bffe-b7f82a39a065)

2. In Web Viewer, the labels look okay once zoomed in (in that they are more spread out), but the font is very small:

![Screenshot 2024-01-12 102037](https://github.com/Riverscapes/RiverscapesXML/assets/73311751/688e4621-df19-4604-b304-fc0fa8b4d615)

-------
## Questions
Before I can write out my tasks, I need to answer 2 questions:
1. Can this expression (or some other way of removing the decimals) be baked into the .qml, or is this just something we have to live with?
2. Did we ever find a way to specify showing labels differently at different zoom levels? If so, it would be great to not show Channel Network Levelpaths until zoom level 13 or 14 (ideally) and bumping up the font size a bit to make them easier to read. The way they display at different zoom levels in Q Viewer is really nice in that regard (zoom levels and font size). 

@Cashe93 tagging you here in case you have any experience / insight with either of these questions

## Tasks
- [x] Change the name from "Channel Network Levelpaths" to "Channel Network Level Paths" to align with USGS (and our) documentation.

**Comment by Cashe93** [comment]
@shelbysawyer, these issues should be resolved. Take a look and let me know if any further changes need to be made.

**Comment by shelbysawyer** [comment]
@Cashe93 Thank you! Both look so much better!

**Comment by shelbysawyer** [comment]
Closing this because all relevant pull requests have now been merged.
