### ISSUE TITLE
Parentheses out of layer names

### ISSUE THREAD

**Issue by nick4rivers** [Riverscapes/RiverscapesXML#693]
Please get rid of the () in the Active Channels and Centerlines layer names. It's inconsistent with all the rest of the layer names and is asking for trouble when writing calculations. Come on people....is this amateur hour.

![Screen Shot 2024-01-24 at 3 29 49 PM](https://github.com/Riverscapes/QRiS/assets/34071692/fdcb12c4-d50a-4d0f-831b-5df47d661c0d)

**Comment by KellyMWhitehead** [comment]
This is a change that needs to me made to the project database as part of layer json used to build the virtual fields.

**Comment by KellyMWhitehead** [comment]
Updated for 0.3.9
