### ISSUE TITLE
Remove VBET Synthesis

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/RiverscapesXML#697]
Please remove the VBET synthesis project type from the Data Exchange. You can delete any projects associated with it.

This was a precursor to the "RME metric scrape".

**Comment by shelbysawyer** [comment]
@philipbaileynar Will the RME metric scrape be up on the RDE soon?

**Comment by philipbaileynar** [comment]
I have an RME scrape from January that I could put up into the RDE, perhaps as soon as next week.

FYI @shelbysawyer We are just finishing a phase of intensive model improvements. All models have had some serious love, right from Riverscapes Context down to RME ([new waterfall diagram](https://docs.google.com/drawings/d/1XEwPYqRHhiQ4Wd6ui8lKxrdeUCnqDNaf5QQS9KZZPJI/edit?usp=sharing)).

We have 4 important workshops for the BLM between now and middle of March. As soon as those are behind us, we are going to re-run all models for Mississippi to the west coast. This includes RME and also a new scrape. We hope to have all the models run and in the RDE by middle/end April.

**Comment by shelbysawyer** [comment]
@philipbaileynar That's really exciting. Last November, it sounded like a future version of the scrape would allow riverscape metrics to be queried by FCode (e.g. perennial vs intermittent riverscapes) and ecoregion (e.g., avg valley bottom width by ecoregion). I'm somewhat out of the loop on where VBET 3.2.4 / RME stands-- has this already been implemented in the January scrape and/or is it planned in the April RME scrape?

**Comment by philipbaileynar** [comment]
Disregard this request.
