### ISSUE TITLE
build symbology for confinement ratio

### ISSUE THREAD

**Issue by lauren-herbine** [Riverscapes/RiverscapesXML#72]
Start building confinement project symbology

**Comment by joewheaton** [comment]
Make sure to use the O'Brien et al. (2019) confinement paper for your symbology inspiration. Pink for active confining margins. etc... 

![image](https://user-images.githubusercontent.com/9723905/119069158-d38ce980-b9a2-11eb-957a-03e997c2ea3f.png)
![image](https://user-images.githubusercontent.com/9723905/119069201-ebfd0400-b9a2-11eb-9e6f-68ee4e5dfb89.png)
