### ISSUE TITLE
Make a video about WebRave VECTOR symbology

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/RiverscapesXML#76]
Here are rough steps to get something symbolized for the web. Ask any questions below.

1. In QGIS Export your layer as GeoJSON. Projection doesn't really matter but you might save yourself some trouble by using WGS84 so that you can throw baselayers under it in mapbox.
   * You may need to remove the crs line that qgis seems to give it.: `"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },` Mapbox doesn't seem to support that
   * If the file is too big for mapbox consider using a smaller HUC or not exporting fields you have no intention of symbolizing. You can also remove features in your layer to make it a more manageable size. We're just looking for a small, representative dataset that will let us work over a few zoom ranges.
2. Log into Mapbox Studio. Click the styles tab and create a new style. Choose the blank template. Give it a good name
3. Go to layers and add a new layer. You should get an "Upload Data" option where you can drag and drop your geojson into a box. The notifications in the bottom right will tell you when it's done or if there are problems with the file upload or parsing.
4. Now use the studio to symbolize with a few guidelines
   * You need to duplicate the layer and change the type to get things like labels. So, for example, you might have one mapbox layer for symbols (labels), one for line styling and one for polygon fill styling. All layers consume from the same datasource.
   * You can add copies of your datasource and convert them for things like labels, lines, polygons etc but you're not allowed to use anything else. Everything must derive from the geojson file you uploaded.
   * You can add support layers like satellite maps underneath to help you see what your map will look like but you need to make sure these don't end up in the final product below. More about that later.
5. When you're happy click the share button and export your style to a zip file.
6. Unzip and pull out the JSON file inside.

Here's what you're going to be looking at.

```json
{
    "version": 8,
    "name": "WebRave Export demo",
    "metadata": {
        "mapbox:autocomposite": true,
        "mapbox:type": "template",
        "mapbox:sdk-support": {
            "android": "9.3.0",
            "ios": "5.10.0",
            "js": "2.0.0"
        },
        "mapbox:groups": {},
        "mapbox:uiParadigm": "layers"
    },
    "center": [-115.7276920252901, 46.04100776943545],
    "zoom": 10.688254550618892,
    "bearing": 0,
    "pitch": 0,
    "sources": {
        "mapbox://mapbox.satellite": {
            "url": "mapbox://mapbox.satellite",
            "type": "raster",
            "tileSize": 256
        },
        "composite": {
            "url": "mapbox://northarrowresearch.5pojlt0g",
            "type": "vector"
        }
    },
    "sprite": "mapbox://sprites/northarrowresearch/ckox2hmjq0yn517p5re1fbtbb/ck2u8j60r58fu0sgyxrigm3cu",
    "glyphs": "mapbox://fonts/northarrowresearch/{fontstack}/{range}.pbf",
    "layers": [
        {
            "id": "mapbox-satellite",
            "type": "raster",
            "source": "mapbox://mapbox.satellite",
            "layout": {"visibility": "none"},
            "paint": {}
        },
        {
            "id": "bratreachgeometry-bv59z4",
            "type": "line",
            "source": "composite",
            "source-layer": "bratReachGeometry-bv59z4",
            "layout": {},
            "paint": {"line-color": "hsl(0, 100%, 44%)", "line-width": 10}
        },
        {
            "id": "bratreachgeometry-bv59z4 copy",
            "type": "symbol",
            "source": "composite",
            "source-layer": "bratReachGeometry-bv59z4",
            "layout": {"text-field": ["get", "NHDPlusID"]},
            "paint": {"text-color": "hsl(0, 0%, 100%)"}
        }
    ],
    "created": "2021-05-20T15:47:03.419Z",
    "modified": "2021-05-20T15:54:44.257Z",
    "id": "ckox2hmjq0yn517p5re1fbtbb",
    "owner": "northarrowresearch",
    "visibility": "private",
    "draft": false
}
```

7. Copy layers array and paste it into a new file. 

In this case my new JSON file looks like this:

```json
[
	{
            "id": "bratreachgeometry-bv59z4",
            "type": "line",
            "source": "composite",
            "source-layer": "bratReachGeometry-bv59z4",
            "layout": {},
            "paint": {"line-color": "hsl(0, 100%, 44%)", "line-width": 10}
        },
        {
            "id": "bratreachgeometry-bv59z4 copy",
            "type": "symbol",
            "source": "composite",
            "source-layer": "bratReachGeometry-bv59z4",
            "layout": {"text-field": ["get", "NHDPlusID"]},
            "paint": {"text-color": "hsl(0, 0%, 100%)"}
        }
]
```

Name it the same way you would for qml files but these should have a `json` suffix. the basename should be identical to what you find in the `symbology="dem"` attribute of the business logic. The suffix should be lowercase `.json`. CASE MATTERS!!

``` bash
# so if the qml file path looks like this:
Symbology/qgis/Shared/dem.qml

# your file should look like this
Symbology/web/Shared/dem.json
```

Everything else about how you upload this should be the same as `.lyr` or `.qml` files

**Comment by joewheaton** [comment]
This is awesome @MattReimer... I will do a little 0.5 day to full day workshop in 3 weeks on this in the lab and get all of the ETAL crew, my grads, and Weber dialed on all three platforms (web, Q and Arc). I need enough reps and time under my belt to do this so I can understand it an explain it. @philipbaileynar showed a quick demo of how to do this earlier... looked super straight forward.

My only question at this stage is: I presume you will be making us a `web` subfolder to go along side `qgis` and `esri` in [`RiverscapesXML/tree/master/Symbology`](https://github.com/Riverscapes/RiverscapesXML/tree/master/Symbology), and we just dump everything in either the shared or the appropriate model subfolder as with the other two?

**Comment by MattReimer** [comment]
Exactly. The files should all have the same base names and path patterns.

**Comment by philipbaileynar** [comment]
http://rave.riverscapes.xyz/Web_RAVE/Technical_Reference/vector_symbology.html
