### ISSUE TITLE
Update vbetLikelihood.qml

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/RiverscapesXML#78]
I am updating the symbology for the VBET likelihood raster from a white-to-black gradient to a green-to-brown gradient. 

I think it's a helpful visual cue for the likelihood of a given area being active / wetted (green) or inactive / dry (brown).

**Comment by shelbysawyer** [comment]
It should look like this:
<img width="1022" alt="VBETlikelihoodraster" src="https://user-images.githubusercontent.com/73311751/119044680-bc84d200-b977-11eb-8460-8c54daa3e4c5.PNG">

**Comment by joewheaton** [comment]
Thanks for this @shelbysawyer ...  Two things:
1. When showing rasters for screen shots, always have the hillshade on underneath so we can see the transparent behavior and they pop.
2. Nice job on this. This could work just fine. This is the one that I was telling you I made, but screwed up something.
 I actually made one of these that is not continuous: 
![image](https://user-images.githubusercontent.com/9723905/119050083-9b73af80-b97e-11eb-8dfb-90488f476d34.png)

I did actually make a [`vbetLikelihood.qml`](https://github.com/Riverscapes/RiverscapesXML/blob/master/Symbology/qgis/VBET/vbetLikelihood.qml) and got it merged in with my last pull request. I must have screwed up the business logic or something in getting it used.

**Comment by shelbysawyer** [comment]
Oh, okay! That makes sense @joewheaton

I fixed the typo in the business logic, which was the symbology key for this raster.. that must have been why it wasn't showing up.

<img width="1023" alt="VBETlikelihoodraster" src="https://user-images.githubusercontent.com/73311751/119054025-286d3780-b984-11eb-9312-3f166cc0459f.PNG">

Maybe the way you have it set up is more logical. If we keep with the original `vbetLikelihood.qml` from your last pull request, then users are seeing the same information across the likelihood raster, outline, and transparent polygons symbolized in roughly the same colors. This makes sense, for sure. What do you think?

**Comment by joewheaton** [comment]
BTW... I like your color ramp. Maybe we duplicate the layer in the business logic and have both?

Also... nice fix on that typo I made ;)

**Comment by shelbysawyer** [comment]
@joewheaton Now that I'm playing around with these layers a bit more, I think this color ramp might be more fitting for the Combined Topographic Evidence (#92) and that your original `vbetLikeligood.qml` is the better fit for this layer. So.. with all of this fantastic version control magic, how can I get rid of the commit with my `vbetLikeligood.qml`?

**Comment by joewheaton** [comment]
@shelbysawyer, with regards to:
`So.. with all of this fantastic version control magic, how can I get rid of the commit with my vbetLikeligood.qml?`

We might need to ask @philipbaileynar, but I think you can just recall your specific commit?

**Comment by shelbysawyer** [comment]
@philipbaileynar Philip, the complicating factor here is that Joe's .qml for vbetLikelihood was misspelled, so when I revert it back to before I took his out and replaced it with mine, the symbology key edit that I made to the business logic will prevent it from displaying. Do you think the easiest thing would be to first revert my commit where I replaced his .qml with mine and then edit the name of his so that it matches the properly-spelled symbology key? I haven't to do this before, and I'm a little confused about the proper order of steps.

**Comment by MattReimer** [comment]
Hey @shelbysawyer I'll jump in here. In general we don't ever get rid of commits. There will be one commit where the file is added and one commit where the file is deleted, renamed or whatever. Make the repo the way you want then commit any additions or deletions and push that.

BTW: You can point all your git questions my way. I love that stuff. Also typing about this stuff is hard so give me a ping on email or gchat if you want to do a quick 5-min call with a demo. Much easier if I can see your screen.

**Comment by joewheaton** [comment]
Too bad Joe can't spell. 

> Hukt on ph0nix werkt 4 me!

**Comment by joewheaton** [comment]
Try something like this @shelbysawyer 
![image](https://user-images.githubusercontent.com/9723905/128556475-2080728b-8301-4d25-a965-5f82018b34ad.png)

**Comment by joewheaton** [comment]
This is done.
