### ISSUE TITLE
Updated VBET project to work with

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/RiverscapesXML#79]
I'm going to dive deeper into defining the VBET symbology in QGIS and ArcMap this week and next. 

Right now, the VBET projects I have access to have the valley bottom layers as single, whole polygons. Is there a VBET project that I could get my hands on that has the segmented valley bottoms? @joewheaton suggested that I be working in the most updated version we have-- thanks!

**Comment by joewheaton** [comment]
@KellyMWhitehead I know you have got the valley bottom segmentation working as well as valley bottom centerlines. Do you have any projects that @shelbysawyer could play with on that? What we were looking at yesterday on the call was not that... (i.e. the valley bottom feature class is one feature or one row). I want to get Shelby doing business logic and symbology on what we'll actually be looking at where that is segmented. We may want to discuss whether we want both (i.e. a segmented version and a merged version).

**Comment by KellyMWhitehead** [comment]
Here is a project with segmented valleys and centerlines:

https://data.riverscapes.xyz/#/PUBLIC_DATA/0dc1c4b1-8f5c-4f43-a584-7bf50668fc60

Note there will be small overlap between the segmented polygons.

**Comment by joewheaton** [comment]
Thanks so much @KellyMWhitehead for this. So when I try to load this project in QRAVE, I get see :
`2021-05-20T18:12:40     CRITICAL    Error loading project : Project: E:\0_RS\VBET\Valley_Bottom_Extraction_Tool_VBET-17060304\project.rs.xml
              Exception: 'id'`

```

- [ ] @KellyMWhitehead and potentially @philipbaileynar should skim the first 15 minutes of [this video](https://youtu.be/pxwapXjZSMA) and there are some discussion points and questions we may want to flesh out here and/or break into new issues. 
- [ ] @lauren-herbine should watch the first five minutes of [this video](https://youtu.be/pxwapXjZSMA) to see the new segmented valley bottoms and maybe a little further in to see the centerlines.
- [ ] @shelbysawyer should watch all of this and create new tasks for yourself to build symbology in QRAVe and ArcRAVE for all things exposed in the current project, and make sure "everything important" (e.g. centerlines) is exposed in the business logic.
- [ ] @MattReimer and/or @KellyMWhitehead from 16 minutes on you'll see me try to open the same project in QRAVE and it crash and not display the same business logic. We should create new ticket(s) as you see appropriate to fix that bug if that is what it is.

**Comment by MattReimer** [comment]
Opened up a QRave issue for this:
https://github.com/Riverscapes/QRAVEPlugin/issues/20
