### ISSUE TITLE
Symbology for Channel Euclidian Distance

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/RiverscapesXML#82]
Create:
- [x] channeldistance.lyr
- [ ] channeldistance.qml

**Comment by shelbysawyer** [comment]
<img width="1261" alt="channeldistance" src="https://user-images.githubusercontent.com/73311751/119187826-14ced900-ba37-11eb-8dd2-22fd91612e8c.PNG">

@joewheaton My thought here is to have a white-to-blue color ramp for the Channel Euclidean Distance color ramp, with blue being closest to channel and white being furthest away. What do you think? My only concern here is that if users are trying to look at it with the VBET network turned on, the blues may be too similar. I'll post another picture below of that.

**Comment by shelbysawyer** [comment]
<img width="1021" alt="channeldistancenetwork" src="https://user-images.githubusercontent.com/73311751/119189249-113c5180-ba39-11eb-981f-5e1e1fb5f48c.png">

**Comment by shelbysawyer** [comment]
Once we like the look of the .lyr I've created, I'll cook up the .qml

**Comment by joewheaton** [comment]
This looks good to me as far as color ramp goes. I do think though we should switch to categories and use distances that will correspond to the breaks we use in our transform function.

**Comment by shelbysawyer** [comment]
I know we haven't determined the breaks yet, but I can update them when they are settled. For now, here's what it should look like now, with symbology categorized.
<img width="937" alt="channeldistance" src="https://user-images.githubusercontent.com/73311751/122228691-18af1900-ce86-11eb-8676-8155f042d90d.PNG">

Here's a view of what it looks like zoom-in:
<img width="938" alt="distance2" src="https://user-images.githubusercontent.com/73311751/122228695-1a78dc80-ce86-11eb-8b26-829c8e675a41.PNG">

**Comment by joewheaton** [comment]
Beautiful, but now on account of https://github.com/Riverscapes/riverscapes-tools/issues/369 no longer necessary (sorry)
