### ISSUE TITLE
Flow Area Euclidean Distance Symbology

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/RiverscapesXML#83]
- [x] Update BL to include "flowarea_dis" symbology key
- [x] Create flowarea_dis.lyr
- [ ] Create flowarea_dis.qml

**Comment by shelbysawyer** [comment]
Here's what it should look like:
<img width="1020" alt="flowarea" src="https://user-images.githubusercontent.com/73311751/119202976-3d62cd00-ba4f-11eb-86eb-c2e114df8279.png">

@joewheaton What do you think? Once we settle on a look for this, I'll make the .qml

**Comment by shelbysawyer** [comment]
I have updated this-- here's the new look:
<img width="1014" alt="flowarea" src="https://user-images.githubusercontent.com/73311751/119742454-12a8b800-be45-11eb-8857-ce4280a22ca3.png">

**Comment by joewheaton** [comment]
Similar to #82, I think we should be using categorical on these to correspond to how we use transform functions (this time on 0 to 1) and use some simple labels (e.g. "Immediately Adjacent", "Near" , "Far" or something... )

**Comment by shelbysawyer** [comment]
@joewheaton That makes a lot of sense.. I'll get a draft of that symbology created and provide updated screenshots here.

**Comment by joewheaton** [comment]
@shelbysawyer maybe I should have approved that pull request? It was hard to find this from review of pull request as it wasn't part of commit or directly in the pull request itself. This looks great though.

**Comment by joewheaton** [comment]
As with others, this is beautiful, but goes away.
