### ISSUE TITLE
VBET ArcRAVE Symbology for Normalized Rasters

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/RiverscapesXML#91]
Create ArcRAVE symbology (.lyr) for the normalized raster layers:

- [x]  norm_slope.lyr
- [x]  norm_hand.lyr
- [x]  norm_channel.lyr
- [x]  norm_flow.lyr

**Comment by shelbysawyer** [comment]
For the normalized evidence rasters (slope, HAND, channel distance, flow area distance), I have the .lyr files (norm_slope.lyr, norm_hand.lyr, norm_channel.lyr, norm_flow.lyr) ready to go, but I'm not sure how to go about building their symbology into the BL (#90). I wanted to get a first run in of trying on some looks for these rasters. 

@joewheaton I'll attach pictures of each below.. for now, I've left them all as gradients instead of classified. We still have to discuss if this is the best route. I'm leaning towards yes for a few different reasons, but I'd like to get your thoughts. I think keeping a consistent color scheme between the evidence rasters and the normalized evidence rasters is best, either way.

**Normalized Flow Area Distance:**
<img width="1019" alt="norm_flow" src="https://user-images.githubusercontent.com/73311751/119742038-299ada80-be44-11eb-8064-7654e899b320.png">

**Normalized Channel Distance:**
<img width="1021" alt="norm_channel" src="https://user-images.githubusercontent.com/73311751/119742044-2d2e6180-be44-11eb-9cd9-9fff51cd3371.png">

**Normalized Slope:**
<img width="1019" alt="norm_slope" src="https://user-images.githubusercontent.com/73311751/119742049-30295200-be44-11eb-80bc-7ca000ac9773.png">

**Normalized HAND:**
<img width="1025" alt="norm_hand" src="https://user-images.githubusercontent.com/73311751/119742062-33bcd900-be44-11eb-85da-e98eab6cc8d2.png">

**Comment by joewheaton** [comment]
Thanks for these @shelbysawyer. 
- I like the use of a similar color scheme/ramp to originals.
- I'm inclined to go with this for now.
- I am thinking we will either want to switch to or also create a categorized ramp that uses the *new* values from the transform functions

**Comment by joewheaton** [comment]
I really like the slope and HAND ones... the others I am not so sure on yet.

**Comment by joewheaton** [comment]
Channel goes away. Slope and HAND are good. Need new one for TWI.

**Comment by shelbysawyer** [comment]
Covered in #213
