### ISSUE TITLE
VBET ArcRAVE Combined Evidence Raster Symbology

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/RiverscapesXML#92]
Add the following symbology keys to the BL:

- [x] channelevidence
- [x] topoevidence

Create the following:

- [x] channelevidence.lyr
- [x] topoevidence.lyr

**Comment by shelbysawyer** [comment]
@joewheaton When choosing the look of these layers, I tried to reflect on what the layers are actually telling the user. 

For the combined topography evidence, I went with a green-tan gradient to emphasize that the likelihood of an area being valley bottom in this layer is based on slope and HAND.. so: what's getting wetted (and therefore more likely to be green) as a result of where it sits on the landscape. 

For the combined channel distance evidence, I went with blue-tan gradient to emphasize that this layer is showing the likelihood of valley bottom based on channel and flow area distance.. so what's getting wet as a result of its proximity to water.

I know this is a basic take, but sometimes simple is good. What do you think?

Combined Channel Evidence:
<img width="1027" alt="channel_evidence" src="https://user-images.githubusercontent.com/73311751/119746926-d712eb80-be4e-11eb-8f1c-32ebbde5830b.PNG">

Combined Topographic Evidence:
<img width="1022" alt="topo_evidence" src="https://user-images.githubusercontent.com/73311751/119746933-da0ddc00-be4e-11eb-80a7-edd18c12bd7c.PNG">

**Comment by joewheaton** [comment]
I like the color ramps on both these. We might need to stretch them or even categorize them using the breaks we end up using. We can discuss.

**Comment by shelbysawyer** [comment]
Addressed in changes we made to the business logic and the symbology in #230
