### ISSUE TITLE
VBET Thiessen Reaches & Drainage Areas Symbology

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/RiverscapesXML#94]
Add the following symbology keys to the BL:

- [x] thiessenpoints
- [x] thiessenpoints
- [ ] drainagearea_zone
- [ ] drainagearea_slope
- [ ] drainagearea_hand

Create the following .lyr files:

- [ ] thiessenpoints.lyr
- [ ] thiessenpoints.lyr
- [ ] drainagearea_zone.lyr
- [ ] drainagearea_slope.lyr
- [ ] drainagearea_hand.lyr

Create the following .qml files:

- [ ] thiessenpoints.qml
- [ ] thiessenpoints.qml
- [ ] drainagearea_zone.qml
- [ ] drainagearea_slope.qml
- [ ] drainagearea_hand.qml

**Comment by shelbysawyer** [comment]
@joewheaton I'm having the same problem here as I did in #90 -- I can't see where in the BL to insert the symbology keys that belong to repeater layers. Maybe a quick call for some help on this?

**Comment by shelbysawyer** [comment]
Closing this as these will no longer be exposed

**Comment by joewheaton** [comment]
These are what @KellyMWhitehead uses to make his reach breaks, but not that insightful....
![image](https://user-images.githubusercontent.com/9723905/128555370-14aeb9fe-294e-456f-bb5a-02aaa28fd7db.png)

So lets not expose them. 

- [ ] Remove whole group from business logic.
